### PR TITLE
fix: Podman dashboard still proposes to update after podman installation

### LINKED ISSUE #1498: podman dashboard still proposes to update after podman installation
### Bug description

I had Podman 4.4.0 installed:

image

So I clicked on Update to 4.4.1 and once the installation is done, the page is updated but the Update button is still there

image

### Operating system

Win11 Pro

### Version

0.12.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #1498

### What does this PR do?

Ensure the Update to ... is not shown anymore after update has been processed

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #1498 

### How to test this PR?

1. Have Podman 4.4.4 installed
2. Launch Podman Desktop
3. Update to 4.5.0 is shown
4. Update to 4.5.0
5. Update to 4.5.0 not shown anymore

### CODE REVIEW

File: packages/renderer/src/lib/dashboard/ProviderStatusTestHelper.ts [hunk 1]
```diff
@@ -0,0 +1,72 @@
+/**********************************************************************
```
Comment (benoitf) [inline packages/renderer/src/lib/dashboard/ProviderStatusTestHelper.ts]: I have only one remark. Here I think it's the first time we have a file only dedicated to the test but not with .spec.ts pattern, so are we sure it will not go to the final assembly/be excluded ?

Should we name it ProviderStatusTestHelper.spec.ts ?

**Review by benoitf — APPROVED** [review]

File: packages/renderer/src/lib/dashboard/ProviderStatusTestHelper.ts (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/lib/dashboard/ProviderStatusTestHelper.ts]: (I think it won't work with a spec.ts file but I don't know what should be the best approach like separate folder or another thing)
