### PR TITLE
fix: avoid unhandled error when starting with invalid kubeconfig file

### LINKED ISSUE #2052: unable to get dashboard if kind cluster (or kubernetes cluster is not alive)
### Bug description

There is an error 

Error: connect ECONNREFUSED 127.0.0.1:52803

### Operating system

macOS

### Version

next (development version)

### Steps to reproduce

start Podman Desktop with a non functional cluster

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
catch/Log the error

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/2052

### How to test this PR?

use a $HOME/.kube/config file with a non-reachable cluster

Change-Id: I14debf79edab0ce557990ba8153d647434214e38

### CODE REVIEW

File: packages/main/src/plugin/kubernetes-client.ts [hunk 1]
```diff
@@ -240,9 +240,14 @@ export class KubernetesClient {
...
-      if (namespaces?.body?.items.length > 0) {
-        namespace = namespaces?.body?.items[0].metadata?.name;
+      try {
+        const namespaces = await ctx.makeApiClient(CoreV1Api).listNamespace();
+        if (namespaces?.body?.items.length > 0) {
+          namespace = namespaces?.body?.items[0].metadata?.name;
+        }
+      } catch (error) {
+        // unable to list namespaces, can be due to a connection refused (cluster not up)
+        console.trace('unable to list namespaces', error);
```
Comment (cdrage) [inline packages/main/src/plugin/kubernetes-client.ts:250]: So it will trace the error, but no erroring out?

I'm assuming it's fine for it to just revert back to `default`. but this is outside of the scope of the PR.

**Review by cdrage — APPROVED** [review]
Gave this a try and it was able to get the dashboard fine (I just added false info to my `.config/kube` to make it error).

One small comment, but otherwise this LGTM if you're okay with no further modifications.

**Review by lstocchi — APPROVED** [review]
LGTM

**Review by jeffmaury — APPROVED** [review]
LGTM
