### PR TITLE
fix(renderer/FilteredEmptyScreen): migrate to Svelte5

### LINKED ISSUE #11583: Migrate UI component screen to Svelte 5
https://github.com/podman-desktop/podman-desktop/blob/ce53e6c5bd49e87ed204b4275510079557f03a92/packages/ui/src/lib/screen/EmptyScreen.svelte#L1

https://github.com/podman-desktop/podman-desktop/blob/ce53e6c5bd49e87ed204b4275510079557f03a92/packages/ui/src/lib/screen/FilteredEmptyScreen.svelte#L1

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

Migrate FilteredEmptyScreen component to Svelte5

### What issues does this PR fix or reference?

Fixes #11583 

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — COMMENTED** [review]
I don't think we should remove the dispatch events for components in the UI package, as it may impact extensions.

We should be sure first, that at least all our extensions are using Svelte5 before moving on with such removal

File: packages/ui/src/lib/screen/EmptyScreen.svelte [hunk 1]
```diff
@@ -34,16 +34,12 @@ let {
   'aria-label': ariaLabel,
   upperContent,
   children,
-  onclick = (text): void => {
-    dispatch('click', text);
-  },
```
Comment (benoitf) [inline packages/ui/src/lib/screen/EmptyScreen.svelte]: please keep this, it allows backward compliance

this is how to proceed: provide callback or then it's dispatching an event

**Review by benoitf — CHANGES_REQUESTED** [review]
dispatchers should not be removed

it's ok to bring on* callbacks but it should dispatch event if the on* callback is not provided

**Comment by simonrey1** [comment]
I  searched in all podman-desktop repository, but I did not think about external usage of ui package.

Thanks for the warning!

However I don't understang your suggestions for implementation @benoitf ?

**Comment by simonrey1** [comment]
So i updated the PR to stay in the scope of updating to Svelte 5 and I left the deprecated event dispatchers here

**Comment by benoitf** [comment]
> I searched in all podman-desktop repository, but I did not think about external usage of ui package.

https://github.com/podman-desktop/extension-bootc/blob/main/packages/frontend/package.json#L30

> However I don't understang your suggestions for implementation @benoitf ?

https://github.com/podman-desktop/podman-desktop/blob/6bf0204c08fba31ef4d2143e67822a02b93b66ea/packages/ui/src/lib/screen/EmptyScreen.svelte#L37-L39

here you can see that the component works in both mode
svelte5: client will provide a callback method onclick

svelte4: if we don't change the existing code (we expect to receive an event 'click') it's still working as default method onclick is sending a click event

so it works in both mode

File: packages/ui/src/lib/screen/FilteredEmptyScreen.svelte [hunk 2]
```diff
@@ -4,19 +4,22 @@ import { createEventDispatcher } from 'svelte';
...
 const dispatch = createEventDispatcher();
 
 const defaultOnResetFilter = (): void => {
   if (dispatch('resetFilter', searchTerm, { cancelable: true })) {
     searchTerm = '';
   }
 };
-export let onResetFilter: () => void = defaultOnResetFilter;
+interface Props {
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (benoitf) [inline packages/ui/src/lib/screen/FilteredEmptyScreen.svelte:15]: use proper typing instead of any, I'm pretty sure we have other UI components with icon not being anyas it's basically
```
        {#if fontAwesomeIcon}
          <Icon icon={icon} size='4x'/>
        {:else}
          <Icon icon={icon} size=55/>
        {/if}
```

and if I look at Icon component I see

```
interface Props {
  icon: IconDefinition | Component | string;
```

so should use the same definition

**Review by benoitf — APPROVED** [review]

File: packages/ui/src/lib/screen/FilteredEmptyScreen.svelte (hunk 2 above)
Comment (simonrey1) [reply packages/ui/src/lib/screen/FilteredEmptyScreen.svelte:15]: Yes I noticed that too, but I don't know if it should come in a separate issue?
