### PR TITLE
fix(PinRegistry): listeners and VM support

### LINKED ISSUE #11974: bug(PinRegistry): do not notify when connections are registered / unregistered
### Bug description

When I wrote the PinRegistry, I did not try to create new kubernetes, or podman machine, so I missed this part. I used the following events (thinking it was enough), but it was not.

https://github.com/podman-desktop/podman-desktop/blob/89a4a47f0a22d942f5b80b6f12dee72093ec358b/packages/main/src/plugin/statusbar/pin-registry.ts#L125-L126

I need to use the following events `onDidRegister(Container | Kubernetes | vm)Connection` and `onDidUnregister(Container | Kubernetes | vm)Connection`

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

Noticed while testing https://github.com/podman-desktop/podman-desktop/pull/11973 and creating new kubernetes cluster

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

While testing https://github.com/podman-desktop/podman-desktop/pull/11973 I noticed that the pin registry was not updating when a new connection is registered, or one is unregistered.

- This PR fixes that, by registering to all register, unregister event.
- It also add support for VM providers (can be in a separate PR, but this a one liner, and I also add the register, unregister event related to VM so... make sense to update all)

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/11974

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/statusbar/pin-registry.ts [hunk 1]
```diff
@@ -121,8 +126,15 @@ export class PinRegistry implements IDisposable {
       this.notify();
     }
 
-    // notify if container connection / kubernetes connection changed
-    this.#disposables.push(this.providers.onDidUpdateContainerConnection(this.notify.bind(this)));
-    this.#disposables.push(this.providers.onDidUpdateKubernetesConnection(this.notify.bind(this)));
```
Comment (SoniaSandler) [inline packages/main/src/plugin/statusbar/pin-registry.ts:126]: question (nit): would using `onDidUpdate` in addition to `onDidRegister` and `onDidUnregister` in this case be redundant/not useful?

**Review by SoniaSandler — APPROVED** [review]
LGTM

File: packages/main/src/plugin/statusbar/pin-registry.ts (hunk 1 above)
Comment (axel7083) [reply packages/main/src/plugin/statusbar/pin-registry.ts:126]: onDidUpdate is triggered on status update (from my understanding) so it would not change the content of the PinRegistry options, as we only keep the providerId 🤔 .
