### PR TITLE
fix: minimize on startup plist for macOS

### LINKED ISSUE #12562: The dashboard always opens at startup
### Bug description

The dashboard always opens when the system starts. The setting "Minimize on login" does not affect the behavior.

### Operating system

macOS 15.5 (Apple silicon)

### Installation Method

Installer from website/GitHub releases

### Version

1.18.0

### Steps to reproduce

Just install the package from the official site, enable the "Minimize on login" setting and restart the system.

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cblecker**
### What does this PR do?
This feature broke due to #10500, as the minimize flag was not being actually passed to the podman desktop process, but bash.

### What issues does this PR fix or reference?

fixes #12562

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by MarsKubeX — APPROVED** [review]
LGTM (not tested)

**Review by benoitf — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
thanks @cblecker could you add a unit test

File: packages/main/src/system/macos-startup.ts [hunk 1]
```diff
@@ -87,10 +86,7 @@ export class MacosStartup {
     <array>
         <string>/bin/bash</string>
         <string>-c</string>
-        <string>/usr/bin/truncate -s 0 '${stdoutPath}'; /usr/bin/truncate -s 0 '${stderrPath}'; '${this.podmanDesktopBinaryPath}'</string>
-        ` +
-      minimizeSettings +
-      `
+        <string>/usr/bin/truncate -s 0 '${stdoutPath}'; /usr/bin/truncate -s 0 '${stderrPath}'; '${this.podmanDesktopBinaryPath}' ${minimizeSettings}</string>
```
Comment (dgolovin) [inline packages/main/src/system/macos-startup.ts:89]: This change breaks formatting in file and triggers change in line 79 above. Line 67 should be the only change.

**Review by dgolovin — CHANGES_REQUESTED** [review]

File: packages/main/src/system/macos-startup.ts (hunk 1 above)
Comment (cblecker) [reply packages/main/src/system/macos-startup.ts:89]: The cause of the bug is that the `--minimize` is in a separate `<string></string>` array item, so bash interprets it as an argument to itself, rather than an argument to the podman desktop binary. It needs to be inside the same `<string></string>` as the binary path.

If I only made the L67 change, the resulting plist would be:

```
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>/usr/bin/truncate -s 0 '~/Library/Logs/Podman Desktop/launchd-stdout.log'; /usr/bin/truncate -s 0 '~/Library/Logs/Podman Desktop/launchd-stderr.log'; '/Applications/Podman Desktop.app/Contents/MacOS/Podman Desktop'</string>
        --minimize
    </array>
```

This would be a malformed plist XML file, as the `--minimize` wouldn't be inside a string at all. Open to other suggestions at how to better format this, but I believe your suggestion as I understand it would not work.

**Comment by cblecker** [comment]
@benoitf I would appreciate some assistance to get a test written for this, as I don't write much in typescript and may not have the cycles to learn in a timely manner. Was just trying to fix the functional bug. Please feel free to carry the PR if that's easier (credit not needed, just trying to make podman desktop easier to use :) )

File: packages/main/src/system/macos-startup.ts (hunk 1 above)
Comment (dgolovin) [reply packages/main/src/system/macos-startup.ts:89]: My fault.

**Review by dgolovin — APPROVED** [review]

**Comment by dgolovin** [comment]
> @benoitf I would appreciate some assistance to get a test written for this, as I don't write much in typescript and may not have the cycles to learn in a timely manner. Was just trying to fix the functional bug. Please feel free to carry the PR if that's easier (credit not needed, just trying to make podman desktop easier to use :) )

@cblecker Not sure why I cannot see your your fork when trying to send PR. Here is my commit with possible test https://github.com/podman-desktop/podman-desktop/commit/86279dfd902787b478bbd53b210ff8f3dacc28b0

**Comment by cblecker** [comment]
Thank you @dgolovin ! Yeah, that test seems to work like a charm

**Comment by benoitf** [comment]
~~@cblecker it looks like the test is missing (the one suggested by Denis~~

now I see it, nevermind

**Comment by benoitf** [comment]
thanks @cblecker
