### PR TITLE
fix: respect appearance theme during render GitHub icon

### LINKED ISSUE #10007: Github registry icon doesn't update when switching to light mode
### Bug description

The Github registry icon doesn't reflect the appearance mode change:
Image

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?

According to the issue, GitHub icon should respect the theme change and be the light on the dark theme and dark on the dark on the light theme.

### Screenshot / video of UI

Снимок экрана 2025-01-16 в 17 32 44
Снимок экрана 2025-01-16 в 17 32 33

### What issues does this PR fix or reference?

#10007 

### How to test this PR?

Switch between themes and check that GitHub icon also changes own appearance.

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: extensions/registries/src/extension.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ import * as extensionApi from '@podman-desktop/api';
 
 import dockerIoImage from './images/docker.io.png';
 import gcrIoImage from './images/gcr.io.png';
-import ghcrIoImage from './images/ghcr.io.png';
+import ghcrIoImage from './images/ghcr.io.svg';
```
Comment (axel7083) [inline extensions/registries/src/extension.ts:22]: might need to create a Svelte component with the svg content in it.

Example https://github.com/podman-desktop/podman-desktop/blob/516922e2ef043c208d55e9921edda79f7798aa20/packages/ui/src/lib/icons/ContainerIcon.svelte

**Review by axel7083 — COMMENTED** [review]
I am wondering if we should not provide more flexibility for the icon property of `RegistrySuggestedProvider`

https://github.com/podman-desktop/podman-desktop/blob/be499999e49627d74cad14efe98c9dbe3fed1111/packages/extension-api/src/extension-api.d.ts#L1085

For example, we could allow multiple value (light, dark) like we do for other component

https://github.com/podman-desktop/podman-desktop/blob/be499999e49627d74cad14efe98c9dbe3fed1111/packages/extension-api/src/extension-api.d.ts#L1632

**Comment by vzhukovs** [comment]
> I am wondering if we should not provide more flexibility for the icon property of `RegistrySuggestedProvider`
> 
> https://github.com/podman-desktop/podman-desktop/blob/be499999e49627d74cad14efe98c9dbe3fed1111/packages/extension-api/src/extension-api.d.ts#L1085
> 
> For example, we could allow multiple value (light, dark) like we do for other component
> 
> https://github.com/podman-desktop/podman-desktop/blob/be499999e49627d74cad14efe98c9dbe3fed1111/packages/extension-api/src/extension-api.d.ts#L1632

Thanks for pointing this. Will take a look if we can do this, so will provide an update to the PR soon.

**Review by benoitf — COMMENTED** [review]
waiting changes as suggested by Axel

File: extensions/registries/src/extension.ts [hunk 2]
```diff
@@ -58,16 +53,11 @@ const defaultRegistries: extensionApi.RegistrySuggestedProvider[] = [
...
   },
   {
     name: 'Google Container Registry',
     url: 'gcr.io',
     icon: gcrIoImage,
   },
 ];
-
-// Remove data:image/png;base64,
-export function stripImagePrefix(imageContent: string): string {
```
Comment (axel7083) [inline extensions/registries/src/extension.ts:71]: some tests seems to be failing since this has been removed?

Comment (vzhukovs) [reply extensions/registries/src/extension.ts:71]: right, thanks, method was removed, but the following test wasn't, fixed in the following commit

**Review by cdrage — APPROVED** [review]
Tested and LGTM. The GitHub icon is displayed properly now.

**Review by axel7083 — APPROVED** [review]
Codewise LGTM
