### PR TITLE
fix: switched to sequential writing to containers.conf file

### LINKED ISSUE #10709: proxy configuration via podman-desktop gui settings breaks containers.conf
### Bug description

I changed my Podman-Desktop proxy settings via GUI > Settings > Proxy Settings multiple times (manual to disabled back and forth) and when disabling proxy configuration again, the "~/.config/containers/containers.conf" file got malformed.

```
$ podman pull quay.io/podman/hello
Failed to obtain podman configuration: reading system config "/Users/nicowde/.config/containers/containers.conf": decode configuration /Users/nicowde/.config/containers/containers.conf: toml: line 16 (last key "configmaps"): expected a top-level item to end with a newline, comment, or EOF, but got '0' instead
``` 

### Operating system

macOS Sequoia 15.1.1 (24B91)

### Installation Method

Brew (macOS)

### Version

1.15.0

### Steps to reproduce

- GUI > Settings > Proxy Settings
- for Proxy configuration select"Manual" ->  insert variables -> click "Update" button
- e.g. podman pull quay.io/podman/hello -> works
- for Proxy configuration select"Disabled" ->  click "Update" button
- e.g. podman pull quay.io/podman/hello (again) -> errors

### Relevant log output

malformed containers.conf:

```
[containers]


[engine]
env = []

[machine]


[network]


[secrets]


[configmaps]80", "http_proxy=http://redacted:1234", "no_proxy=localhost,.local,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1,.redact.ed,.redact2.ed,.re.dact.ed,.de.tcad.re,kubernetes.docker.internal" ]

[machine]


[network]


[secrets]


[configmaps]
``` 

clean / expected containers.conf (after hitting 'Update' via GUI > Settings > Proxy Settings)

```
[containers]


[engine]
env = [ "http_proxy=http://redacted:1234", "https_proxy=http://redacted:1234", "no_proxy=localhost,.local,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1,.redact.ed,.redact2.ed,.re.dact.ed,.de.tcad.re,kubernetes.docker.internal" ]

[machine]


[network]


[secrets]


[configmaps]
``` 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Adds sequential mechanism for writing to containers.conf file to avoid simultaneous write

### What issues does this PR fix or reference?
Closes #10709 

### How to test this PR?
Go to PD, try to restart podman machine and while stopping/starting try to edit proxy settings switching between manual/disabled/system

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
note: I don't think the issue is coming from this part

**Comment by gastoner** [comment]
@benoitf can you try this PR please? From my testing, it fixes the issue (tested remotely on Mac)

**Comment by benoitf** [comment]
to me it's not fixing the root problem, the cause. Changing would just hide/mask/reduce the issue

**Comment by gastoner** [comment]
Updated based on @jeffmaury tips

File: extensions/podman/packages/extension/src/podman-configuration.ts [hunk 1]
```diff
@@ -105,6 +107,20 @@ export class PodmanConfiguration {
     }
   }
 
+  async updateProxySettigsSync(proxy: ProxySettings | undefined): Promise<void> {
```
Comment (jeffmaury) [inline extensions/podman/packages/extension/src/podman-configuration.ts]: Looks wroong to me as if there is a promise then the proxy argument is not beging processed.

I was thinking of something:
if (!promise) {
  promise = this.updateProxySettings(proxy);
} else {
  promise.then(() => promise = this.updateProxySettings());
}

**Review by jeffmaury — CHANGES_REQUESTED** [review]

File: extensions/podman/packages/extension/src/podman-configuration.ts (hunk 1 above)
Comment (gastoner) [reply extensions/podman/packages/extension/src/podman-configuration.ts]: Thank you! Updated

**Comment by gastoner** [comment]
@jeffmaury PR Updated, can you please check again?

**Review by jeffmaury — APPROVED** [review]
LGTM

File: extensions/podman/packages/extension/src/podman-configuration.ts [hunk 2]
```diff
@@ -30,24 +30,26 @@ const configurationRosetta = 'setting.rosetta';
  * Manages access to the containers.conf configuration file used to configure Podman
  */
 export class PodmanConfiguration {
+  updatedProxySettingsPromise: Promise<void> | undefined = undefined;
```
Comment (axel7083) [inline extensions/podman/packages/extension/src/podman-configuration.ts]: We should have this private

File: extensions/podman/packages/extension/src/podman-configuration.ts [hunk 3]
```diff
@@ -30,24 +30,26 @@ const configurationRosetta = 'setting.rosetta';
...
+
   async init(): Promise<void> {
     let httpProxy = undefined;
     let httpsProxy = undefined;
     let noProxy = undefined;
 
     // we receive an update for the current proxy settings
     extensionApi.proxy.onDidUpdateProxy(async (proxySettings: ProxySettings) => {
-      await this.updateProxySettings(proxySettings);
+      await this.updateProxySettigsSync(proxySettings);
```
Comment (axel7083) [inline extensions/podman/packages/extension/src/podman-configuration.ts]: The `*Sync` method name is usually reserved for blocking io, see node method `existsSync`  :/ so having a await is a bit weird

File: extensions/podman/packages/extension/src/podman-configuration.ts [hunk 4]
```diff
@@ -105,6 +107,16 @@ export class PodmanConfiguration {
     }
   }
 
+  async updateProxySettigsSync(proxy: ProxySettings | undefined): Promise<void> {
+    if (!this.updatedProxySettingsPromise) {
+      this.updatedProxySettingsPromise = this.updateProxySettings(proxy);
```
Comment (axel7083) [inline extensions/podman/packages/extension/src/podman-configuration.ts]: We are not awaiting for `this.updatedProxySettingsPromise`, this is a problem? like do we want the `updateProxySettigsSync` to finish before the updateProxySettings promise resolved ?

Comment (gastoner) [reply extensions/podman/packages/extension/src/podman-configuration.ts]: The problem is that the `this.updateProxySettings()` function is called in some cases 2 times, which results in corrupted file. 
The purpose of this is to execute this function sequentially using promises/await

Comment (axel7083) [reply extensions/podman/packages/extension/src/podman-configuration.ts]: I feel like this is an issue to have several call, I would argue we should ignore the second one, or throw an error if the resource is locked.

The root cause is probably the fact that it is called twice.

Otherwise if this is not feasable, we should improve the method signature.

```
queueProxySettingsUpdate(proxy: ProxySettings | undefined): void;
```

This is not a sync operation, but a queue, as we chain the promises until resolve.
Please also add a cleaning mechanism, the promise should be undefined if all are resolved

**Review by benoitf — COMMENTED** [review]
suggestion:

adds https://www.npmjs.com/package/async-mutex

do :

```ts
// update the proxy only once at a time
extensionApi.proxy.onDidUpdateProxy(async (proxySettings: ProxySettings) => {
   await mutex.runExclusive(async () => {
     await this.updateProxySettings(proxySettings);   
   });
});
```

or do the mutex inside the proxySettings call  as you suggested

```ts
const mutex = new Mutex();

updateProxySettings(proxySettings) {
   await mutex.runExclusive(async () => {
     await this.doUpdateProxySettings(proxySettings);   
   });
}

doUpdateProxySettings(...) {

}
```

**Review by benoitf — COMMENTED** [review]
I would love to see a test ensuring that the method updateProxySetings is not called at the same time 

without the new code = it fails, with the new code it succeeed

Else LGTM

**Comment by gastoner** [comment]
@benoitf Added the lib, but I have some linting errors

> I would love to see a test ensuring that the method updateProxySetings is not called at the same time
> 
> without the new code = it fails, with the new code it succeeed
> 
> Else LGTM

I'll add the unit test, do you know how to fix the linter check? running the command does not work

**Comment by benoitf** [comment]
@gastoner yes you need to add the dependency in the package.json file of the extension of podman, not in the root package.json file

File: extensions/podman/packages/extension/src/podman-configuration.ts [hunk 5]
```diff
@@ -30,24 +31,26 @@ const configurationRosetta = 'setting.rosetta';
  * Manages access to the containers.conf configuration file used to configure Podman
  */
 export class PodmanConfiguration {
+  mutex: Mutex | undefined;
```
Comment (benoitf) [inline extensions/podman/packages/extension/src/podman-configuration.ts]: issue: initialize in the constructor and use private, it should not be accessible outside of this class

File: extensions/podman/packages/extension/src/podman-configuration.spec.ts [hunk 6]
```diff
@@ -165,3 +166,45 @@ describe('isRosettaEnabled', () => {
...
+
+  // Mock updateProxySettings to introduce a delay
+  const updateProxySettingsMock = vi.spyOn(podmanConfiguration, 'updateProxySettings').mockImplementation(async () => {
+    await new Promise(resolve => setTimeout(resolve, 100));
+  });
+
+  if (podmanConfiguration.mutex) {
+    // Spy on acquire and release
+    const acquireMock = vi.spyOn(podmanConfiguration.mutex, 'acquire');
+    const releaseMock = vi.spyOn(podmanConfiguration.mutex, 'release');
```
Comment (benoitf) [inline extensions/podman/packages/extension/src/podman-configuration.spec.ts]: AFAIK it should not be reading the value the private value

also what happens if the value is not defined ? all the test will be skipped without error

File: extensions/podman/packages/extension/src/podman-configuration.spec.ts [hunk 7]
```diff
@@ -165,3 +171,44 @@ describe('isRosettaEnabled', () => {
...
+
+  // Mock updateProxySettings
+  const updateProxySettingsMock = vi.spyOn(podmanConfiguration, 'updateProxySettings');
+
+  // Spy on acquire and release
+  const mutex = podmanConfiguration.getMutex();
+
+  const acquireSpy = vi.spyOn(mutex, 'acquire');
+  const releaseMock = vi.fn();
+  acquireSpy.mockResolvedValue(releaseMock);
```
Comment (benoitf) [inline extensions/podman/packages/extension/src/podman-configuration.spec.ts]: question: what I'm not understanding is why we need to intercept/monitor the mutex ?

Comment (benoitf) [reply extensions/podman/packages/extension/src/podman-configuration.spec.ts]: like for example if I throw 1000 events in parallel and the doUpdateProxySettings increment a value by one
at the end, do I have the counter being 1000 or as there well multiple calls in parallel it didn't increase correctly


Here I have the feeling that we're checking that the mutex library is working, while I would check that the method is really doing stuff sequentially

Comment (gastoner) [reply extensions/podman/packages/extension/src/podman-configuration.spec.ts]: To check that the functions are called in right order, or the locking/unlocking mechanism works as expected

Comment (gastoner) [reply extensions/podman/packages/extension/src/podman-configuration.spec.ts]: But need to test it on Mac once it is built

Comment (jeffmaury) [reply extensions/podman/packages/extension/src/podman-configuration.spec.ts]: I think mutex should not be exposed through test but rather that calls to updateProxySettings be done in the right order and with the expected parameters

**Review by jeffmaury — COMMENTED** [review]
See https://github.com/podman-desktop/podman-desktop/pull/10818/files#r1949496560

**Comment by gastoner** [comment]
@jeffmaury suggestions applied

**Review by jeffmaury — APPROVED** [review]
LGTM

File: extensions/podman/packages/extension/src/podman-configuration.spec.ts [hunk 8]
```diff
@@ -165,3 +166,26 @@ describe('isRosettaEnabled', () => {
...
+  };
+
+  // Mock updateProxySettings
+  const updateProxySettingsMock = vi.spyOn(podmanConfiguration, 'updateProxySettings');
+
+  // Simultaneously call the function twice
+  const call1 = podmanConfiguration.doUpdateProxySettings(undefined);
+  const call2 = podmanConfiguration.doUpdateProxySettings(proxySettings);
+
+  await Promise.all([call1, call2]);
```
Comment (feloy) [inline extensions/podman/packages/extension/src/podman-configuration.spec.ts]: The test does not cover that the calls are done one after the other (if you remove the use of the mutex in `doUpdateProxySettings`, the test still passes).

I would expect this instead:

```
  await call1;
  expect(updateProxySettingsMock).toHaveBeenCalledTimes(1);

  expect(updateProxySettingsMock.mock.calls[0][0]).toBe(undefined);

  await call2;
  expect(updateProxySettingsMock).toHaveBeenCalledTimes(2);
  expect(updateProxySettingsMock.mock.calls[1][0]).toBe(proxySettings);

```

**Review by feloy — APPROVED** [review]

File: extensions/podman/packages/extension/src/podman-configuration.ts [hunk 9]
```diff
@@ -105,6 +107,15 @@ export class PodmanConfiguration {
     }
   }
 
+  async doUpdateProxySettings(proxy: undefined | ProxySettings): Promise<void> {
```
Comment (benoitf) [inline extensions/podman/packages/extension/src/podman-configuration.ts:110]: issue: to me it looks like the opposite on how methods usually work

internal methods call updateProxySettings and then it's the method updateProxySettings that call doUpdateProxySettings

Comment (benoitf) [reply extensions/podman/packages/extension/src/podman-configuration.ts:110]: here, all existing calls were replaced from updateProxySettings to doUpdateProxySettings while they should not have been changed

Comment (gastoner) [reply extensions/podman/packages/extension/src/podman-configuration.ts:110]: Should I create an additional PR to change `updateProxySettings` to `doUpdateProxySettings` and vice versa?

Comment (benoitf) [reply extensions/podman/packages/extension/src/podman-configuration.ts:110]: It would be awesome 😎

Comment (gastoner) [reply extensions/podman/packages/extension/src/podman-configuration.ts:110]: Created https://github.com/podman-desktop/podman-desktop/pull/11081
