### PR TITLE
fix: remove failing check from container list table sorting

### LINKED ISSUE #8124: Test failing in container sorting
### Bug description

PR #8086 seems to have introduced a build failure, I have seen multiple unrelated builds fail with the following:

⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/lib/container/ContainerList.spec.ts > Sort containers based on selected parameter
AssertionError: expected 4 to be 2 // Object.is equality

- Expected
+ Received

- 2
+ 4

 ❯ src/lib/container/ContainerList.spec.ts:853:58
    851|   await fireEvent.click(age);

    852| 
Error: AssertionError: expected 4 to be 2 // Object.is equality

- Expected
+ Received

- 2
+ 4

 ❯ src/lib/container/ContainerList.spec.ts:853:58

    853|   expect(container1.compareDocumentPosition(container2)).toBe(2);
       |                                                          ^
    854| });
    855| 

### Operating system

macOS 14.5

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoniaSandler**
Signed-off-by: Sonia Sandler <ssandler@redhat.com>

### What does this PR do?

Removes the failing check in the container list table sorting test

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/8124

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/container/ContainerList.svelte [hunk 1]
```diff
@@ -341,8 +341,8 @@ let ageColumn = new TableColumn<ContainerInfoUI | ContainerGroupInfoUI, Date | u
     return undefined;
   },
   comparator: (a, b) => {
-    const aTime = containerUtils.isContainerInfoUI(a) ? (moment().diff(containerUtils.getUpDate(a)) ?? 0) : 0;
-    const bTime = containerUtils.isContainerInfoUI(b) ? (moment().diff(containerUtils.getUpDate(b)) ?? 0) : 0;
+    const aTime = containerUtils.isContainerInfoUI(a) && a.state === 'RUNNING' ? (moment().diff(a.startedAt) ?? 0) : 0;
```
Comment (jeffmaury) [inline packages/renderer/src/lib/container/ContainerList.svelte:344]: Why only RUNNING. A stopped container may have an age as well ?

File: packages/renderer/src/lib/container/ContainerList.spec.ts [hunk 2]
```diff
@@ -846,11 +846,6 @@ test('Sort containers based on selected parameter', async () => {
   await fireEvent.click(image);
 
   expect(container2.compareDocumentPosition(container1)).toBe(2);
-
```
Comment (jeffmaury) [inline packages/renderer/src/lib/container/ContainerList.spec.ts:849]: This removal seems suspect to me

Comment (SoniaSandler) [reply packages/renderer/src/lib/container/ContainerList.spec.ts:849]: @jeffmaury this is the part that probably have caused issues with others' builds like @deboer-tim mentioned, so I'm removing it to see if it helps

File: packages/renderer/src/lib/container/ContainerList.svelte (hunk 1 above)
Comment (SoniaSandler) [reply packages/renderer/src/lib/container/ContainerList.svelte:344]: @jeffmaury only the age of running containers is displayed in the containers list table. Right now, the table is sorted based on the displayed age, but I can change it to be sorted based on also the unseen age if that is preferable.

File: packages/renderer/src/lib/container/ContainerList.spec.ts (hunk 2 above)
Comment (jeffmaury) [reply packages/renderer/src/lib/container/ContainerList.spec.ts:849]: OK accepting because all others PRs are failing but we should understand the cause and create a follow up PR

File: packages/renderer/src/lib/container/ContainerList.svelte (hunk 1 above)
Comment (jeffmaury) [reply packages/renderer/src/lib/container/ContainerList.svelte:344]: That needs to be discussed but not on this PR

**Review by jeffmaury — APPROVED** [review]

File: packages/renderer/src/lib/container/ContainerList.svelte (hunk 1 above)
Comment (SoniaSandler) [reply packages/renderer/src/lib/container/ContainerList.svelte:344]: @jeffmaury remove the running part for this PR?

Comment (jeffmaury) [reply packages/renderer/src/lib/container/ContainerList.svelte:344]: No keep it as I'm discussing why age is not displayed for stopped containers but that's another PR
