### PR TITLE
fix(extensions/podman): avoid infinite loop when deactivating extension

### LINKED ISSUE #13149: Fix the podman extension monitoring loop to avoid infinite loop when deactivated
### Bug description

Fix the podman extension monitoring loop to avoid infinite loop when deactivated

### Operating system

all

### Installation Method

None

### Version

1.19.2

### Steps to reproduce

Exit the loop when deactivated

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

It breaks the loop when deactivating the podman extension to avoid infinite loop. 

Like in docker extension:

Screenshot 2025-07-10 at 17 46 26

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/13149

### How to test this PR?

I added a test and check that it was in error with the infinite loop if reverting the code of this PR.
- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — COMMENTED** [review]
unit test?

**Comment by simonrey1** [comment]
> unit test?

It is done in the next sub issue https://github.com/podman-desktop/podman-desktop/issues/13147

https://github.com/podman-desktop/podman-desktop/pull/13172/files#diff-b260000c81f05bbed928d650b5b138a2361bbbdaeffce0bcb41c65a990763c03R3488

Edit: Sorry, the UT was related to the doMonitorProvider function and not monitorProvider.

**Comment by axel7083** [comment]
> It is done in the next sub issue https://github.com/podman-desktop/podman-desktop/issues/13147

I would say, when changing something, you can include the unit tests with it, I would prefer to see the change and the corresponding test at the same time, than in separate PR

If you want to test the full function, this does not depends on the change introduced in this PR, so you may do that either before or after, but here as you fix something, you should have a regression test covering the specific change you made :+1:

**Comment by simonrey1** [comment]
> > It is done in the next sub issue #13147
> 
> I would say, when changing something, you can include the unit tests with it, I would prefer to see the change and the corresponding test at the same time, than in separate PR
> 
> If you want to test the full function, this does not depends on the change introduced in this PR, so you may do that either before or after, but here as you fix something, you should have a regression test covering the specific change you made 👍

Sorry, the UT was related to the doMonitorProvider function and not monitorProvider.

I don't really know how to test this function because of the 8s sleep.

It was left untested in the past.

**Comment by axel7083** [comment]
> I don't really know how to test this function because of the 8s sleep.
> 
> It was left untested in the past.

You should look at https://vitest.dev/guide/mocking.html#timers to better understand how to cover things with setTimeout

**Comment by axel7083** [comment]
Weirdly enough, I can't see any files changes in the GitHub files tab

File: extensions/podman/packages/extension/src/extension.ts [hunk 1]
```diff
@@ -2317,3 +2317,7 @@ export function updateWSLHyperVEnabledContextValue(value: boolean): void {
     extensionApi.context.setValue(WSL_HYPERV_ENABLED_KEY, value);
   }
 }
+
+export function setStopLoop(value: boolean): void {
+  stopLoop = value;
```
Comment (axel7083) [inline extensions/podman/packages/extension/src/extension.ts]: maybe the stopLoop should be reset in deactivate method

I am not a big fan of exposing a method for test purpose only :/

**Review by axel7083 — COMMENTED** [review]
https://github.com/podman-desktop/podman-desktop/pull/13153/files#r2215571950

File: extensions/podman/packages/extension/src/extension.ts (hunk 1 above)
Comment (simonrey1) [reply extensions/podman/packages/extension/src/extension.ts]: I understand but I don't want to change the implementation of deactivate for test purpose

Comment (simonrey1) [reply extensions/podman/packages/extension/src/extension.ts]: Oops sorry I thought adding stop loop in deactivate.

You meant, calling deactivate from the test, I can do it!

Comment (axel7083) [reply extensions/podman/packages/extension/src/extension.ts]: When we deactivate an extension we want to dispose its resources, and stop its activity, when calling deactivate I expect the stopLoop to be true, and when reactivating I expect it to be set to false

Comment (simonrey1) [reply extensions/podman/packages/extension/src/extension.ts]: Adding stopLoop = false in activate to make this change possible
https://github.com/podman-desktop/podman-desktop/pull/13275

File: extensions/podman/packages/extension/src/extension.spec.ts [hunk 2]
```diff
@@ -385,6 +384,7 @@ afterEach(async () => {
   console.error = originalConsoleError;
   await extension.deactivate();
   vi.useRealTimers();
+  vi.resetAllMocks();
```
Comment (axel7083) [inline extensions/podman/packages/extension/src/extension.spec.ts]: We usually reset all mocks at the beginning of the beforeEach

File: extensions/podman/packages/extension/src/extension.spec.ts [hunk 3]
```diff
@@ -3601,3 +3552,44 @@ describe('Check notify podman setup', () => {
...
+    expect(mockDoMonitorProvider).toHaveBeenCalledTimes(3);
+
+    await extension.deactivate();
+
+    await vi.runAllTimersAsync();
+    expect(mockDoMonitorProvider).toHaveBeenCalledTimes(3);
+  });
+});
+
+function getContextMock() {
```
Comment (gastoner) [inline extensions/podman/packages/extension/src/extension.spec.ts:3585]: I feel like help/setup functions should be on top, so we know what it is doing

**Review by gastoner — APPROVED** [review]
Codewise LGTM

File: extensions/podman/packages/extension/src/extension.spec.ts (hunk 3 above)
Comment (simonrey1) [reply extensions/podman/packages/extension/src/extension.spec.ts:3585]: I think this test file is too long to remember what was at the top, but I will take it into consideration when splitting it thanks
