### PR TITLE
fix: pass the copy of object to avoid modifying an original one

### LINKED ISSUE #290: Registry editing issues
### Bug description

I hit a number of problems trying to edit registries:

- I tried to pull an image before I realized I didn't have the registry added, so I clicked the Login to a Registry button. The first time in (can't reproduce) I couldn't click on the fields - i.e. the cursor wouldn't move when I clicked, and I had to tab between fields.
- I tried to edit a URL and that failed (separate bug was already open).
- In frustration I clicked on the username and added a few characters to see if it was editable. It was, so I clicked X to cancel. The changes were not shown in the Registries view (good).
- When I reopened the dialog, the changes were still there (bad).
- I closed the dialog again and the changes were not there (good), but when I switched to another Preferences page and back they were shown (bad).
- I opened the dialog, made a change, and clicked Update registry. The changes were lost and didn't appear in the Preferences page or when reopening the dialog (bad).

IMHO X should act like a cancel button, and changes should apply and be immediately visible when using Update Registry.

### Operating system

macOS 12.4 M1

### Version

0.0.5

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
Do not modify the original registry object instance, when the dialog opens. This prevents the original object instance from the modification, when user closes the dialog without create or update action.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

part of #290 

### How to test this PR?

Open dialog to modify the existed registry, type any values and close the dialog, then open the dialog again. Values should not be modified.

### CODE REVIEW

File: packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte [hunk 1]
```diff
@@ -107,6 +107,6 @@ function toggleRegistryModal(): void {
     <PreferencesRegistriesEditCreateRegistryModal
       toggleCallback="{toggleRegistryModal}"
       mode="{preferencesMode}"
-      registry="{selectedRegistry}" />
+      registry="{{source: selectedRegistry?.source, serverUrl: selectedRegistry?.serverUrl, username: selectedRegistry?.username, secret: selectedRegistry?.secret}}" />
```
Comment (benoitf) [inline packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte]: will it work to use `{...selectedRegistry}` ?

Comment (vzhukovs) [reply packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte]: need to check

Comment (benoitf) [reply packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte]: approving but better if we can use spread syntax as we don't need to enumerate all fields

**Review by benoitf — APPROVED** [review]
if we can use spread operator would be better

File: packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte (hunk 1 above)
Comment (vzhukovs) [reply packages/renderer/src/lib/preferences/PreferencesRegistriesRendering.svelte]: yep, that works, updated the PR
