### PR TITLE
fix: remove check on podman machine sockets directory when activating podman (#4080)

### LINKED ISSUE #4080: Podman Onboarding on Mac not working as command is not registered
### Bug description

When the podman extension activates for the first time on Mac it never registers the onboarding commands because it returns here
https://github.com/containers/podman-desktop/blob/ca0642bb7f996ead88c2721c376ef35899328cf0/extensions/podman/src/extension.ts#L882

resulting in a broken onboarding workflow

### Operating system

ventura 13.4

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

It just unifies the `isWindows` and `isMac` branches when it starts checking the machines at the extension activation as they do the same thing.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

it resolves #4080 

### How to test this PR?

1. start podman desktop, it should work as before

### CODE REVIEW

File: extensions/podman/src/extension.ts [hunk 1]
```diff
@@ -879,15 +879,7 @@ export async function activate(extensionContext: extensionApi.ExtensionContext):
     });
   }
 
-  // no podman for now, skip
-  if (isMac()) {
-    if (!fs.existsSync(podmanMachineSocketsDirectory)) {
-      return;
-    }
```
Comment (benoitf) [inline extensions/podman/src/extension.ts:886]: I think this check was added b/c there was an issue monitoring a non-existing directory on macOS so probably it'll fail ?

Comment (lstocchi) [reply extensions/podman/src/extension.ts:886]: So i think it must be moved somewhere else because in this way it returns and it does not start the monitorMachines at all.
If you just install podman without reactivating the extension it will never monitor the machines

Comment (benoitf) [reply extensions/podman/src/extension.ts:886]: yes, I mean I understand your usecase but probably yes it needs to be moved vs being deleted 👍

Comment (lstocchi) [reply extensions/podman/src/extension.ts:886]: I tried on my Mac and it still works either if i delete the folder at runtime or if i remove it just before starting Desktop.

By looking the code i do not see where it could fail. All the functions executed after this point should not break by the missing folder. Both the monitorMachine/Provider have a silent catch which would prevent them to fail, then we just start the registry and proxy setup.

By going backwards i saw that the code was changed here https://github.com/containers/podman-desktop/commit/653b82bf4164fa5470b5caf6d3047034d911f59d#diff-c885162dd627b7cd812c83544b19b9b166179fec79ddbc13273fede7c2566791L238 
before it was watching that folder. Maybe this is what you recalled? In this case maybe it's not necessary anymore. 

Otherwise i need some guidance because i have no idea where i should move this check.

Comment (benoitf) [reply extensions/podman/src/extension.ts:886]: I was remembering https://github.com/containers/podman-desktop/pull/188/files

so maybe it works with a non existing folder but not on a non-existing file

Comment (benoitf) [reply extensions/podman/src/extension.ts:886]: also it seems it was Linux so we should be good on macOS then you tested it

**Review by benoitf — APPROVED** [review]
forgot to approve
