### PR TITLE
fix(renderer): update SettingsPage and dependent components to Svelte 5

### LINKED ISSUE #13397: Update SettingsPage and dependent components to Svelte 5
### Bug description

Update SettingsPage and dependent components to Svelte 5

### Operating system

all

### Installation Method

None

### Version

1.19.2

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

fix(renderer): update SettingsPage and dependent components to Svelte 5

### What issues does this PR fix or reference?

Fixes #13397 

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte [hunk 1]
```diff
@@ -692,7 +693,8 @@ function handleError(errorMessage: string): void {
               connectionStatus={containerConnectionStatus.get(getProviderConnectionName(provider, vmConnection))}
               updateConnectionStatus={updateContainerStatus}
               addConnectionToRestartingQueue={addConnectionToRestartingQueue}>
-              <span slot="advanced-actions" class:hidden={providers.length === 0}>
+              <!-- @migration-task: migrate this slot by hand, `advanced-actions` is an invalid identifier -->
```
Comment (eqqe) [inline packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte:696]: TODO

File: packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte [hunk 2]
```diff
@@ -591,7 +591,8 @@ function handleError(errorMessage: string): void {
                 connectionStatus={containerConnectionStatus.get(getProviderConnectionName(provider, container))}
                 updateConnectionStatus={updateContainerStatus}
                 addConnectionToRestartingQueue={addConnectionToRestartingQueue}>
-                <span slot="advanced-actions" class:hidden={providers.length === 0}>
+                <!-- @migration-task: migrate this slot by hand, `advanced-actions` is an invalid identifier -->
```
Comment (eqqe) [inline packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte:594]: TODO

File: packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte [hunk 3]
```diff
@@ -520,7 +520,7 @@
                   <button
                     aria-label="{provider.name} details"
                     type="button"
-                    on:click={(): void =>
+                    onclick={(): void =>
```
[the remark this answers is not in the document]
Comment (simonrey1) [reply packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte:523]: Good catch, using the new onclick on <Button> components now

a07c6080a7516df6101b4200a211f3083152c484

**Review by axel7083 — APPROVED** [review]
Great works, pretty complex components !

File: packages/renderer/src/lib/preferences/PreferencesRegistriesEditing.svelte [hunk 4]
```diff
@@ -8,38 +8,42 @@ import PasswordInput from '/@/lib/ui/PasswordInput.svelte';
...
+let showPasswordForServerUrls = $state<string[]>([]);
 
-// show or hide new registry form
-export let showNewRegistryForm = false;
+interface Props {
+  // show or hide new registry form
+  showNewRegistryForm?: boolean;
+}
+
+let { showNewRegistryForm = $bindable(false) }: Props = $props();
```
Comment (SoniaSandler) [inline packages/renderer/src/lib/preferences/PreferencesRegistriesEditing.svelte]: Why is `showNewRegistryForm` bindable?

File: packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte [hunk 5]
```diff
@@ -392,28 +334,86 @@ function hasAnyConfiguration(provider: ProviderInfo): boolean {
...
-let providerElementMap: Record<string, HTMLElement> = {};
-
-$: if (focus && providerElementMap[focus]) {
-  providerElementMap[focus].scrollIntoView({ behavior: 'auto', block: 'start' });
+interface Props {
+  properties?: IConfigurationPropertyRecordedSchema[];
+  focus: string | undefined;
 }
 
+let { properties = $bindable([]), focus }: Props = $props();
```
Comment (SoniaSandler) [inline packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte]: Why is `properties` bindable?

**Review by SoniaSandler — APPROVED** [review]
LGTM, just added a couple of non-blocking questions

File: packages/renderer/src/lib/preferences/PreferencesRegistriesEditing.svelte (hunk 4 above)
Comment (simonrey1) [reply packages/renderer/src/lib/preferences/PreferencesRegistriesEditing.svelte]: It was made `bindable` by the Svelte migration script. In the other migrations, I sometimes noticed that it was not useful, so I will take a look on these ones.
