### PR TITLE
fix: use docker.io registry credentials for index.docker.io images

### LINKED ISSUE #8293: Unable to install an extension from a Docker private repository
### Bug description

I'm trying to install an extension from an image stored in a private Docker repository, but I get an error `Error while analyzing image: Error: Unable to get access`

### Operating system

mac

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

I tried with the image names:
- `feloy/test:latest`
- `docker.io/feloy/test:latest`

### Relevant log output

_No response_

### Additional context

- I can install the same image from a private Quay.io repository

- Login/pwd have been added for registry `docker.io`.

- It works if I also add login/pwd for registry `index.docker.io`

### PR DESCRIPTION
**Pull request by feloy**
### What does this PR do?

Use docker.io registry credentials for index.docker.io images

### What issues does this PR fix or reference?

Fixes #8293 

### How to test this PR?

Try to install an extension from a private Docker repository (you should have added credentials for the Docker registry)

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/image-registry.ts [hunk 1]
```diff
@@ -921,20 +924,24 @@ export class ImageRegistry {
...
-      options.registry = 'https://index.docker.io';
-    }
-    if (options.registry === 'docker.io') {
-      options.registry = 'index.docker.io';
-    }
-    if (!options.registry.startsWith('http')) {
-      options.registry = 'https://' + options.registry;
+    try {
+      if (!options.registry) {
+        options.registry = 'https://index.docker.io';
```
Comment (axel7083) [inline packages/main/src/plugin/image-registry.ts]: (Future PR) Should we have this in a configuration value, like `default registry` ?

File: packages/renderer/src/lib/ui/Typeahead.svelte [hunk 2]
```diff
@@ -0,0 +1,233 @@
+<script lang="ts">
```
Comment (axel7083) [inline packages/renderer/src/lib/ui/Typeahead.svelte]: Does this PR is suppose to include the Typeahead component ? Giving the title I thought it would be backend only

**Review by benoitf — COMMENTED** [review]
for separation of concern, it seems this PR is achieving way more stuff than expected

I'm expecting only the 

```ts
 let matchingUrl = registryServer;
    if (matchingUrl === 'index.docker.io') {
      matchingUrl = 'docker.io';
    }
```
change + the unit tests

but here it's also changing the return method like throwing error instead of empty result, etc, new UI components, etc that should be in separate PRs

File: packages/renderer/src/lib/ui/Typeahead.svelte (hunk 2 above)
Comment (feloy) [reply packages/renderer/src/lib/ui/Typeahead.svelte]: I created the branch based on the Typeahead's branch, to be able to test the typeahead of private images with the fix. I'll rebase it to main.

Only the latest commit is part of this PR

**Comment by feloy** [comment]
> for separation of concern, it seems this PR is achieving way more stuff than expected
> 
> I'm expecting only the
> 
> ```ts
>  let matchingUrl = registryServer;
>     if (matchingUrl === 'index.docker.io') {
>       matchingUrl = 'docker.io';
>     }
> ```
> 
> change + the unit tests
> 
> but here it's also changing the return method like throwing error instead of empty result, etc, new UI components, etc that should be in separate PRs

https://github.com/containers/podman-desktop/pull/8892#discussion_r1760945546

**Review by axel7083 — APPROVED** [review]
LGTM Codewise :rocket:

**Review by benoitf — APPROVED** [review]
