### PR TITLE
fix: make sure logo is updated through reactive mode

### LINKED ISSUE #440: Logo of the provider may not be the correct one
### Bug description

With a slow CPU, the provider logo may not be the good one

image

Refreshing the window fixes the issue but it's not user friendly

### Operating system

macOS

### Version

0.0.6

### Steps to reproduce

Use a 'slow computer'

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Ensure logo is updated with reactive changes

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/440

### How to test this PR?

Check logos are the expected one

Change-Id: I5cfcb008c15c9459c207efb93db2159323835df8
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

File: packages/renderer/src/lib/welcome/ProviderLogo.svelte [hunk 1]
```diff
@@ -1,22 +1,21 @@
 <script lang="ts">
-import { onMount } from 'svelte';
-
 import type { ProviderInfo } from '../../../../main/src/plugin/api/provider-info';
 
 export let provider: ProviderInfo;
 
-let logo;
+//$: logo = provider.images.logo ? (typeof provider.images.logo === 'string' ? provider.images.logo : provider.images.logo.d): undefined
```
Comment (vzhukovs) [inline packages/renderer/src/lib/welcome/ProviderLogo.svelte]: Do we need to keep the commented line?

**Review by vzhukovs — APPROVED** [review]

File: packages/renderer/src/lib/welcome/ProviderLogo.svelte (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/lib/welcome/ProviderLogo.svelte]: no :-)

Comment (benoitf) [reply packages/renderer/src/lib/welcome/ProviderLogo.svelte]: fixed
