### PR TITLE
fix: Dashboard doesn’t store state of buttons

### LINKED ISSUE #2403: Dashboard doesn’t store state of buttons
### Bug description

When any button appears on dashboard and it launch some UI changes or process(like install or initialise) that state doesn’t stored. For example, if I click on `Initialize` button and then open `Settings` page and go back to dashboard, it will show me same `Initialize` button, like I never click on it:

https://github.com/containers/podman-desktop/assets/929743/ba98e663-ab8a-4184-9eb5-9b75796fccf8

Similar issue https://github.com/crc-org/crc-extension/issues/73 

### Operating system

 macOS 13.2.1 Intel

### Version

next (development version)

### Steps to reproduce

Delete podman vm, launch podman-desktop, click on `Initialize and start` button on podman dashboard widget, then click on `Settings` button, and return back to dashboard.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2403

### What does this PR do?

Keep initialization state if navigation is done

### Screenshot/screencast of this PR

init

### What issues does this PR fix or reference?

Fixes #2403

### How to test this PR?

1. Removed all Podman machine
2. Go to the dashboard
3. Click the Initialize or Initialize and Run button
4. Navigate to Settings
5. Go back to Dashboard

### CODE REVIEW

File: packages/renderer/src/lib/dashboard/DashboardPage.svelte [hunk 1]
```diff
@@ -15,7 +15,9 @@ import FeaturedExtensions from '/@/lib/featured/FeaturedExtensions.svelte';
 const providerInitMode = new Map<string, InitializationMode>();
 
 $: providersNotInstalled = $providerInfos.filter(provider => provider.status === 'not-installed');
-$: providersInstalled = $providerInfos.filter(provider => provider.status === 'installed');
+$: providersInstalled = $providerInfos.filter(
+  provider => provider.status === 'installed' || provider.status === 'configuring',
+);
```
Comment (benoitf) [inline packages/renderer/src/lib/dashboard/DashboardPage.svelte]: it looks strange that installed providers are also the one being in configuring state
maybe they need their own variables ? like providersConfiguring ?

**Review by benoitf — COMMENTED** [review]
it looks like a hack/patch for now

ProviderInstalled.svelte is checking for a 'configuring' state , providerInstalled is assuming it's configuring state

I suppose it requires its own Component / variables

**Review by benoitf — APPROVED** [review]
