### PR TITLE
fix: internal hrefs in link component

### LINKED ISSUE #3565: Links don't work for local hrefs (e.g. back-links)
### Bug description

Backlinks (history) on the Details and Form pages do not work. Nothing happens in the UI when you click on them and there is an error in the log. All other use of Links (e.g. external links on Dashboard and Deploy to Pod page) work fine.

I made the Link component and replaced the <a href=... /> on these pages, and successfully tested manually. Then extended Link to work in two more cases for other pages (external links and on:click), not realizing I had broken the first. Somehow thought I had retested, and even managed to write tests to confirm the new (broken) behaviour.

### Operating system

macOS 13.5

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Just open a page like Container Details or Image Details, and try to click the back link to Containers or Images. The close button still works.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

As per bug #3565, I managed to break the Link component so that it does not work for internal hrefs. This changes the Link to support three options:
 - internalRef uses tinro router.goto() to navigate to another page.
 - externalRef - uses window.openExternal() to open in external browser.
 - on:click - used for more complicated/programmatic callbacks that need to trigger a function.

Added test for the first option that wasn't working before, and updates Details and Form page tests to check the correct case.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #3565.

### How to test this PR?

Open a page like Container Details or Image Details, and try to click the back link to Containers or Images.

### CODE REVIEW

File: packages/renderer/src/lib/ui/Link.svelte [hunk 1]
```diff
@@ -19,7 +20,11 @@ onMount(() => {
 
 function click() {
   if (href) {
-    window.openExternal(href);
+    if (href.startsWith('/')) {
+      router.goto(href);
+    } else {
+      window.openExternal(href);
+    }
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/Link.svelte]: I think here we may have a problem, a relative link could be `../foo` or `./bar`

so I don't know if we should proceed like that or we have 'internal-link' vs 'external-link' so when referencing a link we do know what we want to do/achieve

or `internalRef/externalRef` vs `href

File: packages/renderer/src/lib/ui/Link.spec.ts [hunk 2]
```diff
@@ -59,6 +69,21 @@ test('Check href action', async () => {
...
+  render(Link, { href: '/Pods' });
+
+  // check href link
+  const link = screen.getByRole('link');
+  expect(link).toBeInTheDocument();
+
+  fireEvent.click(link);
+
+  expect(router.goto).toBeCalledTimes(1);
+  expect(urlMock).not.toHaveBeenCalled();
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/Link.spec.ts]: I don't see how urlMock could have been called anyway as it's not referenced ?

Comment (deboer-tim) [reply packages/renderer/src/lib/ui/Link.spec.ts]: Good catch, added the missing `(window as any).openExternal = urlMock;` in new commit.

File: packages/renderer/src/lib/ui/Link.svelte (hunk 1 above)
Comment (deboer-tim) [reply packages/renderer/src/lib/ui/Link.svelte]: I'm not sure where we use any relative links like that, but what do you think about switching it around (see new commit)? It checks for `startsWith('http')`, which I think should be a safer test.

Comment (benoitf) [reply packages/renderer/src/lib/ui/Link.svelte]: I don't think we need to be smart here.

I'm pretty sure we will have links to `podman-desktop://` etc

so I would give the responsibility to the author using `<Link>` component so it's when using the component that we tell open it externally or open it locally

Else we'll always have bugs around this part

Comment (benoitf) [reply packages/renderer/src/lib/ui/Link.svelte]: 1. onClick
1. internalRef
1. externalRef

then consumer choose how he wants to use that component

File: packages/renderer/src/lib/ui/Link.svelte [hunk 3]
```diff
@@ -19,7 +20,11 @@ onMount(() => {
 
 function click() {
   if (href) {
-    window.openExternal(href);
+    if (href.startsWith('http')) {
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/Link.svelte]: let say the page is relative link `http/my-page` it won't work neither

File: packages/renderer/src/lib/ui/Link.svelte (hunk 1 above)
Comment (deboer-tim) [reply packages/renderer/src/lib/ui/Link.svelte]: Ok, component updated to use internalRef/externalRef props in new commit.

Comment (benoitf) [reply packages/renderer/src/lib/ui/Link.svelte]: thanks, we are less smart but more robust

**Review by benoitf — APPROVED** [review]
tested and it's working 🚀
