### PR TITLE
fix: Kind clusters not cleaned up when stopping podman machine

### LINKED ISSUE #2143: Kind clusters not cleaned up when stopping podman machine
### Bug description

When I stop the podman machine that's hosting my Kind clusters, they don't get cleaned up. I thought I saw several left one time, but when testing repeatedly there seems to always be one Kind cluster remaining, and it's the one my Kube context points to.

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

Create a couple Kind clusters on podman, then stop the machine. (my Kind clusters were all stopped first, I assume that shouldn't make a difference) I always have one Kind cluster still listed; seems to be whatever is on the Kube context.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2143

### What does this PR do?

Reset/initialize container connections 

### Screenshot/screencast of this PR

restart

### What issues does this PR fix or reference?

Fixes #2143 

### How to test this PR?

1. Create a kind cluster
2. Stop the podman machine -> Kind cluster should disappear
3. Restart the podman machine -> Kind cluster should reappear

### CODE REVIEW

File: packages/main/src/plugin/container-registry.ts [hunk 1]
```diff
@@ -170,20 +172,11 @@ export class ContainerProviderRegistry {
...
-    }
-
-    // track the status of the provider
-    const timer = setInterval(async () => {
-      const newStatus = containerProviderConnection.status();
-      if (newStatus !== previousStatus) {
+    providerRegistry.onBeforeDidUpdateContainerConnection(event => {
+      if (event.providerId === provider.id && event.connection.name === containerProviderConnection.name) {
+        const newStatus = event.status;
+        console.log(` New status ${newStatus}`);
```
Comment (benoitf) [inline packages/main/src/plugin/container-registry.ts]:
```suggestion

```

not sure to keep it ?

**Review by benoitf — APPROVED** [review]
LGTM

**Comment by cdrage** [comment]
LGTM after changes from removing log (tested this on Windows & mac M1)

**Review by cdrage — APPROVED** [review]
