### PR TITLE
fix(feedback): showing modal dialog when closing feedback form

### LINKED ISSUE #10837: I can close a feedback form without a confirmation dialog (notifying user about losing info writen into form) sometimes
### Bug description

Sometimes (not 100 sure about the situation) I am encountering issues with a dialogs (feedback form). Feedback form should not let me to close it If I typed in some text or provider some other information, but if I just open a feedback, type mouse into input text field, type down some text and then close or click outside the dialog, I wont get confirmation dialog that I will lose the written text.

https://github.com/user-attachments/assets/92b8a1f6-d087-4882-abad-1dc8be16db6e

### Operating system

Linux, Windows 10

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Open feedback form
2. click into input text field
3. type some text
4. click outside dialog
5. Assert: confirmation dialog apeears 
Actual result: sometimes the dialog is not opened, if I click on some other item in dialog, like choosing a smiley, it starts to work as expected. 

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Fixes showing modal when closing form with some content

### What issues does this PR fix or reference?
Closes #10837 

### How to test this PR?
Try to close dialog when having some content in it

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/feedback/SendFeedback.svelte [hunk 1]
```diff
@@ -50,7 +50,7 @@ async function hideModal(confirm = true): Promise<void> {
 }
 
 function handleUpdate(e: boolean): void {
-  hasContent = !hasContent && e;
+  if (e) hasContent = true;
```
Comment (SoniaSandler) [inline packages/renderer/src/lib/feedback/SendFeedback.svelte]: question: wouldn't it be better to just do `hasContent = e`? Right now, if I add some content and delete it all, it still shows the popup dialog despite not having any content in the feedback form.

Comment (gastoner) [reply packages/renderer/src/lib/feedback/SendFeedback.svelte]: Thank you, didn't notice this. Updated!

**Review by axel7083 — APPROVED** [review]
Tested and works fine on my side LGTM

**Review by SoniaSandler — APPROVED** [review]
LGTM
