### PR TITLE
fix: random CRC status change

### LINKED ISSUE #1387: CRC extension shows running state and 'randomly' changes between stopped and started
We have originally observed the same state in the CRC tray, but when the connection might fail, or the state errors, the default of 'stopped' is shown.

https://github.com/containers/podman-desktop/blob/30ea9a593ee2af9b7117f59d943ed3416fe01f60/extensions/crc/src/extension.ts#L66

This should have a grace period or clearer transition when 'unknown'.

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
It change a bit of how fetching CRC status, add better error handling.
Also it use status object to get preset, instead of calling `crc` CLI.

Basically status is getting close to existing tray-app in CRC https://github.com/crc-org/tray-electron

### Screenshot/screencast of this PR
n/a

### What issues does this PR fix or reference?
Fix: https://github.com/containers/podman-desktop/issues/1387

### How to test this PR?
It very hard to test, as issue appears of some specific windows environment( with VPN setup etc.), at least, this PR shouldn’t break any thing.

### CODE REVIEW

File: extensions/crc/src/extension.ts [hunk 1]
```diff
@@ -232,39 +233,25 @@ function convertToProviderStatus(crcStatus: string): extensionApi.ProviderStatus
...
-    process.on('error', err => reject(err));
-  });
+    try {
+      crcStatus = await commander.status();
+    } catch (e) {
+      console.error('CRC Status tick: ' + e);
+      const unknownStatus: Status = { CrcStatus: 'Stopped', Preset: 'Unknown' };
+      crcStatus = unknownStatus;
+    }
+  }, 1000);
```
Comment (cdrage) [inline extensions/crc/src/extension.ts:244]: Should we have this back to `2000` or is `1000` better for detection?

File: extensions/crc/src/extension.ts [hunk 2]
```diff
@@ -232,39 +233,25 @@ function convertToProviderStatus(crcStatus: string): extensionApi.ProviderStatus
...
-    });
-
-    process.on('close', () => resolve(output.trim()));
-    process.on('error', err => reject(err));
-  });
+    try {
+      crcStatus = await commander.status();
+    } catch (e) {
+      console.error('CRC Status tick: ' + e);
+      const unknownStatus: Status = { CrcStatus: 'Stopped', Preset: 'Unknown' };
```
Comment (cdrage) [inline extensions/crc/src/extension.ts]: Could we put this in the top of the file and use it in the two places required?

File: extensions/crc/src/extension.ts [hunk 3]
```diff
@@ -66,8 +63,12 @@ export async function activate(extensionContext: extensionApi.ExtensionContext):
     crcStatus = await commander.status();
   } catch (err) {
     console.error('error in CRC extension', err);
+    crcStatus = { CrcStatus: 'Unknown', Preset: 'Unknown' };
```
Comment (cdrage) [inline extensions/crc/src/extension.ts]:
```suggestion
    crcStatus = unknownStatus
```

See other command about moving const top top of file

**Review by cdrage — CHANGES_REQUESTED** [review]
Much cleaner and thanks for the new changes! Just a few comments but those are minor.

File: extensions/crc/src/extension.ts (hunk 1 above)
Comment (evidolob) [reply extensions/crc/src/extension.ts:244]: I think it is better for state track

File: extensions/crc/src/extension.ts [hunk 4]
```diff
@@ -232,39 +235,25 @@ function convertToProviderStatus(crcStatus: string): extensionApi.ProviderStatus
...
-
-    process.on('close', () => resolve(output.trim()));
-    process.on('error', err => reject(err));
-  });
+    try {
+      crcStatus = await commander.status();
+    } catch (e) {
+      console.error('CRC Status tick: ' + e);
+      const unknownStatus: Status = defaultStatus;
+      crcStatus = unknownStatus;
```
Comment (benoitf) [inline extensions/crc/src/extension.ts]:
```suggestion
      crcStatus = defaultStatus;
```

**Review by benoitf — APPROVED** [review]

**Review by cdrage — APPROVED** [review]
LGTM!
