### PR TITLE
fix: disable `Create` button if properties audit returns errors

### LINKED ISSUE #9118: If `auditItems` function returns errror 'Create' button stays enabled on create resource page
### Bug description

An extension can provide auditItems function when setting up container connection factory. auditItems function can return records reportin problems with new container connection properties. The `Create` button meantime stays enabled and user can proceed with creating container connection.

Would we good to diable `Create` button in case when connection properties audit returns audit records with type `error`.

### Operating system

macOS M1 Sonoma 14.5

### Installation Method

None

### Version

1.11.1

### Steps to reproduce

If Kind cluster with the same name is created there should be an error on top of the new kind cluster form, but 'Create' button should still be available.

### Relevant log output

_No response_

### Additional context

Relates to #9096.

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

PR disables 'Create' button in new resource form if audit returned record with type 'error'.

### Screenshot / video of UI

https://github.com/user-attachments/assets/c82dcf6b-f317-4499-99c5-51459472137e

### What issues does this PR fix or reference?

Fix #9118

### How to test this PR?

Try to create kind cluster with the same name

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by dgolovin** [comment]
Test have not been inmplemented yet.

File: packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte [hunk 1]
```diff
@@ -223,6 +223,8 @@ async function handleValidComponent() {
       console.warn(String(err));
     }
   }
+  const auditErrors = connectionAuditResult?.records?.filter(record => record.type === 'error');
+  isValid = auditErrors !== undefined && auditErrors.length === 0;
```
Comment (benoitf) [inline packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte]: would it work using only `audit errors?.length === 0`

**Review by benoitf — APPROVED** [review]

**Comment by feloy** [comment]
I'm probably doing things wrong, I cannot find a way to test this.

For example, when I create a podman machine or a Kind cluster, I always get as result of `window.auditConnectionParameters` an empty array of `records`

**Comment by dgolovin** [comment]
> I'm probably doing things wrong, I cannot find a way to test this.
> 
> For example, when I create a podman machine or a Kind cluster, I always get as result of `window.auditConnectionParameters` an empty array of `records`

Actually, you partially right. There is no way to trigger 'error' on create Kind cluster page. You can trigger 'info' and 'warning' but, that would not disable Create/Update button.

There is no easy way to verify it now, because there is no audit implementation in main branch that would report error.

I'll update PR #9096 to use audit, so you can pull this PR, then pull #9096 with `--rebase` option and test it.

**Review by feloy — APPROVED** [review]
LGTM based on unit tests

**Comment by axel7083** [comment]
> Try to create kind cluster with the same name

Here are my existing kind clusters

image

But the `Create` button seems to still be active

image

After clicking on it I am getting the error (expected)

image

**Comment by dgolovin** [comment]
> > Try to create kind cluster with the same name
>
> But the `Create` button seems to still be active 
> 
> After clicking on it I am getting the error (expected)
> 

@axel7083 Sorry, it turned out there is no check for same name in Kind extension. I thought I saw it when I was looking for examples of audit implementations, but after @feloy comment above I checked again ad realized there is no audit for it. I opened follow up for it #9152.
