### PR TITLE
fix: Refactor Kubernetes client with respect to OpenShift and Microshift

### LINKED ISSUE #2260: Refactor Kubernetes client with respect to OpenShift and Microshift
### Bug description

The Kubernetes client is making the distinction for OpenShift in order to select:

- namespaces vs projects
- ingresses vs routes

The selection is based on the OpenShift console config but we should be based on API groups (which btw would allow validations of Kubernetes YAML).

So replace isOpenShift by isAPIGroupSupported and provide well know API Group OpenShiftRoute and OpenShiftProject

### Operating system

Win11 Pro

### Version

0.14.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2260

### What does this PR do?

Handle raw Kubernetes, OpenShift and Microshift clusters accordingly. On Microshift and OpenShift, deploy should create routes. On other clusters, ingresses should be used. On Microshift and raw Kubernetes, namespaces should be used and projects on OpenShift clusters.

I added support for the Restricted security profile which is required by Microshift and enabled it by default for simpler workflows on MicroShift. Let me know WDYT
Please also note that the link to the Kubernetes documentation won't work until #2230 is fixed

### Screenshot/screencast of this PR

microshift

### What issues does this PR fix or reference?

Fixes #2260

### How to test this PR?

Deploy a container to one of those clusters

### CODE REVIEW

File: packages/main/src/plugin/kubernetes-client.ts [hunk 1]
```diff
@@ -85,9 +86,7 @@ function toPodInfo(pod: V1Pod): PodInfo {
   };
 }
 
-const OPENSHIFT_CONSOLE_NAMESPACE = 'openshift-config-managed';
-
-const OPENSHIFT_CONSOLE_CONFIG_MAP = 'console-public';
+const PROJECT_API_GROUP = 'project.openshift.io';
```
Comment (benoitf) [inline packages/main/src/plugin/kubernetes-client.ts]: looks like it's more OPENSHIFT_PROJECT_API_GROUP

File: packages/main/src/plugin/kubernetes-client.ts [hunk 2]
```diff
@@ -240,8 +257,8 @@ export class KubernetesClient {
     let namespace;
 
     try {
-      const cm = await this.readNamespacedConfigMap(OPENSHIFT_CONSOLE_CONFIG_MAP, OPENSHIFT_CONSOLE_NAMESPACE);
-      if (cm) {
+      const projectGroupSupported = await this.isAPIGroupSupported(PROJECT_API_GROUP);
+      if (projectGroupSupported) {
```
Comment (benoitf) [inline packages/main/src/plugin/kubernetes-client.ts:261]: below maybe replace .listClusterCustomObject('project.openshift.io' by the name of the constant

File: packages/preload/src/index.ts [hunk 3]
```diff
@@ -1114,6 +1114,10 @@ function initExposure(): void {
     },
   );
 
+  contextBridge.exposeInMainWorld('kubernetesisAPIGroupSupported', async (group: string): Promise<boolean> => {
```
Comment (benoitf) [inline packages/preload/src/index.ts]: small typo
```suggestion
  contextBridge.exposeInMainWorld('kubernetesIsAPIGroupSupported', async (group: string): Promise<boolean> => {
```

File: packages/renderer/src/lib/pod/DeployPodToKube.spec.ts [hunk 4]
```diff
@@ -62,6 +63,9 @@ beforeEach(() => {
   Object.defineProperty(window, 'kubernetesCreateService', {
     value: kubernetesCreateServiceMock,
   });
+  Object.defineProperty(window, 'kubernetesisAPIGroupSupported', {
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/DeployPodToKube.spec.ts]:
```suggestion
  Object.defineProperty(window, 'kubernetesIsAPIGroupSupported', {
```

File: packages/renderer/src/lib/pod/DeployPodToKube.spec.ts [hunk 5]
```diff
@@ -35,6 +35,7 @@ const telemetryTrackMock = vi.fn();
 const kubernetesCreatePodMock = vi.fn();
 const kubernetesCreateIngressMock = vi.fn();
 const kubernetesCreateServiceMock = vi.fn();
+const kubernetesisAPIGroupSupported = vi.fn();
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/DeployPodToKube.spec.ts]:
```suggestion
const kubernetesIsAPIGroupSupported = vi.fn();
```

File: packages/renderer/src/lib/pod/DeployPodToKube.svelte [hunk 6]
```diff
@@ -22,6 +22,7 @@ let deployError = '';
 let deployWarning = '';
 let updatePodInterval: NodeJS.Timeout;
 let openshiftConsoleURL: string;
+let routeGroupSupported = false;
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/DeployPodToKube.svelte]:
```suggestion
let openshiftRouteGroupSupported = false;
```

probably says that it's openshift route ?

File: packages/renderer/src/lib/pod/DeployPodToKube.svelte [hunk 7]
```diff
@@ -62,6 +63,7 @@ onMount(async () => {
 
   // check if there is OpenShift and then grab openshift console URL
   try {
+    routeGroupSupported = await window.kubernetesisAPIGroupSupported('route.openshift.io');
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/DeployPodToKube.svelte]:
```suggestion
    routeGroupSupported = await window.kubernetesIsAPIGroupSupported('route.openshift.io');
```

**Review by benoitf — COMMENTED** [review]
looks better using this pattern 👍

File: packages/renderer/src/lib/pod/pod-utils.ts [hunk 8]
```diff
@@ -64,3 +65,36 @@ export class PodUtils {
     };
   }
 }
+
+// eslint-disable-next-line  @typescript-eslint/no-explicit-any
+export function ensureRestrictedSecurityContext(body: any) {
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/pod-utils.ts:70]: looks like this function requires a unit test ?

File: packages/renderer/src/lib/pod/DeployPodToKube.svelte [hunk 9]
```diff
@@ -361,8 +369,25 @@ function updateKubeResult() {
...
+          name="useRestricted"
+          id="useRestricted"
+          data-testid="useRestricted"
+          class=""
+          required />
+        <span class="text-gray-400 text-sm ml-1"
+          >Update Kubernetes manifest to respect the Pod security <a
+            href="https://kubernetes.io/docs/concepts/security/pod-security-standards#restricted">restricted profile</a
+          >.</span>
+      </div>
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/DeployPodToKube.svelte:387]: requires a unit test as well

**Review by lstocchi — APPROVED** [review]
Tested, works fine for me.

There was just one problem at the beginning. I was logged in my kind cluster, then i used the terminal to log in to sandbox and PD still was proposing me to create an ingress even if it was pointing correctly to the sandbox  cluster. But after it, it didn't repeat again 🤷‍♂️

**Review by benoitf — APPROVED** [review]
