### PR TITLE
fix: do not try to monitor machine when autostarting it

### LINKED ISSUE #10173: podman machine is loaded twice upon PD startup
### Bug description

It seems that podman machine data is loaded twice upon starting up PD, and as such will be shown in duplicate in the Settings -> Resources page, issue is a regression in the main branch.

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Have a podman machine available in podman cli.
2. Startup PD from main branch.
3. Go into Settings -> Resources page.
4. Notice that the podman machine resource box is duplicated.

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Avoid to check for machines during the 'autostart' as it could lead to two calls to 'podman machine list' in parallel leading to duplicate podman machines.

wrap the autoStart in a try/finally block to not check for machines during that time

### What issues does this PR fix or reference?

fixes https://github.com/podman-desktop/podman-desktop/issues/10173

### How to test this PR?

Use steps of the issue

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: extensions/podman/packages/extension/src/extension.ts [hunk 1]
```diff
@@ -669,16 +671,19 @@ async function timeout(time: number): Promise<void> {
...
-    try {
-      await updateMachines(provider, podmanConfiguration);
-    } catch (error) {
-      // ignore the update of machines
+    // skip the update during the auto start process
+    if (!autostartInProgress) {
+      try {
+        await updateMachines(provider, podmanConfiguration);
+      } catch (error) {
+        // ignore the update of machines
```
Comment (axel7083) [inline extensions/podman/packages/extension/src/extension.ts:685]: question: why the linter is not complaining

File: extensions/podman/packages/extension/src/extension.ts [hunk 2]
```diff
@@ -1453,45 +1458,55 @@ export async function activate(extensionContext: extensionApi.ExtensionContext):
...
-      } catch (error) {
-        // ignore the update of machines
-      }
+  const doAutoStart = async (logger: extensionApi.Logger): Promise<void> => {
+    autostartInProgress = true;
+    // If autostart has been enabled for the machine, try to start it.
+    try {
+      await updateMachines(provider, podmanConfiguration);
+    } catch (error) {
+      // ignore the update of machines
```
Comment (axel7083) [inline extensions/podman/packages/extension/src/extension.ts:1467]: same :thinking:

File: extensions/podman/packages/extension/src/extension.ts (hunk 1 above)
Comment (benoitf) [reply extensions/podman/packages/extension/src/extension.ts:685]: I don't know (I just moved the code to a try/finally block)

File: extensions/podman/packages/extension/src/extension.ts (hunk 2 above)
Comment (benoitf) [reply extensions/podman/packages/extension/src/extension.ts:1467]: it's the existing code there

**Review by axel7083 — APPROVED** [review]
LGTM: I tried on fedora with a native connection and a podman machine (qemu). When launching Podman Desktop with autostarting I am able to see my machine started withotu issue, and only see one resource card.

**Review by dgolovin — APPROVED** [review]
Works for me 

image

**Review by odockal — APPROVED** [review]
Fix works well. I tested on both Mac OS and Windows.

File: extensions/podman/packages/extension/src/extension.spec.ts [hunk 3]
```diff
@@ -3107,3 +3107,85 @@ describe('connectionAuditor', () => {
...
+
+  // call 100 times monitorMachines
+  for (let i = 0; i < 100; i++) {
+    extension.monitorMachines(provider, podmanConfiguration).catch(() => {});
+  }
+
+  await promiseAutoStart;
+
+  // should be only 1 but we allow some more calls (if there is not a check to check during the autostart it would be 100+ calls)
+  expect(podmanMachineListCalls).toBeLessThan(5);
```
Comment (jeffmaury) [inline extensions/podman/packages/extension/src/extension.spec.ts:3189]: Hard to understand the logic here, why don't we check for 1 only ?

Comment (benoitf) [reply extensions/podman/packages/extension/src/extension.spec.ts:3189]: due to timers/ asynchronous, some events may start so to avoid a flaky test I used 5

**Review by jeffmaury — APPROVED** [review]
LGTM
