### PR TITLE
fix: cleanup log files before starting the app

### LINKED ISSUE #10120: 160GB of launchd-stderr.log
### Bug description

On my Macbook (M1) I was running out of space. Suddenly "no space left on device". I have identified the logfiles from podman desktop as problem:

```
160G 26 Nov 17:15 launchd-stderr.log
1,7G 20 Nov 23:30 launchd-stdout.log
```

Last lines of the logfile are

```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:92308)
    at _.send (node:electron/js2c/browser_init:2:75634)
    at /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:349:8824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I don't know what went wrong here. I didn't notice any problems with podman desktop. I would expect that logfiles should never get so huge

### Operating system

macOs 15.1.1

### Installation Method

Installer from website/GitHub releases

### Version

1.14.1

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
macOS pList files are appending data to previous log files. Ensure to clean (truncate) the log file before starting the application. It ensures the log files won't grow indefinitely 

### What issues does this PR fix or reference?

fixes https://github.com/podman-desktop/podman-desktop/issues/10120

### How to test this PR?

on macOS only:
using a production binary installed in /Applications folder, disable and enable again the startup on Login in preferences
logout from your current macOS session and login

check that the log files have been wiped truncated before the app is starting

- [x] Tests are covering the bug fix or the new feature

the file was not tested, added unit tests

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
LGTM Codewise (don't have a Mac)

**Review by gastoner — APPROVED** [review]
LGTM Codewise (not tested)

File: packages/main/src/system/macos-startup.ts [hunk 1]
```diff
@@ -81,35 +85,37 @@ export class MacosStartup {
     <string>io.podman_desktop.PodmanDesktop</string>
     <key>ProgramArguments</key>
     <array>
-        <string>${this.podmanDesktopBinaryPath}</string>
+        <string>bash</string>
```
Comment (feloy) [inline packages/main/src/system/macos-startup.ts]: It seems on my Mac that `/bin/bash` is necessary

Comment (benoitf) [reply packages/main/src/system/macos-startup.ts]: PR amended

**Review by feloy — APPROVED** [review]

**Comment by benoitf** [comment]
cc @cbr7 if you could check this PR thanks

**Comment by cbr7** [comment]
@benoitf build this branch locally and installed it and the logs do get truncated now on macOS when the user logs back into macOS and PD restarts. Looks good from my side.

**Review by cbr7 — APPROVED** [review]

**Comment by benoitf** [comment]
thanks for the test @cbr7
