### PR TITLE
fix: Delete the removal of sha256: prefix in imageHref

### LINKED ISSUE #6801: bug(ImageDetails): navigation to container image crashes Podman Desktop
### Bug description

https://github.com/containers/podman-desktop/assets/42176370/997bcbc4-f28c-45d5-a91c-2c3329496e3d

After that the application became completely crashed and user cannot perform any action except restarting Podman Desktop.

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

image

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoniaSandler**
### What does this PR do?
Deletes the removal of `sha256:` prefix in the `imageHref` property of the `ContainerInfoUI` interface 
(the `sha256:` prefix stays in `imageHref`)
### What issues does this PR fix or reference?
Fixes https://github.com/containers/podman-desktop/issues/6801

### How to test this PR?

- [X] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by deboer-tim** [comment]
Maybe this would be a good time to start switching to the navigation API (#5556)?

**Comment by SoniaSandler** [comment]
@deboer-tim I'll take a look at the navigation API

**Review by axel7083 — CHANGES_REQUESTED** [review]
Globally this does not fix in certain scenario.

https://github.com/containers/podman-desktop/assets/42176370/af01ca2c-b3c7-417c-ab9f-34731db0d961

### Specific scenario

I am not really sure why, but in some cases it does not work, let's break the example down.

In my container list, I have a pod, and three container in it. One of the container, as visible in the video is called `llamacpp-server-podified`.

The link is the following reading from the `Inspect.image`: `sha256:462f6b668ede74b92d4823a309eda3033809dee5d3bd536f78308cd5afd7aaaf`

Let's go in the image list, and search this sha256

We do get the right image which is being used by the container

image

Now let's look at the url.

`http://localhost:5173/#/images/sha256:462f6b668ede74b92d4823a309eda3033809dee5d3bd536f78308cd5afd7aaaf/podman.Podman%20Machine/cXVheS5pby9haS1sYWIvbGxhbWFjcHBwX3B5dGhvbjpsYXRlc3Q=/summary`

Now let's compare with the blank page url.

`http://localhost:5173/#/images/sha256:462f6b668ede74b92d4823a309eda3033809dee5d3bd536f78308cd5afd7aaaf/podman.Podman%20Machine/c2hhMjU2OjQ2MmY2YjY2OGVkZTc0YjkyZDQ4MjNhMzA5ZWRhMzAzMzgwOWRlZTVkM2JkNTM2Zjc4MzA4Y2Q1YWZkN2FhYWY=/summary`

Let's diff

```diff
- http://localhost:5173/#/images/sha256:462f6b668ede74b92d4823a309eda3033809dee5d3bd536f78308cd5afd7aaaf/podman.Podman%20Machine/cXVheS5pby9haS1sYWIvbGxhbWFjcHBwX3B5dGhvbjpsYXRlc3Q=/summary
+ http://localhost:5173/#/images/sha256:462f6b668ede74b92d4823a309eda3033809dee5d3bd536f78308cd5afd7aaaf/podman.Podman%20Machine/c2hhMjU2OjQ2MmY2YjY2OGVkZTc0YjkyZDQ4MjNhMzA5ZWRhMzAzMzgwOWRlZTVkM2JkNTM2Zjc4MzA4Y2Q1YWZkN2FhYWY=/summary
```

The last part of the url id different, which is the `ImageBase64RepoTag`, weird... 

Let's decode it:
```
$: atob("cXVheS5pby9haS1sYWIvbGxhbWFjcHBwX3B5dGhvbjpsYXRlc3Q=")
'quay.io/ai-lab/llamacppp_python:latest'
```

```
$: atob("c2hhMjU2OjQ2MmY2YjY2OGVkZTc0YjkyZDQ4MjNhMzA5ZWRhMzAzMzgwOWRlZTVkM2JkNTM2Zjc4MzA4Y2Q1YWZkN2FhYWY=")
'sha256:462f6b668ede74b92d4823a309eda3033809dee5d3bd536f78308cd5afd7aaaf'
```

Okey okey, so the `ImageBase64RepoTag` is one case is the one of the sha256, and the other of the image tag. This is a problem.

cc @deboer-tim @benoitf the consequence is the following: in `image-utils.ts` we are trying to find an image based on the base64Tag provided

https://github.com/containers/podman-desktop/blob/61eefc784b4c191bb14242dc3ecb9cd905ca346c/packages/renderer/src/lib/image/image-utils.ts#L244-L245

But we construct the image href with a base64 value from the container info

https://github.com/containers/podman-desktop/blob/cb188d7d5b71bf295c7f8d02c1b5b5234d9eae00/packages/renderer/src/lib/container/container-utils.ts#L161

which seems to not exists in the images available.

## Solution proposal

We are generating a list of imageInfo for the ImageDetails 

https://github.com/containers/podman-desktop/blob/6b615e4cf1941451834b531a126a0640231e0bd8/packages/renderer/src/lib/image/ImageDetails.svelte#L75

Those image are generated by iterating over the `RepoTags: string[]` property like shown bellow

https://github.com/containers/podman-desktop/blob/61eefc784b4c191bb14242dc3ecb9cd905ca346c/packages/renderer/src/lib/image/image-utils.ts#L204

As we understood above, one condition that is not generated is the cases where the `base64RepoTag` is the sha256 itself. So we could add this possiblity and do the following

```diff
- return imageInfo.RepoTags.map(repoTag => {
+ return [...imageInfo.RepoTags, imageInfo.Id].map(repoTag => {
```

This solutions works on my computer **in addition** of  the change made by @SoniaSandler.

Moreover, to cover all cases, we might also generate one more imageInfo for the case where there are not RepoTags

https://github.com/containers/podman-desktop/blob/61eefc784b4c191bb14242dc3ecb9cd905ca346c/packages/renderer/src/lib/image/image-utils.ts#L181

**Comment by deboer-tim** [comment]
Excellent digging @axel7083. I think your solution is good, but I also can't help feeling that we need to understand/define what the full unique identifier(s) are for an image, and this code should only exist with the navigation helper and either image details or utils. i.e. places like container utils should have no idea how to build the url for an image or what the unique properties are. Then we should also repeat for all other types. :)

**Comment by SoniaSandler** [comment]
@deboer-tim @axel7083 I've added Axel's solution to the PR. However, I ran into some issues with AI-lab, so I wasn't able to get an image that might have the same problem of two different tags and check that the new addition does solve this problem completely. The images that I have work with the original change (just adding back the `sha256`), so please let me know if that works or if additional change is required. If this change works, it fixes this bug for now (but it also add duplicate images to `ImageList` as seen in the screenshot below), but I'm not sure if this problem goes deeper than just this link issue since my images don't have it.
Also, using the navigation manager might also have the same problem since `navigateToImage` requires also an image tag, and here we have two different image tags from `ContainerInfo` and `ImageInfo`
Screenshot from 2024-07-09 19-34-21

**Comment by axel7083** [comment]
> it fixes this bug for now (but it also add duplicate images to `ImageList` as seen in the screenshot below)

This is a pretty big issue sadly, I did not notice this side effect when I made the change, this is probably not something we would want. I am not sure that would be acceptable.

Maybe one possible long term solution would be to stop using a mixte of many elements for the image url. As you mention the `navigateToImage` requires also some `image tag`.

I am not sure of the solution, it should probably be discussed with @benoitf when he will be back from PTO in a daily.

**Comment by benoitf** [comment]
The basic idea of the links is that when you do click on a specific image, it means you may have an associated tag and  you don't want to see other images sharing the same sha256 id.

And we don't want to list extra images with only the ids. (Here we want to have the same behavior than Docker Desktop, one line per tag even and not one line per image id or one extra line just with the image id)

From the provided analysis, it seems that for some case we don't have tags but only the ids.

We should not then add the id of the image to the tag as it'll cause extra lines in the image lists.

I would suggest to have different links, one for tags and one for id or a single link but with a prefix, either giving the id or the name of the tag.

so either a link to the id of the image like `#/images/sha256:462f6b66/engineid` (and in that case we could display all the tags of the image) or #/images/sha256:462f6b66/engineid/<base64 of the tag>`

or use `#/images/sha256:462f6b66/engineid/<base64 of either tag:tagName or sha256:id>` 

when decoding the base64, if it starts by tag we do a matching per tag, if sha wedo the matching on the image id.

**Comment by SoniaSandler** [comment]
> so either a link to the id of the image like `#/images/sha256:462f6b66/engineid` (and in that case we could display all the tags of the image) or #/images/sha256:462f6b66/engineid/`

@benoitf If I understood correctly, for id of image, the link will lead to an `ImageList` page with all the image with the same `imageId` we are looking for, right?

**Comment by benoitf** [comment]
@SoniaSandler yes, unless we can be sure that we never have a case with only the id and we always have the tag of the image ?

**Comment by SoniaSandler** [comment]
@benoitf Axel got a container where the link to the image has the id as the tag, so I don't think we can be 100% sure it won't happen again, but right now there is no page rendering for `images/imageId/engineId`, so I can add it in a separate PR if we want to show a list of images with only a specific `imageId`

**Comment by SoniaSandler** [comment]
@benoitf @axel7083 right now this PR is finished from my side. However, I can't verify that Axel's edge case works since I don't have images/containers with similar problems. Working links of images with Id instead of a tag should lead to pages with the route `images/imageId/engineId`.
However, since we currently don't have rendering for this route, in this PR, they will lead to an empty page. I opened a issue for the creation of page rendering for `images/imageId/engineId`- https://github.com/containers/podman-desktop/issues/8216

**Comment by axel7083** [comment]
> @benoitf @axel7083 right now this PR is finished from my side. However, I can't verify that Axel's edge case works since I don't have images/containers with similar problems. Working links of images with Id instead of a tag should lead to pages with the route `images/imageId/engineId`. However, since we currently don't have rendering for this route, in this PR, they will lead to an empty page. I opened a issue for the creation of page rendering for `images/imageId/engineId`- #8216

On my side it seems to be fixing the problem

https://github.com/user-attachments/assets/99a86733-b25f-4379-b942-ebeac8164a79

File: packages/renderer/src/lib/container/container-utils.ts [hunk 1]
```diff
@@ -18,6 +18,8 @@
 
 import type { Port } from '@podman-desktop/api';
 import { ContainerIcon } from '@podman-desktop/ui-svelte/icons';
+// eslint-disable-next-line unicorn/prefer-node-protocol
+import { Buffer } from 'buffer';
```
Comment (axel7083) [inline packages/renderer/src/lib/container/container-utils.ts:22]:
```suggestion
import { Buffer } from 'node:buffer';
```

We have a preference for `node:*` import, that's why they was a eslint warning

File: packages/renderer/src/lib/container/container-utils.ts [hunk 2]
```diff
@@ -136,6 +138,19 @@ export class ContainerUtils {
...
+      if (imageTag.startsWith('sha256:')) {
+        return `/images/${containerInfo.ImageID}/${containerInfo.engineId}`;
+      } else {
+        return `/images/${containerInfo.ImageID}/${containerInfo.engineId}/${containerInfo.ImageBase64RepoTag}/summary`;
+      }
+    } else {
+      return `/images/${containerInfo.ImageID}/${containerInfo.engineId}`;
+    }
+  }
+
```
Comment (benoitf) [inline packages/renderer/src/lib/container/container-utils.ts]: it seems we are not testing the case without sha256 ?

File: packages/renderer/src/lib/container/container-utils.ts (hunk 1 above)
Comment (SoniaSandler) [reply packages/renderer/src/lib/container/container-utils.ts:22]: @axel7083 I get an error and a white screen for PD if I use `node:buffer` instead of `buffer`
Screenshot from 2024-07-25 08-47-35

Comment (benoitf) [reply packages/renderer/src/lib/container/container-utils.ts:22]: ah yes it's because you're on the frontend side

Comment (benoitf) [reply packages/renderer/src/lib/container/container-utils.ts:22]: you need to keep `buffer`

File: packages/renderer/src/lib/container/container-utils.ts (hunk 2 above)
Comment (SoniaSandler) [reply packages/renderer/src/lib/container/container-utils.ts]: @benoitf I'm not sure I understand what you mean. Do you mean if there is no tag, but the `imageId` doesn't start with `sha256` -> add `containerInfo.ImageBase64RepoTag === containerInfo.ImageId` to the `if` statement in line 144?

File: packages/renderer/src/lib/container/container-utils.ts (hunk 1 above)
Comment (axel7083) [reply packages/renderer/src/lib/container/container-utils.ts:22]: Okey I see the issue. But why are we using Buffer to decode a base64 instead of `btoa` @benoitf  any idea ?

**Review by benoitf — APPROVED** [review]
make sure the lines of getImageHref method are all tested

also maybe name a constant for `/images/${containerInfo.ImageID}/${containerInfo.engineId}`;
as we copy/paste 3 times the same value

but I'm not sure we need all these if else if else

could be a single condition
```ts
const imageTag = containerInfo.ImageBase64RepoTag ? Buffer.from(...) : ''
if (imageTag.startsWith('sha256')
 ....
else
...
```

so no need to have the constant

File: packages/renderer/src/lib/container/container-utils.ts (hunk 2 above)
Comment (benoitf) [reply packages/renderer/src/lib/container/container-utils.ts]: sorry I wasn't clear enough
I mean to have tests in the spec.ts file covering all the branches of your new method

File: packages/renderer/src/lib/container/container-utils.ts (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/lib/container/container-utils.ts:22]: I think it's because they're flagged as deprecated

File: packages/renderer/src/lib/container/container-utils.ts (hunk 2 above)
Comment (SoniaSandler) [reply packages/renderer/src/lib/container/container-utils.ts]: @benoitf Line 323 (in the `speac.ts` file) tests the url with an image tag, and the test in line 337 checks the url with an image id instead of a tag, but it looks like I'll have to add another one for the case of `if (containerInfo.ImageBase64RepoTag)`

File: packages/renderer/src/lib/container/container-utils.ts (hunk 1 above)
Comment (axel7083) [reply packages/renderer/src/lib/container/container-utils.ts:22]: https://stackoverflow.com/a/70851350

As mention in the issue, only `btoa` on node has been deprecated not the one on DOM

**Review by benoitf — APPROVED** [review]

**Comment by SoniaSandler** [comment]
@axel7083 do you approve these changes? merging is blocked due to request changes from June 18

**Review by axel7083 — APPROVED** [review]
LGTM ! Sorry I missed the request review
