### PR TITLE
fix: Pods from Kind are not visible in Podman Desktop

### LINKED ISSUE #2030: Pods from Kind are not visible in Podman Desktop
### Bug description

Following: https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

Pods are not visible in Podman Desktop.

capture_d___e__cran_2023-04-11_a___16 59 07_720

### Operating system

Venture 13.2

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2030

### Screenshot/screencast of this PR

pod

### What issues does this PR fix or reference?

Fixes #2030

### How to test this PR?

1. Create a kind cluster
2. Podify a container to that cluster
3. Go to the Pods tab and the new pod should be displayed

### CODE REVIEW

File: packages/main/src/plugin/kubernetes-client.ts [hunk 1]
```diff
@@ -207,10 +211,47 @@ export class KubernetesClient {
...
+      }
+    }
+    if (!namespace) {
+      namespace = 'default';
+    }
+    return namespace;
   }
 
-  refresh() {
+  async refresh() {
```
Comment (benoitf) [inline packages/main/src/plugin/kubernetes-client.ts:254]: if you change to async, shouldn't the caller used the await now when calling the function ?

Comment (jeffmaury) [reply packages/main/src/plugin/kubernetes-client.ts:254]: No because this function is called to trigger an update to the context

Comment (benoitf) [reply packages/main/src/plugin/kubernetes-client.ts:254]: I mean, it's a pattern.
it may lead to unhandled errors (let say tomorrow someone include in refresh something that is causing an error

https://eslint.org/docs/latest/rules/require-await

**Review by benoitf — APPROVED** [review]
please fix the async/await for refresh to avoid any code smell issue

I was able to see pods from Kind or from OpenShift

I faced another issue (not related directly to this PR) but probably need to be fixed. I'll file a new issue https://github.com/containers/podman-desktop/issues/2035

image

I shouldn't see the Restart button in the kebab menu (I don't see stop and start but I can see restart)


Clicking on restart I have an error about engineID
image

**Review by lstocchi — APPROVED** [review]
LGTM, same remarks as @benoitf
