### PR TITLE
fix: removing skipLibCheck option in `package/extension-api/tsconfig.json`

### LINKED ISSUE #5879: typescript configuration issue lead to problems with certain interface/types not being defined
### Bug description

Some elements in the extension-api are not defined, and there are not error where it should be. Leading to potential definition missed

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Adds the missing interfaces/types definition in the `extension-api.d.ts` file.

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/5879

### How to test this PR?

- [x] compile without the skipLibCheck option

### CODE REVIEW

**Comment by axel7083** [comment]
cc @benoitf the `extensionApi.provider.getProviderLifecycleContext` is kinda annoying (see linter), and I don't really know how to fix it.

> To summarize, before this PR, the linter was not able to know the types, so it was ignoring it. Now the argument `providerConnectionInfo` of the `getProviderLifecycleContext` takes `ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo` **but** in the podman extension, we provide `ContainerProviderConnection` which has some differences, and make it incompatible.

**Review by dgolovin — CHANGES_REQUESTED** [review]
@axel7083 It looks like ProviderContainerConnectionInfo and ProviderKuberneterConnectionInfo are DAO objects leaked from internal API https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/api/provider-info.ts.

Have not tested it all the way, but if you remove them form API definition file nothing is affected.

**Comment by benoitf** [comment]
looks like it's stale. AFAIK what @dgolovin said is accurate

**Comment by axel7083** [comment]
> looks like it's stale. AFAIK what @dgolovin said is accurate

I removed `ProviderContainerConnectionInfo` and `ProviderKubernetesConnectionInfo`, but we are facing many other issues

File: packages/renderer/src/lib/pod/PodCreateFromContainers.svelte [hunk 1]
```diff
@@ -86,7 +86,14 @@ async function doCreatePodFromContainers() {
...
   // first create pod
-  const { Id, engineId } = await window.createPod({ name: podCreation.name, portmappings, provider: selectedProvider });
+  const { Id, engineId } = await window.createPod({
+    name: podCreation.name,
+    portmappings,
+    provider: {
+      ...selectedProvider,
+      status: () => selectedProvider?.status ?? 'unknown',
+    },
+  });
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/PodCreateFromContainers.svelte]: AFAIK we should not have to do this

File: packages/main/src/plugin/container-registry.spec.ts [hunk 2]
```diff
@@ -1416,7 +1425,10 @@ describe('buildImage', () => {
       containerFile: '/dir/dockerfile',
       tag: 'name',
       platform: '',
-      provider: connection,
+      provider: {
+        ...connection,
+        status: () => connection.status,
+      },
```
Comment (benoitf) [inline packages/main/src/plugin/container-registry.spec.ts]: IMHO the test is correct without this change

**Review by benoitf — CHANGES_REQUESTED** [review]
some changes are not expected.

Client should not have to provide status() method

**Comment by axel7083** [comment]
> some changes are not expected.
> 
> Client should not have to provide status() method

The question is deeper. `ProviderContainerConnectionInfo` status field is a string, where `ContainerProviderConnection` is a function returning a string.

_We were lucky in the past that it did not raised an error_ but we were passing the wrongs objects, and the typing definitions are different. We need to discuss how we want to solve that

**Comment by benoitf** [comment]
> The question is deeper. ProviderContainerConnectionInfo status field is a string, where ContainerProviderConnection is a function returning a string.

yes it's expected

**Comment by benoitf** [comment]
one object is created by the providers (on the backend side) with methods
the other object is the one that UI can use and they're 'plain' object, no functions

**Comment by axel7083** [comment]
@benoitf this PR need to be divided, and what we want to do need to be cleared up because I am not seeing what we expect here. We need to change some functions signature to be able to handle some cases here

**Comment by benoitf** [comment]
yes 👍

File: packages/main/src/plugin/extension-loader.ts [hunk 3]
```diff
@@ -725,9 +724,12 @@ export class ExtensionLoader {
...
       getProviderLifecycleContext(
         providerId: string,
-        providerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+        containerProviderConnection: containerDesktopAPI.ContainerProviderConnection,
       ): containerDesktopAPI.LifecycleContext {
-        return providerRegistry.getMatchingProviderLifecycleContextByProviderId(providerId, providerConnectionInfo);
+        return providerRegistry.getMatchingProviderLifecycleContextByProviderId(providerId, {
+          ...containerProviderConnection,
+          status: containerProviderConnection.status(),
+        });
```
Comment (benoitf) [inline packages/main/src/plugin/extension-loader.ts]: I think it's inside providerRegistry.getMatchingProviderLifecycleContextByProviderId that we should add the 
providerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo

**Comment by benoitf** [comment]
@axel7083 if you rebase and include https://github.com/containers/podman-desktop/pull/6203 I think it'll reduce the number of changes and remove the need to provide status() method for at least createPod

File: packages/main/src/plugin/extension-loader.ts (hunk 3 above)
Comment (axel7083) [reply packages/main/src/plugin/extension-loader.ts]: @benoitf currently the `getMatchingProviderLifecycleContextByProviderId` is the following

```ts
getMatchingProviderLifecycleContextByProviderId(
    providerId: string,
    providerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
  ): LifecycleContextImpl
```

you want to make the following ?
```diff
- providerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+ providerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo | containerDesktopAPI.ContainerProviderConnection,
```

File: packages/main/src/plugin/container-registry.spec.ts (hunk 2 above)
Comment (axel7083) [reply packages/main/src/plugin/container-registry.spec.ts]: No. Inside containerDesktopAPI.BuildImageOptions we have the following
```
provider?: ContainerProviderConnection;
```

Which is **not** compatible with ProviderContainerConnectionInfo.

Comment (benoitf) [reply packages/main/src/plugin/container-registry.spec.ts]: will need another change in the BuildImageOptions like for createPod
the test should not be changed

File: packages/main/src/plugin/extension-loader.ts (hunk 3 above)
Comment (benoitf) [reply packages/main/src/plugin/extension-loader.ts]: I guess so

**Comment by axel7083** [comment]
> @axel7083 if you rebase and include #6203 I think it'll reduce the number of changes and remove the need to provide status() method for at least createPod

@benoitf I have a proposal. The `ProviderContainerConnectionInfo` (internally) and `ContainerProviderConnection` (api) share 3 identical properties 
- `name: string`
- `type: 'docker' | 'podman'`
- `endpoint: ContainerProviderConnectionEndpoint`

Most of the methods `getMatchingContainerProvider`, `getMatchingEngineFromConnection`, `buildImage` etc. would have enough with an interface with only those properties.
Let's create the following inside the extension-api.d.ts

```ts
export interface BaseContainerConnectionProvider {
    name: string;
    type: 'docker' | 'podman';
    endpoint: ContainerProviderConnectionEndpoint;
  }
```

> If you have a better name I would be willing to change it

and make the `ProviderContainerConnectionInfo` and `ContainerProviderConnection` **extend** containerDesktopAPI.BaseContainerConnectionProvider.

If you agree with this idea, I can make another PR for this

File: packages/extension-api/src/extension-api.d.ts [hunk 4]
```diff
@@ -827,7 +827,7 @@ declare module '@podman-desktop/api' {
     /**
      * A description of the field to be show (Markdown format)
      */
-    markdownDescription?;
+    markdownDescription?: string;
```
Comment (benoitf) [inline packages/extension-api/src/extension-api.d.ts]: maybe issue a small PR with the changes related to adding the missing types as it should work out of the box

this one, new NotificationType, IPAM interface, DeviceRequest etc

File: packages/main/src/plugin/container-registry.spec.ts [hunk 5]
```diff
@@ -3210,7 +3222,10 @@ test('check createPod uses running podman connection if ProviderContainerConnect
 
   const result = await containerRegistry.createPod({
     name: 'pod',
-    provider: containerProviderConnection,
+    provider: {
+      ...containerProviderConnection,
+      status: () => containerProviderConnection.status,
+    },
```
Comment (benoitf) [inline packages/main/src/plugin/container-registry.spec.ts]: should be removed with the new changes

File: packages/extension-api/src/extension-api.d.ts (hunk 4 above)
Comment (axel7083) [reply packages/extension-api/src/extension-api.d.ts]: Yes, this PR was suppose to be small enough for those changes, but it start to get too big. Agreed

File: packages/main/src/plugin/index.ts [hunk 6]
```diff
@@ -1069,7 +1069,10 @@ export class PluginSystem {
             containerFile: relativeContainerfilePath,
             tag: imageName,
             platform,
-            provider: selectedProvider,
+            provider: {
+              ...selectedProvider,
+              status: () => selectedProvider.status,
+            },
```
Comment (benoitf) [inline packages/main/src/plugin/index.ts]: here as well we should remove this change and make the method accepting the info object

**Comment by benoitf** [comment]
> and make the ProviderContainerConnectionInfo and ContainerProviderConnection extend containerDesktopAPI.BaseContainerConnectionProvider.

I disagree internal types should not extend extension API types

File: packages/main/src/plugin/extension-loader.ts (hunk 3 above)
Comment (axel7083) [reply packages/main/src/plugin/extension-loader.ts]: Done

**Comment by axel7083** [comment]
@benoitf linter say yes ✅ !

File: packages/main/src/plugin/provider-registry.ts [hunk 7]
```diff
@@ -812,7 +815,10 @@ export class ProviderRegistry {
 
   getMatchingProviderLifecycleContextByProviderId(
     providerId: string,
-    providerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+    providerConnectionInfo:
+      | ProviderContainerConnectionInfo
```
Comment (benoitf) [inline packages/main/src/plugin/provider-registry.ts:819]:
```suggestion
      ProviderContainerConnectionInfo
```
should we remove this first `|`

File: packages/main/src/plugin/provider-registry.ts [hunk 8]
```diff
@@ -789,7 +789,10 @@ export class ProviderRegistry {
 
   getMatchingConnectionLifecycleContext(
     internalId: string,
-    providerContainerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+    providerContainerConnectionInfo:
+      | ProviderContainerConnectionInfo
```
Comment (benoitf) [inline packages/main/src/plugin/provider-registry.ts:793]:
```suggestion
      ProviderContainerConnectionInfo
```

should we remove this first `|`

File: packages/main/src/plugin/extension-loader.ts [hunk 9]
```diff
@@ -725,7 +725,10 @@ export class ExtensionLoader {
       },
       getProviderLifecycleContext(
         providerId: string,
-        providerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+        providerConnectionInfo:
+          | containerDesktopAPI.ContainerProviderConnection
```
Comment (benoitf) [inline packages/main/src/plugin/extension-loader.ts]: should we remove this first `|`
```suggestion
          containerDesktopAPI.ContainerProviderConnection
```

File: packages/main/src/plugin/provider-registry.ts [hunk 10]
```diff
@@ -921,7 +927,10 @@ export class ProviderRegistry {
 
   getMatchingConnectionFromProvider(
     internalProviderId: string,
-    providerContainerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+    providerContainerConnectionInfo:
+      | ProviderContainerConnectionInfo
```
Comment (benoitf) [inline packages/main/src/plugin/provider-registry.ts:931]:
```suggestion
      ProviderContainerConnectionInfo
```

**Comment by axel7083** [comment]
> should we remove this first |

@benoitf prettier do not want it to be removed :(

**Review by benoitf — APPROVED** [review]
nice enhancement 🎉

**Comment by axel7083** [comment]
@dgolovin waiting on your `change requested`

File: packages/main/src/plugin/extension-loader.ts [hunk 11]
```diff
@@ -725,7 +725,10 @@ export class ExtensionLoader {
...
+          | ProviderContainerConnectionInfo
+          | ProviderKubernetesConnectionInfo,
```
Comment (dgolovin) [inline packages/main/src/plugin/extension-loader.ts]:
```suggestion
        providerConnectionInfo: containerDesktopAPI.ContainerProviderConnection
```

IMO there is no need for union type here, because you cannot use internal types from client extension.

File: packages/main/src/plugin/provider-registry.ts [hunk 12]
```diff
@@ -812,7 +815,10 @@ export class ProviderRegistry {
 
   getMatchingProviderLifecycleContextByProviderId(
     providerId: string,
-    providerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+    providerConnectionInfo:
+      | ProviderContainerConnectionInfo
+      | ProviderKubernetesConnectionInfo
+      | ContainerProviderConnection,
```
Comment (dgolovin) [inline packages/main/src/plugin/provider-registry.ts:821]: This method called only from extension loader and only with objects that is instance of `ContainerProviderConnection', so no union type is needed as well.

```suggestion
    providerConnectionInfo: ContainerProviderConnection,
```

File: packages/main/src/plugin/provider-registry.ts [hunk 13]
```diff
@@ -789,7 +789,10 @@ export class ProviderRegistry {
 
   getMatchingConnectionLifecycleContext(
     internalId: string,
-    providerContainerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+    providerContainerConnectionInfo:
+      | ProviderContainerConnectionInfo
+      | ProviderKubernetesConnectionInfo
+      | ContainerProviderConnection,
```
Comment (dgolovin) [inline packages/main/src/plugin/provider-registry.ts:795]: This union type is fine, because it is called from renderer with info objects and from extension-loader.

File: packages/main/src/plugin/provider-registry.ts [hunk 14]
```diff
@@ -921,7 +927,10 @@ export class ProviderRegistry {
 
   getMatchingConnectionFromProvider(
     internalProviderId: string,
-    providerContainerConnectionInfo: ProviderContainerConnectionInfo | ProviderKubernetesConnectionInfo,
+    providerContainerConnectionInfo:
+      | ProviderContainerConnectionInfo
+      | ProviderKubernetesConnectionInfo
+      | ContainerProviderConnection,
```
Comment (dgolovin) [inline packages/main/src/plugin/provider-registry.ts:933]: This is required too, because it is called from ```getMatchingProviderLifecycleContextByProviderId```

**Review by dgolovin — APPROVED** [review]
LGTM
nit: some union types are not required.
Compiled and run locally to test suggested changes. Works for me.

File: packages/main/src/plugin/extension-loader.ts [hunk 15]
```diff
@@ -725,10 +725,7 @@ export class ExtensionLoader {
       },
       getProviderLifecycleContext(
         providerId: string,
-        providerConnectionInfo:
-          | containerDesktopAPI.ContainerProviderConnection
-          | ProviderContainerConnectionInfo
-          | ProviderKubernetesConnectionInfo,
+        providerConnectionInfo: containerDesktopAPI.ContainerProviderConnection
```
Comment (axel7083) [inline packages/main/src/plugin/extension-loader.ts]:
```suggestion
        providerConnectionInfo: containerDesktopAPI.ContainerProviderConnection,
```

**Comment by axel7083** [comment]
🚀

**Comment by benoitf** [comment]
looks like this PR has broken the website build

when looking at the PR check there were failures 
https://github.com/containers/podman-desktop/actions/runs/8137643006/job/22236482437

but it was reported as ✅ 

skipLibCheck might be related there

**Comment by axel7083** [comment]
> looks like this PR has broken the website build
> 
> when looking at the PR check there were failures https://github.com/containers/podman-desktop/actions/runs/8137643006/job/22236482437
> 
> but it was reported as ✅
> 
> skipLibCheck might be related there

I will take a look

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/pull/6251 in the meantime as it broke the website

**Comment by axel7083** [comment]
> #6251 in the meantime as it broke the website

I opened https://github.com/tgreyuk/typedoc-plugin-markdown/issues/583 to warn about the problem of the exit code being 0 when the Typedoc fails. 
I also open a PR to fix the issue on their side https://github.com/tgreyuk/typedoc-plugin-markdown/pull/584

**Comment by benoitf** [comment]
thanks @axel7083
