### PR TITLE
fix: avoid propagating event of PasswordInput component for show/hide

### LINKED ISSUE #13798: passwordInput component can submit forms
### Bug description

when clicking on the button show/hide, if the component is used inside a form, it'll send the form as the event is propagated

### Operating system

macOS

### Installation Method

None

### Version

1.21.0

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
clicking on show/hide button was submitting the form

### What issues does this PR fix or reference?

fixes https://github.com/podman-desktop/podman-desktop/issues/13798

### How to test this PR?

unit test provided
- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

File: packages/renderer/src/lib/ui/PasswordInputTest.svelte [hunk 1]
```diff
@@ -0,0 +1,10 @@
+<script lang="ts">
```
Comment (simonrey1) [inline packages/renderer/src/lib/ui/PasswordInputTest.svelte:1]: This component is displayed as "Legacy mode" in vscode, please create new Svelte components in "Runes mode"

**Review by simonrey1 — APPROVED** [review]
new UT is passing, and becomes red if we delete "  event.preventDefault();" so this change is working

File: packages/renderer/src/lib/ui/PasswordInputTest.svelte (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/lib/ui/PasswordInputTest.svelte:1]: ~~yes but rewriting or porting this component to svelte5 is a different scope~~

Comment (benoitf) [reply packages/renderer/src/lib/ui/PasswordInputTest.svelte:1]: hmm I think it's the onsubmit, I'll update

Comment (benoitf) [reply packages/renderer/src/lib/ui/PasswordInputTest.svelte:1]: fixed
