### PR TITLE
nit: fix autostart not working

### LINKED ISSUE #2781: Podman Machine AutoStarts EVEN when AutoStart button is set to Disabled
### Bug description

After updating Podman Desktop to 1.1.0, it tries to start the Podman Machine on every launch of Podman desktop DESPITE the "Autostart container Engine" setting being set to "Disabled/Off"

image

### Operating system

Windows 10 Pro 22H2

### Version

1.1.0

### Steps to reproduce

Launch Podman Desktop
Stop Podman Machine if it is running, Observe it restarts on its own.
Toggled ""Autostart container Engine" to disabled/off
Exit Podman Desktop
Re-launch Podman Desktop, observe autostarting the Podman Machine despite the setting above.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
nit: fix autostart not working

### What does this PR do?

Fixes autostart not working correctly.

This bug occurs during onMount when ProviderConfigured.svelte is loaded
and does runProvider without checking the autostart configuration.

Very small change / nit.

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/6422176/19f9de01-0fc7-4787-95c7-188501030933

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/2781

### How to test this PR?

1. Disable autostart
2. Stop podman machine
3. Exit PD
4. Start PD, it should still stay stopped.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
~Tests failing, investigating~ fixed

**Review by jeffmaury — APPROVED** [review]
LGTM

File: packages/renderer/src/lib/dashboard/ProviderConfigured.svelte [hunk 1]
```diff
@@ -39,7 +39,13 @@ async function runProvider() {
   runInProgress = false;
 }
 
-onMount(() => {
+onMount(async () => {
+  // Get the autostart configuration setting. If it's disabled, we do *not* want to start the current container provider.
+  const autostart = await window.getConfigurationValue<boolean>('preferences.engine.autostart');
+  if (!autostart) {
+    runAtStart = false;
```
Comment (lstocchi) [inline packages/renderer/src/lib/dashboard/ProviderConfigured.svelte]: This break the original behavior though.
Let's say you have the autostart setting set to false and you are installing podman (idk for what reason this could happen). After the installation complete, you click on `Initialize and start`. The podman machine is initialized but it's not started bc the setting is false.
Shouldn't the click have priority over the setting?

**Review by lstocchi — COMMENTED** [review]
There is a empty kind file which should be removed.

File: packages/renderer/src/lib/dashboard/ProviderConfigured.svelte (hunk 1 above)
Comment (cdrage) [reply packages/renderer/src/lib/dashboard/ProviderConfigured.svelte]: You're right. I've changed it to `if (runAtStart && autostart)` instead so that it'll *only* run runProvider() if autostart is set to enabled / defined.

So that means after you press Initialize and start, it'll actually start.

Comment (lstocchi) [reply packages/renderer/src/lib/dashboard/ProviderConfigured.svelte]: Doesn't it have the same outcome? If autostart is false (bc the setting is false) and you click on `Initialize and start`, it will not get in the if branch. I guess the problem is that the `runAtStart` is true by default because the value of `initializationContext.mode`  is `InitializeAndStartMode` even when the initialize and start is not actually clicked.
I mean it is set differently only when the `Initialize only` option is clicked. Maybe it could be set at some other value when the user doesn't initialize any provider but only open up PD 🤔

**Comment by deboer-tim** [comment]
Something has been nagging me, but please let me know if I'm misunderstanding. My main concern: why is there anything in onMount() in the first place?

If I have auto-start off, then shouldn't the provider only start based on a user action? (if the user action makes this page appear, also odd that onMount() would be used)
If I have auto-start on, then don't I want the provider to start even if I don't go to the dashboard? e.g. it should start if only the tray is open, or we have some future path like the protocol handler where the dashboard is not the first page I see.

It seems like the auto-start should be in a completely different place in either case (not tied to a particular UI page) and this onMount() doesn't exist.

**Comment by cdrage** [comment]
> Something has been nagging me, but please let me know if I'm misunderstanding. My main concern: why is there anything in onMount() in the first place?
> 
> If I have auto-start off, then shouldn't the provider only start based on a user action? (if the user action makes this page appear, also odd that onMount() would be used) If I have auto-start on, then don't I want the provider to start even if I don't go to the dashboard? e.g. it should start if only the tray is open, or we have some future path like the protocol handler where the dashboard is not the first page I see.
> 
> It seems like the auto-start should be in a completely different place in either case (not tied to a particular UI page) and this onMount() doesn't exist.

100% agree and it's odd that it is there in the first place.. @lstocchi and I are having this discussion now on slack

**Comment by cdrage** [comment]
> Something has been nagging me, but please let me know if I'm misunderstanding. My main concern: why is there anything in onMount() in the first place?
> 
> If I have auto-start off, then shouldn't the provider only start based on a user action? (if the user action makes this page appear, also odd that onMount() would be used) If I have auto-start on, then don't I want the provider to start even if I don't go to the dashboard? e.g. it should start if only the tray is open, or we have some future path like the protocol handler where the dashboard is not the first page I see.
> 
> It seems like the auto-start should be in a completely different place in either case (not tied to a particular UI page) and this onMount() doesn't exist.

So the TLDR on slack is that we require onMount() to exist in order to be able to initialize / interact with the user in terms of initializing each provider. For example, we have initialize and start for Podman / button interaction before we use startProvider().

Makes sense as future features we'd be able to ask the user / interact before actually launching.

I've updated the PR to draft and I'll push some new code.

**Comment by cdrage** [comment]
Ready for review!

"Run Podman" or "Run Provider" button's will appear when autostart is false and Podman Desktop appears for the first time.

All it needed was an update to `runAtStart = autostart && initializationContext.mode === InitializeAndStartMode;`

Ready for review @lstocchi

**Comment by lstocchi** [comment]
> Ready for review!
> 
> "Run Podman" or "Run Provider" button's will appear when autostart is false and Podman Desktop appears for the first time.
> 
> All it needed was an update to `runAtStart = autostart && initializationContext.mode === InitializeAndStartMode;`

I still face the same issue. If i click on `initialize and start` i expect that it creates a machine and start it. But if the autostart flag is set to false, the machine is only created and not started.

init-start-fail

the question is how it should work. Bc if the autostart flag has always priority then it works fine.

**Comment by benoitf** [comment]
I gave a quick look

@lstocchi My question is that it looks like the Dashboard page initialize a map called providerInitContexts setting the mode to `{ mode: InitializeAndStartMode };` without any user action so ProviderConfigured will always see mode is InitializeAndStartMode and will run the machine

I'm wondering why we initialize data to `InitializeAndStartMode` I suppose the value should be set only if user click on 'Init' or 'Init and Start' (this is what is done but it is also the default value??) and then we should initialize the context to something 'empty/none/do nothing'

like in Dashboard.svelte:
```
    context = { mode: DoNothingMode };
```

and ProviderInitUtils having
```
export const DoNothingMode = 'DoNothing';
export const InitializeOnlyMode = 'Initialize';
export const InitializeAndStartMode = 'Initialize and start';
export type InitializationMode = typeof NoneMode |typeof InitializeOnlyMode | typeof InitializeAndStartMode;
```

**Comment by cdrage** [comment]
> > Ready for review!
> > "Run Podman" or "Run Provider" button's will appear when autostart is false and Podman Desktop appears for the first time.
> > All it needed was an update to `runAtStart = autostart && initializationContext.mode === InitializeAndStartMode;`
> 
> I still face the same issue. If i click on `initialize and start` i expect that it creates a machine and start it. But if the autostart flag is set to false, the machine is only created and not started.
> 
> init-start-fail
> 
> the question is how it should work. Bc if the autostart flag has always priority then it works fine.

We have no way of knowing if it's been started for the first time, so I think we'd have to update the dashboard with a new value similar to Initialize and Start, what do you think?

EDIT: I see @benoitf and I commented at the same time. I'll update this PR so that we add a new value of "DoNothing" and only apply Init / Init and start when the user actually clicks the value.

**Comment by lstocchi** [comment]
> I gave a quick look
> 
> @lstocchi My question is that it looks like the Dashboard page initialize a map called providerInitContexts setting the mode to `{ mode: InitializeAndStartMode };` without any user action so ProviderConfigured will always see mode is InitializeAndStartMode and will run the machine
> 
> I'm wondering why we initialize data to `InitializeAndStartMode` I suppose the value should be set only if user click on 'Init' or 'Init and Start' (this is what is done but it is also the default value??) and then we should initialize the context to something 'empty/none/do nothing'
> 
> like in Dashboard.svelte:
> 
> ```
>     context = { mode: DoNothingMode };
> ```
> 
> and ProviderInitUtils having
> 
> ```
> export const DoNothingMode = 'DoNothing';
> export const InitializeOnlyMode = 'Initialize';
> export const InitializeAndStartMode = 'Initialize and start';
> export type InitializationMode = typeof NoneMode |typeof InitializeOnlyMode | typeof InitializeAndStartMode;
> ```

Correct. At that time i initialize it to `InitializeAndStartMode` as i didn't think it could cause any problem. But by changing the default value it should solve the issue

**Comment by cdrage** [comment]
Added DoNothing + changed the line to: `runAtStart = autostart || initializationContext.mode === InitializeAndStartMode;`

Tests done:
1. Disable autostart: When pressing initialize + start, podman starts correctly
2. Stop podman + restart podman desktop. Podman is still stopped.
3. Enable autostart, start podman desktop, Podman machine starts correctly

File: packages/renderer/src/lib/dashboard/ProviderConfigured.svelte [hunk 2]
```diff
@@ -39,7 +39,11 @@ async function runProvider() {
   runInProgress = false;
 }
 
-onMount(() => {
+onMount(async () => {
+  // Get the autostart configuration setting. If it's disabled, we do *not* want to start the current container provider.
```
Comment (benoitf) [inline packages/renderer/src/lib/dashboard/ProviderConfigured.svelte]: I think here we can keep the current code of the main branch( no need to check for autostart property. It's all user driven )

File: packages/renderer/src/lib/dashboard/ProviderConfigured.spec.ts [hunk 3]
```diff
@@ -23,9 +23,15 @@ import { beforeAll, test, vi } from 'vitest';
 import { verifyStatus } from './ProviderStatusTestHelper.spec';
 import ProviderConfigured from '/@/lib/dashboard/ProviderConfigured.svelte';
 
-// fake the window.events object
 beforeAll(() => {
   (window as any).startProvider = vi.fn();
+
+  // mock that autostart is configured as true
```
Comment (benoitf) [inline packages/renderer/src/lib/dashboard/ProviderConfigured.spec.ts:29]: not sure if it's used now ?

**Review by benoitf — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]

**Comment by cdrage** [comment]
Removed the lingering comment and have marked this as auto-merge
