### PR TITLE
fix(feedback): confirmation dialogs

### LINKED ISSUE #10828: bug(feedback): submitting feedback asks the user wrong confirm message
### Bug description

https://github.com/user-attachments/assets/92f7b181-41fd-427b-bb6f-081969dccfec

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Open the feedback form
2. Click on submit
3. assert confirmation dialog is asking `Do you want to close the Feedback form? Closing will erase your input.`

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### Changes

- Adding confirm parameter to `SendFeedback#hideModal` function
- Make the Developer feedback close the modal without confirmation
- Make the Developer feedback display a nice message (might need improvement please share any idea) to confirm it has been sent
- Renaming `onCloseModal` to `close`, this is not an event, but a request, so no `on` prefix

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/10828

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/feedback/SendFeedback.svelte [hunk 1]
```diff
@@ -54,11 +56,10 @@ function handleUpdate(e: boolean): void {
 
 {#if displayModal}
 <div class='z-40'>
-  <Modal name="Share your feedback" on:close={hideModal}>
+  <Modal name="Share your feedback" on:close={(): Promise<void> => hideModal()}>
```
Comment (axel7083) [inline packages/renderer/src/lib/feedback/SendFeedback.svelte:59]: We can't just provide hideModal as its signature require a boolean as first argument, and this missmatch with the on:close Event type.

File: packages/renderer/src/lib/feedback/SendFeedback.svelte [hunk 2]
```diff
@@ -54,11 +56,10 @@ function handleUpdate(e: boolean): void {
...
     <div class="flex items-center justify-between pl-4 pr-3 py-3 space-x-2 text-[var(--pd-modal-header-text)]">
       <h1 class="grow text-lg font-bold capitalize">Share your feedback</h1>
-
-      <CloseButton on:click={hideModal} />
+      <CloseButton on:click={(): Promise<void> => hideModal()} />
```
Comment (axel7083) [inline packages/renderer/src/lib/feedback/SendFeedback.svelte:62]: Same as https://github.com/podman-desktop/podman-desktop/pull/10830/files#r1930322514

File: packages/renderer/src/lib/feedback/SendFeedback.svelte [hunk 3]
```diff
@@ -69,11 +70,11 @@ function handleUpdate(e: boolean): void {
     </div>
 
     {#if category === 'developers'}
-      <DevelopersFeedback onCloseForm={hideModal} contentChange={handleUpdate}/>
+      <DevelopersFeedback close={hideModal} contentChange={handleUpdate}/>
     {:else if category === 'bug'}
-      <GitHubIssueFeedback onCloseForm={hideModal} category="bug" contentChange={handleUpdate}/>
+      <GitHubIssueFeedback close={hideModal} category="bug" contentChange={handleUpdate}/>
```
Comment (benoitf) [inline packages/renderer/src/lib/feedback/SendFeedback.svelte]: question: why onCloseForm is renamed to close

note: close is meaningless, onclose is meaningful

**Comment by benoitf** [comment]
> Renaming onCloseModal to close, this is not an event, but a request, so no on prefix

it's what we call a callback no ?

**Comment by axel7083** [comment]
> it's what we call a callback no ?

From my POV we use `on*` when it is an event, onSubmit, onClick, onChange. But onClose is not triggered by the child it is requested by the child, the logic is on the parent component, so this is not an event, but a callback? 

ℹ️ I will revert to on* as this is not part of the issue, but this may need some discussion later to have more rules on the naming convention for the props

For example here we use `contentchange` but `onCloseForm` this is weird, as the content change is an event triggered by the component, and onCloseForm is not, it is a request

**Review by odockal — APPROVED** [review]
LGTM. Tested on Linux. I have found another issue not related to the PR: https://github.com/podman-desktop/podman-desktop/issues/10837

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@Mergifyio backport 1.16.x
