### PR TITLE
fix: report errors when analyzing extensions

### LINKED ISSUE #2871: When installing an extension that has an undefined displayName the extensions section gets broken
### Bug description

If an extension does not have a display name the extensions section is broken.
 
extension-tree-broken

It fails at 

```
export async function fetchExtensions() {
  const result = await window.listExtensions();
  result.sort((a, b) => a.displayName.localeCompare(b.displayName));
  extensionInfos.set(result);
}
```

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. install quay.io/lstocchi/sample-podman-extension:v1
2. check that your extensions section is broken

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Since PR #2990 is very old I'm creating a new one.

Adds an error property to analyzed extensions, and analyzeExtension() sets it whenever there is a problem loading a folder instead of returning undefined. Added error for missing manifest entries.

Updated callers to check for error instead of undefined, and send an error when trying to install an extension that has an error.

Tests updated to confirm an error is being created.

### Screenshot/screencast of this PR

Screenshot 2023-10-17 at 1 26 31 PM

### What issues does this PR fix or reference?

Fixes #2871.

### How to test this PR?

See issue https://github.com/containers/podman-desktop/issues/2871 - try installing this extension: quay.io/lstocchi/sample-podman-extension:v1

### CODE REVIEW

File: packages/main/src/plugin/extension-loader.ts [hunk 1]
```diff
@@ -310,22 +312,29 @@ export class ExtensionLoader {
...
-  async analyzeExtension(extensionPath: string, removable: boolean): Promise<AnalyzedExtension | undefined> {
+  async analyzeExtension(extensionPath: string, removable: boolean): Promise<AnalyzedExtension> {
     // do nothing if there is no package.json file
+    let error = undefined;
     if (!fs.existsSync(path.resolve(extensionPath, 'package.json'))) {
-      console.warn(`Ignoring extension ${extensionPath} without package.json file`);
-      return undefined;
+      error = `Ignoring extension ${extensionPath} without package.json file`;
+      console.warn(error);
+      return { error } as AnalyzedExtension;
```
Comment (benoitf) [inline packages/main/src/plugin/extension-loader.ts]: here I think it may lead to client's error as the object they'll get is not compliant to the typescript contract.
So while I see no problem of using that pattern in tests, we should not in main code as it may lead to runtime errors.

File: packages/main/src/plugin/extension-loader.ts [hunk 2]
```diff
@@ -310,22 +312,29 @@ export class ExtensionLoader {
...
     }
 
+    // log error if the manifest is missing required entries
     const manifest = await this.loadManifest(extensionPath);
+    if (!manifest.name || !manifest.displayName || !manifest.version || !manifest.publisher || !manifest.description) {
+      error = `Extension ${extensionPath} missing required manifest entries in package.json`;
```
Comment (benoitf) [inline packages/main/src/plugin/extension-loader.ts]: maybe add the required attributes in the error message (name, displayName, version, publisher & description ?) so it might help the user

**Review by benoitf — COMMENTED** [review]
overall LGTM

probably add tests to check specific error message returned

File: packages/main/src/plugin/extension-loader.ts (hunk 1 above)
Comment (deboer-tim) [reply packages/main/src/plugin/extension-loader.ts]: Understood, and I agree that would be better. I've changed it to return a regular AnalyzedExtension now. I didn't want to change the API contract, so added a couple 'fake' values like id and name (felt like these could cause problems if empty), and tried to give reasonable defaults/undefined elsewhere. I wasn't sure if there's a simpler way to do the subscription/dispose(), please review again.

File: packages/main/src/plugin/extension-loader.ts (hunk 2 above)
Comment (deboer-tim) [reply packages/main/src/plugin/extension-loader.ts]: Good point, added.

File: packages/main/src/plugin/extension-loader.ts [hunk 3]
```diff
@@ -312,27 +314,47 @@ export class ExtensionLoader {
...
+        id: '<unknown>',
+        name: '<unknown>',
+        path: extensionPath,
+        manifest: undefined,
+        api: <typeof containerDesktopAPI>{},
+        removable,
+        subscriptions: disposables,
+        dispose(): void {
+          disposables.forEach(disposable => disposable.dispose());
+        },
```
Comment (benoitf) [inline packages/main/src/plugin/extension-loader.ts]: I'm not sure why we dispose the disposables. Do we register subscriptions in case of errors ?

**Review by benoitf — COMMENTED** [review]
overall, LGTM

I'll need to test with an extension

File: packages/main/src/plugin/extension-loader.ts (hunk 3 above)
Comment (deboer-tim) [reply packages/main/src/plugin/extension-loader.ts]: Because we still have to return the subscriptions array from here I felt like we should correctly dispose it... but had forgot it was readonly anyway. Simplified this in new commit.

**Comment by deboer-tim** [comment]
@benoitf could you take another look?

**Review by lstocchi — APPROVED** [review]
LGTM 🚀

File: packages/main/src/plugin/extension-loader.ts [hunk 4]
```diff
@@ -293,12 +295,12 @@ export class ExtensionLoader {
...
     const analyzedFoldersExtension = (
       await Promise.all(folders.map(folder => this.analyzeExtension(folder, false)))
-    ).filter(extension => extension !== undefined) as AnalyzedExtension[];
+    ).filter(extension => !extension.error) as AnalyzedExtension[];
     analyzedExtensions.push(...analyzedFoldersExtension);
 
     const analyzedExternalExtensions = (
       await Promise.all(externalExtensions.map(folder => this.analyzeExtension(folder, false)))
-    ).filter(extension => extension !== undefined) as AnalyzedExtension[];
+    ).filter(extension => !extension.error) as AnalyzedExtension[];
```
Comment (dgolovin) [inline packages/main/src/plugin/extension-loader.ts]:
```suggestion
    ).filter(extension => !extension.error);
```

File: packages/main/src/plugin/extension-loader.ts [hunk 5]
```diff
@@ -312,22 +314,40 @@ export class ExtensionLoader {
       // collect all extensions from the pluginDirectory folders
       const analyzedPluginsDirectoryExtensions: AnalyzedExtension[] = (
         await Promise.all(pluginDirectories.map(folder => this.analyzeExtension(folder, true)))
-      ).filter(extension => extension !== undefined) as AnalyzedExtension[];
+      ).filter(extension => !extension.error) as AnalyzedExtension[];
```
Comment (dgolovin) [inline packages/main/src/plugin/extension-loader.ts]:
```suggestion
      ).filter(extension => !extension.error);
```

File: packages/main/src/plugin/extension-loader.ts [hunk 6]
```diff
@@ -293,12 +295,12 @@ export class ExtensionLoader {
 
     const analyzedFoldersExtension = (
       await Promise.all(folders.map(folder => this.analyzeExtension(folder, false)))
-    ).filter(extension => extension !== undefined) as AnalyzedExtension[];
+    ).filter(extension => !extension.error) as AnalyzedExtension[];
```
Comment (dgolovin) [inline packages/main/src/plugin/extension-loader.ts]: Here and below `as AnalyzedExtension[]` is not needed.
```suggestion
    ).filter(extension => !extension.error) as AnalyzedExtension[];
```

**Review by dgolovin — CHANGES_REQUESTED** [review]

File: packages/main/src/plugin/extension-loader.ts (hunk 4 above)
Comment (deboer-tim) [reply packages/main/src/plugin/extension-loader.ts]: Good catch, fixed all three instances in latest commit.

File: packages/main/src/plugin/extension-loader.ts (hunk 5 above)
Comment (deboer-tim) [reply packages/main/src/plugin/extension-loader.ts]: Fixed.

File: packages/main/src/plugin/extension-loader.ts (hunk 6 above)
Comment (deboer-tim) [reply packages/main/src/plugin/extension-loader.ts]: Fixed.

**Review by benoitf — APPROVED** [review]

**Comment by deboer-tim** [comment]
@dgolovin good to remove your request (fixed) and merge?

**Review by dgolovin — APPROVED** [review]
