### PR TITLE
fix: kind installation throws error if system wide install

### LINKED ISSUE #4168: bug: Kind installation throws error: Unable to install kind binary: [object Object]
### Bug description

When installing Kind binary on windows through the pop-up in left bottom corner, 
installation throws error: "Unable to install kind binary: [object Object]".
image

Kind binary is still downloaded to C:\Users\username\.local\share\containers\podman-desktop\extensions-storage\podman-desktop.kind

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

Update: Adding dev console error log:
```
main ↪️ [compose] Failed to install 'docker-compose' binary: [object Object]
console.<computed> @ VM50:2
(anonymous) @ VM50:2
emit @ VM49 sandbox_bundle:2
onMessage @ VM49 sandbox_bundle:2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #4168

### What does this PR do?

Fixes error reported when installing kind system wide

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #4168 

### How to test this PR?

1. Remove kind extension and system wide kind
2. Install kind from Podman Desktop and ask for system wide installation

### CODE REVIEW

File: packages/main/src/plugin/util/exec.ts [hunk 1]
```diff
@@ -64,6 +64,15 @@ export class Exec {
 
           // convert process.env to { [key: string]: string; }'
           const sudoEnv = env as { [key: string]: string };
+          /*
+           * sudo prompt verify keys and does not support keys with special characters
```
Comment (cdrage) [inline packages/main/src/plugin/util/exec.ts:84]: this is such an odd bug, is there any issue open upstream / we can link here for sudo prompt?

Comment (jeffmaury) [reply packages/main/src/plugin/util/exec.ts:84]: > this is such an odd bug, is there any issue open upstream / we can link here for sudo prompt?

Looks like a feature: https://github.com/jorangreef/sudo-prompt/blob/c3cc31a51bc50fe21fadcbf76a88609c0c77026f/index.js#L96

And repo is not active enough but will open an issue

**Review by cdrage — APPROVED** [review]
Tried this on Windows 10 enterprise and I do not get the error.

LGTM!

(unsure if we should write tests for this? but we don't have any tests for sudo prompt anyways right now)

**Review by lstocchi — APPROVED** [review]
I faced the issue when testing @cdrage PR and this fixes it ... can you explain a bit what it does exactly and what was the problem?

**Comment by cdrage** [comment]
@lstocchi Described here: https://github.com/jorangreef/sudo-prompt/blob/c3cc31a51bc50fe21fadcbf76a88609c0c77026f/index.js#L96

Actually I think it's important we get it in as a comment explaining why we did it, can you add the link: https://github.com/jorangreef/sudo-prompt/blob/c3cc31a51bc50fe21fadcbf76a88609c0c77026f/index.js#L96 to the PR as a comment in the code @jeffmaury ?

**Review by benoitf — COMMENTED** [review]
@jeffmaury could you add a unit test to check that environment is cleaned when we have invalid values ?

File: packages/main/src/plugin/util/exec.ts [hunk 2]
```diff
@@ -64,6 +64,15 @@ export class Exec {
...
+           * ( or ) on Windows
+           */
+          for (const key of Object.keys(sudoEnv)) {
```
Comment (benoitf) [inline packages/main/src/plugin/util/exec.ts:88]: if it's windows specific we need to remove only on Windows

**Review by benoitf — DISMISSED** [review]
require unit tests and should it be deleted or it requires some encoding ?

File: packages/main/src/plugin/util/exec.ts (hunk 2 above)
Comment (jeffmaury) [reply packages/main/src/plugin/util/exec.ts:88]: It's not Windows specific it's just that Windows env causes the error to be raised so path is to make sure error won't be raised

File: packages/main/src/plugin/util/exec.spec.ts [hunk 3]
```diff
@@ -430,6 +430,48 @@ describe('exec', () => {
...
+    const args = ['Hello, World!'];
+    (util.isWindows as Mock).mockReturnValue(true);
+    let options: any;
+
+    (sudo.exec as Mock).mockImplementation((_command, _options, callback) => {
+      callback(undefined);
+      options = _options;
+    });
+
+    vi.mock('child_process', () => {
```
Comment (dgolovin) [inline packages/main/src/plugin/util/exec.spec.ts]: This vi.mock call overrides all previous calls. It is luck they are all the same so nothing is affected.
It can be moved on top of the file with other mocks and removed from all the tests in this file.

**Review by dgolovin — APPROVED** [review]
you can delete mocking for child_process and move it up (optional).

**Comment by lstocchi** [comment]
Can this be merged after the rebase? It is needed for the compose onboarding @jeffmaury

**Comment by jeffmaury** [comment]
> Can this be merged after the rebase? It is needed for the compose onboarding @jeffmaury

I can't merge it @benoitf asked for changes, waiting for his approval

File: packages/main/src/plugin/util/exec.ts [hunk 4]
```diff
@@ -64,6 +64,16 @@ export class Exec {
...
+          /*
+           * sudo prompt verify keys and does not support keys with special characters
+           * ( or ) on Windows
+           * See https://github.com/jorangreef/sudo-prompt/blob/c3cc31a51bc50fe21fadcbf76a88609c0c77026f/index.js#L96
+           */
+          for (const key of Object.keys(sudoEnv)) {
+            if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key)) {
+              delete sudoEnv[key];
+            }
+          }
```
Comment (benoitf) [inline packages/main/src/plugin/util/exec.ts:92]: if it's windows specific, then probably as previously mentioned it's missing a `if isWindows` ?

Comment (jeffmaury) [reply packages/main/src/plugin/util/exec.ts:92]: It is already in a `isWindows` section see line 60

Comment (benoitf) [reply packages/main/src/plugin/util/exec.ts:92]: ok so no comment and I'm not blocking the merge :-)
