### PR TITLE
fix: Can't use locally built latest images on Kubernetes clusters

### LINKED ISSUE #2661: Can't use locally built latest images on Kubernetes clusters
### Bug description

I can't seem to pull a local image into the local kubernetes. The image appears as 

Screenshot 2023-05-29 at 08 18 57

Yet when I 'upload KIND cluster' and then try and use the image name I get...

```ImagePullBackOff```

### Operating system

macOS Ventura 13.4

### Version

1.0.x

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2661

### What does this PR do?

Allow to deploy locally built images with latest tag on Kubernetes clusters

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #2661 

### How to test this PR?

1. Build a local image using latest tag
2. Push that image to your Kubernetes cluster
3. Deploy that image on the Kubernetes cluster
4. Ensure the pod is running

### CODE REVIEW

File: packages/renderer/src/lib/pod/DeployPodToKube.svelte [hunk 1]
```diff
@@ -81,6 +81,7 @@ onMount(async () => {
     container.ports?.forEach((port: any) => {
       containerPortArray.push(port.hostPort);
     });
+    container.imagePullPolicy = 'IfNotPresent';
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/DeployPodToKube.svelte:84]: I'm wondering if it needs to be all the time or just if we don't specify a tag to the image ?

**Review by benoitf — APPROVED** [review]

File: packages/renderer/src/lib/pod/DeployPodToKube.svelte (hunk 1 above)
Comment (jeffmaury) [reply packages/renderer/src/lib/pod/DeployPodToKube.svelte:84]: This is the default if tag is different from latest so it's good to always set it to this value.
