### PR TITLE
fix: interpret arguments given to info command for example

### LINKED ISSUE #3017: microcks docker desktop extension is not working in Podman Desktop
### Bug description

https://github.com/microcks/microcks-docker-desktop-extension does not work but it's a plain UI extension so it should work

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

1.1.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Plug-ins provide arguments using quotes etc that need to be interpreted for the format expression so it doesn't return a quoted json response like '<my-value />'

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/3017

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

File: packages/main/src/plugin/docker-extension/docker-plugin-adapter.ts [hunk 1]
```diff
@@ -84,7 +84,7 @@ export class DockerPluginAdapter {
             updatedArgs = args;
           }
 
-          const spawnProcess = spawn(updatedCommand, updatedArgs, { env });
+          const spawnProcess = spawn(updatedCommand, updatedArgs, { env, shell: true });
```
Comment (jeffmaury) [inline packages/main/src/plugin/docker-extension/docker-plugin-adapter.ts:87]: As the arguments are passed as an array, there is no need to escape them with spaces so is this necessary and not error prone ?

Comment (benoitf) [reply packages/main/src/plugin/docker-extension/docker-plugin-adapter.ts:87]: the thing is that arguments are like `ddClient.docker.cli.exec("info", ["--format", "'{{json .}}'"])`

https://github.com/microcks/microcks-docker-desktop-extension/blob/927a51c91e7dcb5f5b40e4da4f98044cba2cb1d0/client/src/api/metrics.ts#L44

so they are providing `"'{{json .}}'"` which is then interpreted by default as `'{{json .}}'` and return `'{content of the json}'` instead of `{content of the json}`

Comment (jeffmaury) [reply packages/main/src/plugin/docker-extension/docker-plugin-adapter.ts:87]: I would guess that they should pass "{{json .}}" but maybe that will cause issues with Docker Desktop then

Comment (benoitf) [reply packages/main/src/plugin/docker-extension/docker-plugin-adapter.ts:87]: yes, it's to be bug compatible

**Review by jeffmaury — APPROVED** [review]
LGTM
