### PR TITLE
fix: support more fa icons

### LINKED ISSUE #6498: bug(Button): component does not show icon for certain fa icons
### Bug description

Icons such as `faGithub` has a prefix `fab`. However the check in the Button component does not support it

https://github.com/containers/podman-desktop/blob/48c0d3905f6acf60a1f4fb659610787f262a6c77/packages/renderer/src/lib/ui/Button.svelte#L25

### Operating system

windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

```svelte
    <Button icon="{faGithub}">Github</Button>
```

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Adding the prefix of unsupported fa icons to properly display them

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/6498

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/ui/Button.svelte [hunk 1]
```diff
@@ -21,7 +21,7 @@ export let padding: string =
 let iconType: string | undefined = undefined;
 
 onMount(() => {
-  if (icon?.prefix === 'fas') {
+  if (['fas', 'fab'].includes(icon?.prefix)) {
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/Button.svelte]: I think we have some code with 'fa' as prefix so maybe would be simpler

if you want to cover all icons then you'll be missing regular (`far` and maybe more)
https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/%40fortawesome/free-regular-svg-icons/faAddressCard.js#L3

Comment (axel7083) [reply packages/renderer/src/lib/ui/Button.svelte]: So what you recommend is doing like `icon?.prefix.startsWith('fa')` ?

Comment (benoitf) [reply packages/renderer/src/lib/ui/Button.svelte]: yes

Comment (benoitf) [reply packages/renderer/src/lib/ui/Button.svelte]: or maybe here we should have an unified utility class that really do checks all the available font awesome options

b/c I think each component is doing its own check

Comment (deboer-tim) [reply packages/renderer/src/lib/ui/Button.svelte]: Looks like we're doing this in at least 4 places, agreed a util function would be useful.

Comment (axel7083) [reply packages/renderer/src/lib/ui/Button.svelte]: I created a  `IconUtils` file to handle the logic, and changed the 4 places where the same logic was applied

File: packages/renderer/src/lib/ui/IconUtils.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ ***********************************************************************/
+
+import type { IconDefinition } from '@fortawesome/fontawesome-common-types';
+
+export const isIconDefinition = (icon: unknown): icon is IconDefinition => {
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/IconUtils.ts]: if you could rename to include FontAwesome maybe

isFontAwesomeIconDefinition

File: packages/renderer/src/lib/ui/IconUtils.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
+/**********************************************************************
+ * Copyright (C) 2023 Red Hat, Inc.
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/IconUtils.ts]:
```suggestion
 * Copyright (C) 2024 Red Hat, Inc.
```

File: packages/renderer/src/lib/ui/IconUtils.ts [hunk 4]
```diff
@@ -0,0 +1,29 @@
+/**********************************************************************
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/IconUtils.ts]: The file should be all lowercase for utils

File: packages/renderer/src/lib/ui/IconUtils.spec.ts [hunk 5]
```diff
@@ -0,0 +1,30 @@
+/**********************************************************************
+ * Copyright (C) 2023 Red Hat, Inc.
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/IconUtils.spec.ts]:
```suggestion
 * Copyright (C) 2024 Red Hat, Inc.
```

**Review by benoitf — APPROVED** [review]
looks like we're missing the update in ListItemButtonIcon.svelte

**Comment by benoitf** [comment]
nice enhancement 👍
