### PR TITLE
fix: update current context reactively

### LINKED ISSUE #5053: After switching current kube context, popup is not raised when deleting new current one
### Bug description

When deleting the current kube context, a popup is raised to ask the user to confirm the deletion.

But if the current context is changed to another context, deleting this new context does not raise the popup.

### Operating system

Linux Fedora

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

- go to Settings > Kubernetes
- switch the current context to another context
- delete this new current context

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

On the Kubernetes Context page, the current context is updated reactively, so it has the good value when the suer switches the current context.

### What issues does this PR fix or reference?

Fixes #5053

### CODE REVIEW

File: packages/renderer/src/lib/preferences/PreferencesKubernetesContextsRendering.svelte [hunk 1]
```diff
@@ -2,19 +2,14 @@
...
 import ErrorMessage from '../ui/ErrorMessage.svelte';
 import { kubernetesContexts } from '../../stores/kubernetes-contexts';
 import { clearKubeUIContextErrors, setKubeUIContextError } from '../kube/KubeContextUI';
 
-let currentContextName: string | undefined;
-
-onMount(async () => {
-  currentContextName = await window.kubernetesGetCurrentContextName();
-});
+$: currentContextName = $kubernetesContexts.filter(c => c.currentContext).map(c => c.name)[0];
```
Comment (benoitf) [inline packages/renderer/src/lib/preferences/PreferencesKubernetesContextsRendering.svelte]: what if array is empty ?

Comment (feloy) [reply packages/renderer/src/lib/preferences/PreferencesKubernetesContextsRendering.svelte]: the test I have made indicates the value of `currentContextName` is `undefined`, which is ok

Comment (benoitf) [reply packages/renderer/src/lib/preferences/PreferencesKubernetesContextsRendering.svelte]: what about using instead `find()` method instead that returns the first matching element ?

`$kubernetesContexts.find(c => c.currentContext)?.name`

Comment (benoitf) [reply packages/renderer/src/lib/preferences/PreferencesKubernetesContextsRendering.svelte]: b/c using `[0]` to access the first element of an empty array looks like an error prone case to me

Comment (feloy) [reply packages/renderer/src/lib/preferences/PreferencesKubernetesContextsRendering.svelte:12]: ok, I'll change this to make an explicit check

**Review by benoitf — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]
