### PR TITLE
fix: pass the complete imageInfo to the check function

### LINKED ISSUE #5065: Image checker provider `check` function accepts imageInfo but is passed `image.name`
### Bug description

The definition of the image checker is:

```
  export interface ImageCheckerProvider {
    check(image: ImageInfo, token?: CancellationToken): ProviderResult<ImageChecks>;
  }
```

but the implementation passed the image name only:
```
  contextBridge.exposeInMainWorld(
    'imageCheck',
    async (
      id: string,
      image: string,
      cancellationToken?: number,
    ): Promise<containerDesktopAPI.ImageChecks | undefined> => {
      return ipcInvoke('image-checker:check', id, image, cancellationToken);
    },
  );
```

### Operating system

Linux Fedora

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Passes the complete ImageInfo to the Image Checker's `check` function, instead of the `name` only, as expected by the API

### What issues does this PR fix or reference?

Fixes #5065

### CODE REVIEW

File: packages/renderer/src/lib/image/ImageDetailsCheck.svelte [hunk 1]
```diff
@@ -47,12 +47,15 @@ async function callProviders(_providers: readonly ImageCheckerInfo[]) {
   remainingProviders = providers.length;
 
   providers.forEach(provider => {
+    if (imageInfo === undefined) {
+      return;
+    }
```
Comment (benoitf) [inline packages/renderer/src/lib/image/ImageDetailsCheck.svelte]:
```suggestion
    if (!imageInfo) {
      return;
    }
```

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@feloy FYI there are some unit tests failing

**Review by lstocchi — APPROVED** [review]
