### PR TITLE
fix(renderer): update TroubleshootingPageStore to svelte 5

### LINKED ISSUE #13415: Migrate TroubleshootingPageStore component to Svelte 5
### Bug description

Migrate TroubleshootingPageStore component to Svelte 5

### Operating system

all

### Installation Method

None

### Version

1.19.2

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

fix(renderer): update TroubleshootingPageStore to svelte 5

### What issues does this PR fix or reference?

Fixes #13415 

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/troubleshooting/TroubleshootingPageStore.svelte [hunk 1]
```diff
@@ -18,18 +22,18 @@ async function fetch(): Promise<void> {
   }
 }
 
-let openDetails = false;
+let openDetails = $state(false);
 </script>
 
 <div class="flex flex-col bg-[var(--pd-invert-content-card-bg)] p-2 items-center rounded-sm w-full" role="listitem" aria-label={eventStoreInfo.name}>
-  <div><svelte:component this={eventStoreInfo.iconComponent} size="20" /></div>
```
Comment (axel7083) [inline packages/renderer/src/lib/troubleshooting/TroubleshootingPageStore.svelte:25]: Not related to this PR but this feel a bit hacky to store some icon component in a store?

**Review by axel7083 — APPROVED** [review]
