### PR TITLE
fix: get proxy settings to initialize ImageRegistry

### LINKED ISSUE #7940: Proxy settings not used for extension installation
### Bug description

When doing a custom install of an extension, the proxy settings are not used. They are used only if the user goes to the proxy settings configuration and applies the config again.

### Operating system

Mac

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

- configure the proxy settings with a Squid proxy
- configure the Squid proxy to deny access to everything
- restart Podman Desktop (completely)
- go to Extensions > Custom Install
- Provide an URL of an extension

The installation should fail, but is successful.

### Relevant log output

_No response_

### Additional context

In `ImageRegistry` constructor, the proxySettings are updated when the config changes, but the initial value of the proxy settings are not taken into account

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Get proxy settings when initializing the ImageRegistry instance.

### What issues does this PR fix or reference?

Fixes #7940 

### How to test this PR?

See steps to reproduce in #7940 

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/image-registry.ts [hunk 1]
```diff
@@ -80,6 +80,7 @@ export class ImageRegistry {
     });
 
     this.proxyEnabled = this.proxy.isEnabled();
+    this.proxySettings = this.proxy.proxy;
```
Comment (axel7083) [inline packages/main/src/plugin/image-registry.ts]:
```suggestion
    this.proxyEnabled = this.proxy.isEnabled();
    if(this.proxyEnabled) {
        this.proxySettings = this.proxy.proxy;
    }
```

**Review by axel7083 — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
