### PR TITLE
fix: support for telemetry in a proxy environment

### LINKED ISSUE #3770: Telemetry in a proxy environment
### Bug description

The telemetry module is reporting errors when workstation is using a proxy environment

`index.ts:1506 main ↪️ Telemetry request error: Error: connect EACCES 35.163.144.222:443`

### Operating system

Win10Pro

### Installation Method

Winget (Windows)

### Version

1.3.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #3770

### What does this PR do?

The main part is to switch from the deprecate analytics-node Segment library to the recommended one @segment/analytics-node.
As a side effect, it would bring proxy support as this new library is based on NodeJS fetch which is already linked to Podman Desktop proxy settings.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

#3770 

### How to test this PR?

1. Verify telemetry on Amplitude
2. Setup a proxy environment and verify telemetry on Amplitude and error message is now absent from console

### CODE REVIEW

File: packages/main/src/plugin/index.ts [hunk 1]
```diff
@@ -372,12 +372,12 @@ export class PluginSystem {
     const configurationRegistry = new ConfigurationRegistry(directories);
     configurationRegistry.init();
 
-    const telemetry = new Telemetry(configurationRegistry);
-    await telemetry.init();
-
     const proxy = new Proxy(configurationRegistry);
     await proxy.init();
 
+    const telemetry = new Telemetry(configurationRegistry);
```
Comment (benoitf) [inline packages/main/src/plugin/index.ts]: should we for example add a proxy parameter to Telemetry constructor ? just to ensure that we have a dependency and then nobody move the lines if the order is important

if the order is not important, it means we can keep the current/previous lines ?

File: packages/main/src/plugin/telemetry/telemetry.ts [hunk 2]
```diff
@@ -342,7 +341,8 @@ export class Telemetry {
     };
   }
 
-  protected async getContext(): Promise<unknown> {
+  // eslint-disable-next-line @typescript-eslint/ban-types
+  protected async getContext(): Promise<Object> {
```
Comment (benoitf) [inline packages/main/src/plugin/telemetry/telemetry.ts:349]: unknown doesn't work ?

Comment (jeffmaury) [reply packages/main/src/plugin/telemetry/telemetry.ts:349]: No there was a cast issue reported by Typescript

**Review by benoitf — APPROVED** [review]
maybe merge on monday

**Comment by slemeur** [comment]
tested telemetry events properly received
