### PR TITLE
fix: release notes banner update button

### LINKED ISSUE #9352: Dashboard panel tells to update when there is no update required
### Bug description

Image

Image

Image

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.13.2

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

When clicking the version below, it works as expected
Image

### LINKED ISSUE #9365: podman wants to update to same version
### Bug description

Image

### Operating system

macos silicon

### Installation Method

None

### Version

1.13.0

### Steps to reproduce

got notice about update availalbe - ran it and now podman desktop shows up asking to update v.1.13.2 to v.1.13.2 ...and when clicking update it reports error and to look in dev console.

under thebell icon I have:
`Unable to download v1.13.2 update: Error: Please check update first`

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoniaSandler**
Signed-off-by: Sonia Sandler <ssandler@redhat.com>

### What does this PR do?
Fixes the release notes banner update button bug where the update button still shows up even after updating to the latest release.

### What issues does this PR fix or reference?
Closes https://github.com/containers/podman-desktop/issues/9365
Closes https://github.com/containers/podman-desktop/issues/9352

### How to test this PR?

- [X] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/stores/update-store.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  window.events?.receive('app-update-available', isUpdateAvailable => {
+    if (isUpdateAvailable) {
+      updateAvailable.set(true);
+    } else {
+      updateAvailable.set(false);
+    }
+  });
+
+  return store;
+}
```
Comment (benoitf) [inline packages/renderer/src/stores/update-store.ts]: if we go with a store, it should be like the other one and use the `new EventStore<....>` pattern (where you can add events that you're interested in)

you might look at existing stores importing `EventStore`

File: packages/renderer/src/stores/update-store.ts [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  } else if ('app-update-available' === eventName) {
+    return true;
+  }
+  return false;
+}
+
+const isUpdateAvailable = (...args: unknown[]): Promise<boolean> => {
+  const eventArg = args.length > 0 ? args[0] : false;
+  if (typeof eventArg === 'boolean') {
+    return Promise.resolve(eventArg);
```
Comment (benoitf) [inline packages/renderer/src/stores/update-store.ts]: here we can't use async keyword on the function ?
so we don't need to use Promise resolve but just returning the value ?

Comment (SoniaSandler) [reply packages/renderer/src/stores/update-store.ts]: @benoitf the type of the updater function in `event-store` is `private updater: (...args: unknown[]) => Promise<T>`, so if I don't do the promise resolve is gives me a type error

Comment (benoitf) [reply packages/renderer/src/stores/update-store.ts]: but if you set this function as being 'async' ?

**Review by gastoner — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by SoniaSandler** [comment]
@benoitf just double checking, are the ` onUpdateNotAvailable` and ` onUpdateAvailable` events happen on each start of the app or also only every 12 hours?
In a any case, the ` return this.#updateCheckResult !== undefined && this.#currentVersion !== this.#nextVersion;` check should solve this issue
