### PR TITLE
fix: addressed uninstall version error for kubectl installed via onboard

### LINKED ISSUE #11379: No Version detected error in CLI tools Page when trying to uninstall Kubectl that was installed via onboarding
### Bug description

I am testing a PR for removing cli binaries from system path and I noticed that if I install kubectl via onboarding and then tries to uninstall it from CLI Page, I got `no version detected` error.

This seems very similar to https://github.com/podman-desktop/podman-desktop/issues/9763 which was just referring to compose.

### Operating system

Linux, flatpak

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

See steps to reproduce in linked issue. Except for kubectl.
1. Start up podman desktop with fresh env. (remove `~/.local/share/containers/podman-desktop`) and make sure to wipe out kubectl from system beforehand
2. In global onboarding download kubectl on install it system-wide
3. Go To Cli tools
4. try to uninstall kubectl
5. assert: successfully removed
Actual: error

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bmahabirbu**
### What does this PR do?

This pr addresses the issue of kubectl version not being updated after onboard, which caused a no version detected error when trying to uninstall kubectl in the same session

Thanks to @odockal for linking a similar issue and @dgolovin for reference for a similar fix! In the long run, maybe we should align kubectl and compose extension.ts. Here is the reference PR https://github.com/podman-desktop/podman-desktop/pull/10148

### What issues does this PR fix or reference?

fixes https://github.com/podman-desktop/podman-desktop/issues/11379

### How to test this PR?

Remove kubectl from host to simulate onboarding
i.e for windows 

go to
C:\Users\username\.local\share\containers\podman-desktop\extensions-storage
remove podman-desktop.kubectl-cli

go to
C:\Users\username\AppData\Local\Microsoft\WindowsApps
remove kubectl.exe 

Go to extension settings click on the cog to start the onboard download
Then go to cli settings and uninstall kubectl

Kubectl should be removed without error

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: extensions/kubectl-cli/src/extension.ts [hunk 1]
```diff
@@ -65,9 +65,15 @@ const kubectlCliDisplayName = 'kubectl';
...
 const imageLocation = './icon.png';
 
+let binaryVersion: string | undefined;
+let binaryPath: string | undefined;
+
 export async function activate(extensionContext: extensionApi.ExtensionContext): Promise<void> {
   initTelemetryLogger();
 
+  binaryVersion = undefined;
+  binaryPath = undefined;
```
Comment (cdrage) [inline extensions/kubectl-cli/src/extension.ts]: no need for this? first time I've seen Sorcery AI be useful haha, but I don't think we need to re-initialize these here.

File: extensions/kubectl-cli/src/extension.ts [hunk 2]
```diff
@@ -137,8 +143,16 @@ export async function activate(extensionContext: extensionApi.ExtensionContext):
 
         // We are all done, so we can set the context value to false / downloaded to true
         extensionApi.context.setValue('kubectlIsNotDownloaded', false, 'onboarding');
+        // update the cli version
+        binaryVersion = kubectlVersionMetadata?.tag.slice(1);
```
Comment (cdrage) [inline extensions/kubectl-cli/src/extension.ts]: is the slice(1) reliable enough to not cause issues?

**Review by cdrage — CHANGES_REQUESTED** [review]
Tested this on macOS and it solves the issue, although I was unable to test it on Windows.

There's also missing tests for extension.ts

File: extensions/kubectl-cli/src/extension.ts (hunk 2 above)
Comment (bmahabirbu) [reply extensions/kubectl-cli/src/extension.ts]: Good question! I think it will be ok, as the logic was in the previous version. I only changed how the logic was saved

prev previous 
` kubectlCliTool?.updateVersion({
          version: kubectlVersionMetadata.tag.slice(1),`

File: extensions/kubectl-cli/src/extension.ts (hunk 1 above)
Comment (bmahabirbu) [reply extensions/kubectl-cli/src/extension.ts]: Good catch!

**Comment by bmahabirbu** [comment]
updated PR to fix tests!

File: extensions/kubectl-cli/src/extension.ts [hunk 3]
```diff
@@ -65,9 +65,16 @@ const kubectlCliDisplayName = 'kubectl';
 const kubectlCliDescription = `A command line tool for communicating with a Kubernetes cluster's control plane, using the Kubernetes API.\n\nMore information: [kubernetes.io](https://kubernetes.io/docs/reference/kubectl/)`;
 const imageLocation = './icon.png';
 
+interface KubectlState {
+  version?: string;
+  path?: string;
+}
+
+// State machine for version and path
+export const vp_state: KubectlState = {};
```
Comment (cdrage) [inline extensions/kubectl-cli/src/extension.ts]: Change to using camelCase similar to our other constants :) 

I'm also curious why we set this as a constant, but we do updates such as `vp_state.version = kubectlVersionMetadata?.tag.slice(1);`?

**Review by cdrage — CHANGES_REQUESTED** [review]
Tests pass and I'm able to correctly uninstall.

Thanks for the fixes!

File: extensions/kubectl-cli/src/extension.ts (hunk 3 above)
Comment (bmahabirbu) [reply extensions/kubectl-cli/src/extension.ts]: Thanks Charlie!

**Review by cdrage — APPROVED** [review]
