### PR TITLE
fix: ui freeze when crc activated

### LINKED ISSUE #265: 0.0.5 unusable, can't click anywhere
### Bug description

I just updated to 0.0.5 and can't get to the Images, Containers, or Preferences page anymore. Clicking on the tabs does nothing.

I can see the new welcome page and it appears to work - external links function, clicking to start or using toolbar menu to stop podman seems to work. It doesn't refresh though, e.g. if I start podman I need to wait and restart desktop to see that it has started.

### Operating system

macOS 12.4 M1

### Version

next (development version)

### Steps to reproduce

Just installed 0.0.5 universal image and launched. Using an M1.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vzhukovs**
The problem was in null pointer exception after adding a tile with crc to the welcome page.

fixes https://github.com/containers/podman-desktop/issues/265

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### CODE REVIEW

File: packages/renderer/src/lib/welcome/ProviderLogo.svelte [hunk 1]
```diff
@@ -8,6 +8,8 @@ export let provider: ProviderInfo;
 let logo;
 
 onMount(() => {
+  if (provider.images.logo === undefined) return;
```
Comment (benoitf) [inline packages/renderer/src/lib/welcome/ProviderLogo.svelte]: I would make it part of the next if

If undefined
Else if
Else

**Review by benoitf — APPROVED** [review]

File: packages/renderer/src/lib/welcome/ProviderLogo.svelte (hunk 1 above)
Comment (vzhukovs) [reply packages/renderer/src/lib/welcome/ProviderLogo.svelte]: yep, updated

**Review by benoitf — APPROVED** [review]

**Comment by slemeur** [comment]
Fixes the problem on my side!
Maybe @deboer-tim you can give it a shot?

**Comment by slemeur** [comment]
good work @vzhukovs !

**Comment by deboer-tim** [comment]
Fixes it for me too 👍🏼.
