### PR TITLE
fix: update editor content when pod name changes and disable deploy button when empty (#1319)

### LINKED ISSUE #1319: Kubify: Changing the pod name does not reflect in YAML
### Bug description

When using Pod to Kubernetes, updating the name of the pod does not reflect in the above YAML.

Screenshot 2023-01-31 at 3 40 29 PM

### Operating system

macOS M1

### Version

0.11.0

### Steps to reproduce

1. Kubify a Pod
2. Change the Pod name in the Kubify page
3. Look at the YAML, it doesn't change

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

it updates the editor content when the pod name is hangedby the user

### Screenshot/screencast of this PR

editor-pod-name-update

### What issues does this PR fix or reference?

it fixes #1319 

### How to test this PR?

1. go to the deploy page of a pod
2. update the pod name
3. the editor content should reflect the change made
4. delete everything so that the input box is empty
5. the deploy button should be disabled

### CODE REVIEW

File: packages/renderer/src/lib/editor/MonacoEditor.svelte [hunk 1]
```diff
@@ -54,6 +54,10 @@ onMount(async () => {
     editor.dispose();
   };
 });
+
+export function setContent(content: string) {
```
Comment (benoitf) [inline packages/renderer/src/lib/editor/MonacoEditor.svelte]: I would expect that if exported content variable change, then it's updated. No need to call a setContent method

File: packages/renderer/src/lib/pod/DeployPodToKube.svelte [hunk 2]
```diff
@@ -208,7 +239,7 @@ async function deployToKube() {
       {#if kubeDetails}
         <p>Generated pod to deploy to Kubernetes:</p>
         <div class="h-1/3 pt-2">
-          <MonacoEditor content="{kubeDetails}" language="yaml" />
+          <MonacoEditor bind:this="{editor}" content="{kubeDetails}" language="yaml" />
```
Comment (benoitf) [inline packages/renderer/src/lib/pod/DeployPodToKube.svelte]: Updating kubeDetails should update the value inside the MonacoEditor component, no need to get a reference I would say

Comment (lstocchi) [reply packages/renderer/src/lib/pod/DeployPodToKube.svelte:242]: I guess i tried and it didn't work. I'll verify again. But in this case you only set the content, there is no listener that makes the editor refresh when the value is updated

Comment (lstocchi) [reply packages/renderer/src/lib/pod/DeployPodToKube.svelte]: Can the MonacoEditor content ever be edited manually? If so we should do a two way binding or it can cause some misbehavior.

Comment (lstocchi) [reply packages/renderer/src/lib/pod/DeployPodToKube.svelte]: It's read-only by default so it would be a future issue in case

**Review by cdrage — APPROVED** [review]
I was able to test this and this LGTM. The "flickering" of the screen is a little annoying, but I understand it's rendering the entire YAML again.

**Comment by slemeur** [comment]
@lstocchi : When editing the pod name in the YAML editor, does it also update the name displayed in the form?

**Comment by lstocchi** [comment]
> @lstocchi : When editing the pod name in the YAML editor, does it also update the name displayed in the form?

The YAML editor is read-only, so the name cannot be updated from there

**Comment by slemeur** [comment]
OK got it!

**Review by benoitf — APPROVED** [review]
works as expected 👍 

https://user-images.githubusercontent.com/436777/218479340-faf383d4-99e9-457a-81a0-a2b3026db5c8.mp4
