### PR TITLE
fix: replace backslash with slash so to support rendering on Windows (#3120)

### LINKED ISSUE #3120: Font url not escaped correctly when retrieving the resource in Windows
### Bug description

On Windows the font url gets broken as the backslashes are removed during the rendering.
The font url that is received by the `IconStyle` component is correct
Something like `C://blabla1\\blabla2\\blabla3`
but then during rendering all backslashes are removed resulting in `C://blabla1blabla2blabla3`. Because the url is incorrect you only see an empty rectangle in the UI

icon_broken

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. make an extension contributes an icon on windows
2. you should see an empty rectangle

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR replaces backslashes with slashes when creating the url of a font style.
On Windows backslashes get removed and it results in a wrong url.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

this fixes #3120 

### How to test this PR?

N/A
This is useful for #1899 to work

### CODE REVIEW

File: packages/renderer/src/lib/style/IconsStyle.svelte [hunk 1]
```diff
@@ -19,7 +19,7 @@ function createStyleSheet(): HTMLStyleElement {
 }
 
 export function toUrl(location: string) {
-  return `url('file://${location.replace(/'/g, '%27')}')`;
+  return `url('file://${location.replace(/\\/g, '/').replace(/'/g, '%27')}')`;
```
Comment (benoitf) [inline packages/renderer/src/lib/style/IconsStyle.svelte]: should the location be replaced on the server side ?

Comment (benoitf) [reply packages/renderer/src/lib/style/IconsStyle.svelte]: there: https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/icon-registry.ts#L85-L101

you changed to use join method when checking some file but then probably location should be set properly here ?

Comment (lstocchi) [reply packages/renderer/src/lib/style/IconsStyle.svelte]: the fact is that the path is not wrong and if we change it in the server side it could create other issues if we need to work with it in future (comparing, equals ...) . BTW i didn't have a strong opinion on it so i moved the change on the server side. Only for Windows as it only seems affecting it

Comment (benoitf) [reply packages/renderer/src/lib/style/IconsStyle.svelte]: @lstocchi maybe we can add on server side a new field browserURL and just use that field on the client side ?

Comment (benoitf) [reply packages/renderer/src/lib/style/IconsStyle.svelte]: so we provide both links, one for the 'server', one for the 'client' ?

**Review by benoitf — APPROVED** [review]
works for me but as you suggested, maybe it's better to have two fields instead of one field

File: packages/renderer/src/lib/style/IconsStyle.svelte [hunk 2]
```diff
@@ -46,7 +46,7 @@ onMount(() => {
     });
 
     fontsToAdd.forEach(font => {
-      const src = font.src.map(l => `${toUrl(l.location)} format('${l.format}')`).join(', ');
+      const src = font.src.map(l => `${toUrl(l.browserURL)} format('${l.format}')`).join(', ');
```
Comment (benoitf) [inline packages/renderer/src/lib/style/IconsStyle.svelte]: maybe it means we wouldn't need the toUrl method ?

Comment (lstocchi) [reply packages/renderer/src/lib/style/IconsStyle.svelte]: I thought there was a reason to have `url('file://${location.replace(/'/g, '%27')}')` in the client. Do i move everything in the server?

**Review by cdrage — APPROVED** [review]
Worked for me LGTM!

File: packages/renderer/src/lib/style/IconsStyle.svelte (hunk 2 above)
Comment (benoitf) [reply packages/renderer/src/lib/style/IconsStyle.svelte]: I think that now that we provide the field for the client on the server, we could do everything on the server side so client is dummy, just use the field

**Comment by lstocchi** [comment]
@benoitf updated. Please give it another look

**Review by benoitf — APPROVED** [review]
LGTM but we have a style error:

Strings must use singlequote

**Review by benoitf — APPROVED** [review]
approving again

**Comment by benoitf** [comment]
thanks @lstocchi
