### PR TITLE
fix: Kind clusters not cleaned up when stopping podman machine

### LINKED ISSUE #2143: Kind clusters not cleaned up when stopping podman machine
### Bug description

When I stop the podman machine that's hosting my Kind clusters, they don't get cleaned up. I thought I saw several left one time, but when testing repeatedly there seems to always be one Kind cluster remaining, and it's the one my Kube context points to.

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

Create a couple Kind clusters on podman, then stop the machine. (my Kind clusters were all stopped first, I assume that shouldn't make a difference) I always have one Kind cluster still listed; seems to be whatever is on the Kube context.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2143

### What does this PR do?

Reset/initialize container connections

### Screenshot/screencast of this PR

stop

### What issues does this PR fix or reference?

Fixes #2143 

### How to test this PR?

1. Create a kind cluster
2. Stop the podman machine -> Kind cluster should disappear
3. Restart the podman machine -> Kind cluster should reappear

### CODE REVIEW

File: packages/main/src/plugin/container-registry.ts [hunk 1]
```diff
@@ -174,6 +176,27 @@ export class ContainerProviderRegistry {
...
+          this.apiSender.send('provider-change', {});
+        }
+        if (newStatus === 'started') {
+          internalProvider.api = new Dockerode({ socketPath: containerProviderConnection.endpoint.socketPath });
+          if (containerProviderConnection.type === 'podman') {
+            internalProvider.libpodApi = internalProvider.api as unknown as LibPod;
+          }
+          this.handleEvents(internalProvider.api);
+          this.internalProviders.set(id, internalProvider);
+          this.apiSender.send('provider-change', {});
```
Comment (benoitf) [inline packages/main/src/plugin/container-registry.ts]: with https://github.com/containers/podman-desktop/pull/2938/files you could just call setupConnectionAPI for 90% of these lines

**Review by benoitf — COMMENTED** [review]
probably need to rebase the code

File: packages/main/src/plugin/container-registry.ts [hunk 2]
```diff
@@ -193,6 +195,21 @@ export class ContainerProviderRegistry {
...
+      if (event.providerId === provider.id && event.connection.name === containerProviderConnection.name) {
+        const newStatus = event.status;
+        if (newStatus === 'stopped') {
+          internalProvider.api = undefined;
+          internalProvider.libpodApi = undefined;
+          this.apiSender.send('provider-change', {});
+        }
+        if (newStatus === 'started') {
+          this.setupConnectionAPI(internalProvider, containerProviderConnection);
+        }
```
Comment (benoitf) [inline packages/main/src/plugin/container-registry.ts:252]: before you were using `this.internalProviders.set(id, internalProvider);` should it be kept ?

Comment (jeffmaury) [reply packages/main/src/plugin/container-registry.ts:252]: I remove it because I don't think this is needed

File: extensions/podman/src/extension.ts [hunk 3]
```diff
@@ -426,8 +426,13 @@ async function registerProviderFor(provider: extensionApi.Provider, machineInfo:
       await startMachine(provider, machineInfo, logger);
     },
     stop: async (context, logger): Promise<void> => {
-      await execPromise(getPodmanCli(), ['machine', 'stop', machineInfo.name], { logger });
-      provider.updateStatus('ready');
+      try {
+        await execPromise(getPodmanCli(), ['machine', 'stop', machineInfo.name], { logger });
+      } catch (err: unknown) {
+        console.error(`Error while stopping Podman machine ${err}`);
```
Comment (cdrage) [inline extensions/podman/src/extension.ts]: Error outputs to console, but doesn't go anywhere else? Usually we'd return an error / should we add `throw err` here?

**Review by cdrage — CHANGES_REQUESTED** [review]
One small comment, otherwise LGTM.

Tested (on M1 & Windows) and kind clusters are cleaned up / removed when stopping the podman machine.

File: extensions/podman/src/extension.ts [hunk 4]
```diff
@@ -426,8 +426,13 @@ async function registerProviderFor(provider: extensionApi.Provider, machineInfo:
...
+      } finally {
+        provider.updateStatus('stopped');
```
Comment (lstocchi) [inline extensions/podman/src/extension.ts]: If it fails the status is updated to stopped. Is it correct? Wouldn't it be better to move it inside the try branch?

Comment (jeffmaury) [reply extensions/podman/src/extension.ts]: I put it here because on Windows if you stop the machine when a kind cluster is running you will get a non 0 exit code and it will delay the visual update

File: extensions/podman/src/extension.ts (hunk 3 above)
Comment (jeffmaury) [reply extensions/podman/src/extension.ts]: See https://github.com/containers/podman-desktop/pull/2943#discussion_r1243901076 for the rationale

**Review by cdrage — APPROVED** [review]
Works for me still and LGTM.

May need another test from either @benoitf or @lstocchi before merging.

**Review by lstocchi — COMMENTED** [review]
Just an early comment as I'm investigating. i'm having some issues and idk if it's me or not.

The first is that when i start my podman machine the kind panel is not refreshed, i need to force the refresh myself
kind_not_appear

The second (most annoying) is that after stopping/starting the podman machine, the kind cluster is stopped and if i try to restart it i face an error.
The first time i stop/start, i see my kind cluster running. After stop/start it again, i see the kind cluster stopped and i cannot restart it. I mean i see it running in PD but it's not actually working

error_kind

**Review by benoitf — COMMENTED** [review]
on my side, I've stopped the podman machine and the kind cluster is still displayed as running

image


I just clicked on 'stop' button on the podman machine

**Comment by jeffmaury** [comment]
> on my side, I've stopped the podman machine and the kind cluster is still displayed as running
> 
> image
> 
> I just clicked on 'stop' button on the podman machine

I cannot reproduce on Windows but noticed that the Kind cluster is removed once the Podman machine stop process returns which may take a very long time (returns an error).

image

Will check on MacOS then.

**Comment by benoitf** [comment]
it's taking 1mn30 before it changes the state so I assume there is still something wrong ?

kind extension can detect that the container engine is gone so it should update the state almost immediately.


https://github.com/containers/podman-desktop/assets/436777/851f316f-8023-4946-89bd-dbc145065b22

**Review by benoitf — APPROVED** [review]
tested again and it works as expected 👍 and the delay is very small before the kind cluster is disappearing
