### PR TITLE
chore: fix multiple connection warnings

### LINKED ISSUE #7582: A lot of warnings on load for PreferencesConnectionRendering..
### Bug description

Screenshot 2024-06-11 at 10 04 19 AM

Unsure exactly what's happening, this is happening as well on main.

When loading PD there is a lot of warnings regarding auditing the PreferencesConnectionRendering files.

### Operating system

mac M1

### Installation Method

None

### Version

1.10.2

### Steps to reproduce

`yarn watch` on main branch and open up PD / see console logs.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SoniaSandler**
Signed-off-by: Sonia Sandler <ssandler@redhat.com>

### What does this PR do?
Removes the console warning `The provider does not support audit for connection parameters` that pops up multiple times

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/7582

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

Go to one of the extensions `create new` page in the preferences page and check that the warning mentioned above doesn't pop up

### CODE REVIEW

File: packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte [hunk 1]
```diff
@@ -184,11 +184,7 @@ onMount(async () => {
     }
   }
   if (!connectionInfo) {
-    try {
```
Comment (SoniaSandler) [inline packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte]: I wasn't sure if I should also remove the try catch block in line 215 since it is a bit different. Is there a special case there that I might be missing?

Comment (jeffmaury) [reply packages/renderer/src/lib/preferences/PreferencesConnectionCreationOrEditRendering.svelte]: No you should keep the try / catch as the optional audit method from a provider may throw an exception so we should be protected

**Review by jeffmaury — CHANGES_REQUESTED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM
