### PR TITLE
fix: migrate Input, NumberInput and SearchInput to svelte v5

### LINKED ISSUE #11578: Migrate UI component inputs to Svelte 5
https://github.com/podman-desktop/podman-desktop/blob/ce53e6c5bd49e87ed204b4275510079557f03a92/packages/ui/src/lib/inputs/Input.svelte#L1

https://github.com/podman-desktop/podman-desktop/blob/ce53e6c5bd49e87ed204b4275510079557f03a92/packages/ui/src/lib/inputs/NumberInput.svelte#L1

https://github.com/podman-desktop/podman-desktop/blob/ce53e6c5bd49e87ed204b4275510079557f03a92/packages/ui/src/lib/inputs/SearchInput.svelte#L1

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

This PR migrates components in subject to svelte v5

### What issues does this PR fix or reference?

Fix #11578.

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/ui/src/lib/inputs/NumberInput.svelte [hunk 1]
```diff
@@ -1,28 +1,56 @@
...
+  oninput,
+  onValidation = (_value: number, _error?: string): void => {},
+  class: className = '',
+  'aria-label': ariaLabel,
+  'aria-invalid': ariaInvalid,
+}: Props = $props();
 
 // callback after validation occurs
-export let onValidation = (_value: number, _error?: string): void => {};
+// export let onValidation = (_value: number, _error?: string): void => {};
```
Comment (gastoner) [inline packages/ui/src/lib/inputs/NumberInput.svelte]: To remove?

File: packages/ui/src/lib/inputs/NumberInput.svelte [hunk 2]
```diff
@@ -1,28 +1,56 @@
...
 
-let minimumEnabled: boolean;
-let maximumEnabled: boolean;
-let valueAsString: string | undefined = undefined;
-$: valueAsString = value !== undefined ? String(value) : undefined;
+let minimumEnabled: boolean | undefined = $state();
```
Comment (gastoner) [inline packages/ui/src/lib/inputs/NumberInput.svelte]: Shoudn't be there false as default value?

**Review by gastoner — COMMENTED** [review]
Cant we use props for 
```
export let id: string;
export let password: string | undefined = undefined;
export let passwordHidden: boolean = true;
export let readonly: boolean = false;
```

**Comment by dgolovin** [comment]
> Cant we use props for
> 
> ```
> export let id: string;
> export let password: string | undefined = undefined;
> export let passwordHidden: boolean = true;
> export let readonly: boolean = false;
> ```

The change would be bigger than just props and it is not in the scope of the issue.

File: packages/ui/src/lib/inputs/NumberInput.svelte (hunk 2 above)
Comment (dgolovin) [reply packages/ui/src/lib/inputs/NumberInput.svelte]: I updated it to use $derived().

**Review by gastoner — APPROVED** [review]
Codewise LGTM
