### PR TITLE
fix: allow to show Open DevTools menu items for extensions and webviews

### LINKED ISSUE #8752: Unable to view dev tools for extensions with router.mode.memory()
### Bug description

With the https://github.com/containers/podman-desktop/pull/8489 change, we are now unable to view the dev console for extensions when right-clicking:

Screenshot 2024-09-04 at 10 44 51 AM

Changing this bash to `hash()` works however.

### Operating system

mac m1

### Installation Method

None

### Version

1.11.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

The fix allows to show Open DevTools menu for webviews without checking if webview is loaded. 
If it is not loaded then menu selection does nothing.

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fix #8752

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by feloy — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by benoitf — CHANGES_REQUESTED** [review]
no unit tests

**Review by benoitf — APPROVED** [review]
thanks

File: packages/main/src/mainWindow.ts [hunk 1]
```diff
@@ -23,6 +23,7 @@ import type { BrowserWindowConstructorOptions, Rectangle } from 'electron';
 import { app, autoUpdater, BrowserWindow, ipcMain, nativeTheme, screen } from 'electron';
 import contextMenu from 'electron-context-menu';
 
+import * as developmentItemsMenuBuilder from './development-menu-builder.js';
```
Comment (benoitf) [inline packages/main/src/mainWindow.ts]: can we just import the function ?
