### PR TITLE
fix: create /usr/local/bin directory if it does not exist on binary install

### LINKED ISSUE #3309: Installing docker-compose system wide fails on macOS 13
### Bug description

> Unable to install docker-compose binary: Error: Command failed:
> `cp /Users/krinkle/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/docker-compose /usr/local/bin/docker-compose`
> ```
> cp: /usr/local/bin/docker-compose: No such file or directory
> ```

I assume the reason is that on latest macOS, `/usr/local/bin` no longer exists by default. Having said that, it is still listed in `/etc/paths` and in the default `PATH` variable, so if the directory were to be created first, that should work and would require the same permissions.

### Operating system

macOS 13.4 Ventura

### Installation Method

Installer from website/GitHub releases

### Version

1.2.1

### Steps to reproduce

1. Install.
2. Click "Compose" button.
3. Click "Yes" to installing the binary system-wide.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
fix: create /usr/local/bin directory if it does not exist on binary install

### What does this PR do?

* On macOS and Linux we install the binary to /usr/local/bin. However,
  we do not check to see if it exists or create the directory if it it
  does not exist.
* This PR updates the installBinaryToSystem function to check and create
  the bin directory
* Added tests
* No updates to user UI (this all happens behind the scenes)

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/6422176/d5971702-8aa3-4243-a230-077e53caec0e

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/3309

### How to test this PR?

1. Modify the `localBinDir` const to `/usr/local/bin/foobar` or a random
   test folder that's non-existant
2. "Install" Compose using the normal functionality
3. Check the directory that the binary has been installed.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

File: extensions/compose/src/cli-run.ts [hunk 1]
```diff
@@ -146,10 +148,16 @@ export class CliRun {
...
       command = ['copy', `"${binaryPath}"`, `"${destinationPath}"`];
     } else {
-      destinationPath = path.join('/usr/local/bin', binaryName);
+      destinationPath = path.join(localBinDir, binaryName);
       command = ['cp', binaryPath, destinationPath];
     }
 
+    // If on macOS or Linux, check to see if the /usr/local/bin directory exists,
+    // if it does not, then add mkdir -p /usr/local/bin to the start of the command when moving the binary.
+    if (system === 'linux' || (system === 'darwin' && !fs.existsSync(localBinDir))) {
```
Comment (lstocchi) [inline extensions/compose/src/cli-run.ts]: it works on linux because of the `-p` flag but i wonder why you didn't write as 
```
(system === 'linux' || system === 'darwin') && !fs.existsSync(localBinDir)
```

**Review by lstocchi — APPROVED** [review]
LGTM

File: extensions/compose/src/cli-run.ts (hunk 1 above)
Comment (cdrage) [reply extensions/compose/src/cli-run.ts]: Ahhh good catch. That's totally a mistake there.

**Comment by cdrage** [comment]
Thanks @lstocchi I've updated it with the correct if statement as well as added a test for Linux as well. Good catch! I totally missed that.

**Review by lstocchi — APPROVED** [review]

**Comment by cdrage** [comment]
Rebased + repushed due to #3437 . Now it passes.

**Comment by afbjorklund** [comment]
There is a "typo" in the summary and the commit message is weird (GitHub template?)

/usr/bin/local -> /usr/local/bin

File: extensions/compose/src/cli-run.spec.ts [hunk 2]
```diff
@@ -53,3 +78,81 @@ test('error: expect installBinaryToSystem to fail with a non existing binary', a
   // Expect await installBinaryToSystem to throw an error
   await expect(cliRun.installBinaryToSystem('test', 'tmpBinary')).rejects.toThrowError();
 });
+
+test('success: installBinaryToSystem on mac with /usr/bin/local already created', async () => {
```
Comment (benoitf) [inline extensions/compose/src/cli-run.spec.ts]:
```suggestion
test('success: installBinaryToSystem on mac with /usr/local/bin already created', async () => {
```

File: extensions/compose/src/cli-run.spec.ts [hunk 3]
```diff
@@ -53,3 +78,81 @@ test('error: expect installBinaryToSystem to fail with a non existing binary', a
...
+    expect(options.name).toBe('Binary Installation');
+    expect(command).toBe('cp test /usr/local/bin/tmpBinary');
+    callback(undefined);
+  });
+
+  // Run installBinaryToSystem which will trigger the spyOn mock
+  await cliRun.installBinaryToSystem('test', 'tmpBinary');
+});
+
+test('success: installBinaryToSystem on mac with /usr/bin/local NOT created yet (expect mkdir -p command)', async () => {
```
Comment (benoitf) [inline extensions/compose/src/cli-run.spec.ts]:
```suggestion
test('success: installBinaryToSystem on mac with /usr/local/bin NOT created yet (expect mkdir -p command)', async () => {
```

File: extensions/compose/src/cli-run.spec.ts [hunk 4]
```diff
@@ -53,3 +78,81 @@ test('error: expect installBinaryToSystem to fail with a non existing binary', a
...
+    expect(options.name).toBe('Binary Installation');
+    expect(command).toBe('mkdir -p /usr/local/bin && cp test /usr/local/bin/tmpBinary');
+    callback(undefined);
+  });
+
+  // Run installBinaryToSystem which will trigger the spyOn mock
+  await cliRun.installBinaryToSystem('test', 'tmpBinary');
+});
+
+test('success: installBinaryToSystem on linux with /usr/bin/local NOT created yet (expect mkdir -p command)', async () => {
```
Comment (benoitf) [inline extensions/compose/src/cli-run.spec.ts]:
```suggestion
test('success: installBinaryToSystem on linux with /usr/local/bin NOT created yet (expect mkdir -p command)', async () => {
```

**Review by jeffmaury — APPROVED** [review]
LGTM

Seems fix: rather than feat:

**Comment by cdrage** [comment]
Updated based on commands 💯

**Review by benoitf — APPROVED** [review]
