### PR TITLE
fix: Incorrect pod status

### LINKED ISSUE #2340: Incorrect pod status in Containers view
### Bug description

This is minor, but I have a pod that's degraded (amber) and it shows up with the default/stopped icon in the Containers view. IMHO the same degraded (or whichever) status should be shown.

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

ContainerGroupIcon was just a PodIcon, setting the status to running or stopped based on whether all containers in the group were running or not. Pods have a degraded state where only some of the containers are running.

Instead of trying to make this icon more complicated, this change falls back to directly using the PodIcon and the status of the container group. There are three kinds of groups, with the status now set in container-utils.ts:
- standalone containers - set to the container status
- pods - set to pod status
- compose groups - wait until the group is created, then use the same logic as before

### Screenshot/screencast of this PR

Screenshot 2023-05-08 at 8 21 50 AM

### What issues does this PR fix or reference?

Fixes #2340.

### How to test this PR?

Start a degraded pod (e.g. stop a container, or create a pod where one of the containers won't start) and check the status in the Containers page.

### CODE REVIEW

**Review by cdrage — APPROVED** [review]
Tested this with Compose, unsucessfull-starting pods as well as regular pods.

It all LGTM! Thanks @deboer-tim 

Screenshot 2023-05-08 at 9 58 44 AM

**Review by jeffmaury — COMMENTED** [review]
LGTM

We should have a unit test

File: packages/renderer/src/lib/container/container-utils.ts [hunk 1]
```diff
@@ -181,13 +183,20 @@ export class ContainerUtils {
...
           });
         }
         groups.get(group.name).containers.push(containerInfo);
       }
     });
+
+    for (const group of groups.values()) {
+      if (group.type === ContainerGroupInfoTypeUI.COMPOSE)
+        group.status = group.containers.every(c => c.state === 'RUNNING') ? 'RUNNING' : 'STOPPED';
+    }
```
Comment (benoitf) [inline packages/renderer/src/lib/container/container-utils.ts]: maybe something more in line with javascript iteration:
```suggestion
groups.filter(group => group.type === ContainerGroupInfoTypeUI.COMPOSE).forEach(group => group.status = group.containers.every(c => c.state === 'RUNNING') ? 'RUNNING' : 'STOPPED');
```

Comment (deboer-tim) [reply packages/renderer/src/lib/container/container-utils.ts]: groups is a Map, so there is no filter method. I tried to find something simpler with values() or forEach() but both became more awkward than what's there. Any other ideas?

Comment (benoitf) [reply packages/renderer/src/lib/container/container-utils.ts]: Array.from(map.values()).filter

Comment (deboer-tim) [reply packages/renderer/src/lib/container/container-utils.ts]: That just looks less efficient to old-school me :), but numbers are low enough I know it wouldn't matter either way. It is more consistent, I've pushed the change.

Comment (benoitf) [reply packages/renderer/src/lib/container/container-utils.ts]: I think the pattern is more the iterable/stream/filterable. It's typescript so it could be transformed to something more efficient maybe but here we read something only with a single pipe


you can also keep your pattern, it was just a suggestion.

**Review by benoitf — APPROVED** [review]
