### PR TITLE
fix: clean up electron-updater cache when it is not needed anymore

### LINKED ISSUE #8488: Updater to 1.12.0 doesn't update, and updater doesn't cleanup 301MB installer
### Bug description

This updater popup does nothing, after clicking on "Update now" Podman Desktop only **exits**. Starting it launches previous version, and the same popup is displayed.

image

`%localappdata%\podman-desktop-updater\pending` is empty
`%localappdata%\podman-desktop-updater\installer.exe` has version 1.11.1
Btw. can you explain, why is there a 301MB installer on my drive? Please also consider this as part of this issue. Updater must perform cleanup after it's finished.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.11.1

### Steps to reproduce

_No response_

### Relevant log output

```shell
main ↪️ Kubeconfig path C:\Users\User\.kube\config provided does not exist. Skipping.
main ↪️ Starting http server to handle webviews on port 44000
main ↪️ System ready. Loading extensions...
main ↪️ Activating extension (podman-desktop.compose) with max activation time of 20 seconds
main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 105.9197999999999ms
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-started listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extension-stopped listeners added. Use emitter.setMaxListeners() to increase limit
main ↪️ PluginSystem: received dom-ready event from the UI
main ↪️ Delayed startup, flushing 8 events
main ↪️ Activating extension (podman-desktop.compose) ended in 302 milliseconds
main ↪️ Activating extension (podman-desktop.docker) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.docker) ended in 5 milliseconds
main ↪️ Activating extension (podman-desktop.kind) with max activation time of 20 seconds
main ↪️ [compose] Error getting compose version: Error: Failed to execute command: spawn C:\Users\User\.local\share\containers\podman-desktop\extensions-storage\podman-desktop.compose\bin\docker-compose.exe ENOENT
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ [kind] Error: Failed to execute command: spawn kind-windows-amd64 ENOENT
main ↪️ Activating extension (podman-desktop.kind) ended in 707 milliseconds
main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 20 seconds
main ↪️ [kube-context] starting extension kube-context
main ↪️ Activating extension (podman-desktop.kube-context) ended in 2 milliseconds
main ↪️ Activating extension (podman-desktop.kubectl-cli) with max activation time of 20 seconds
main ↪️ event is [object Object]
main ↪️ Activating extension (podman-desktop.kubectl-cli) ended in 318 milliseconds
main ↪️ Activating extension (podman-desktop.lima) with max activation time of 20 seconds
main ↪️ [lima] Could not find socket at C:\Users\User\.lima\podman\sock\podman.sock
main ↪️ Activating extension (podman-desktop.lima) ended in 3 milliseconds
main ↪️ Activating extension (podman-desktop.podman) with max activation time of 20 seconds
main ↪️ [podman] Can't get machine podman-machine-default resource usage error Error: no engine matching this container
main ↪️ [podman] Unable to run regex on containers.conf file. Reason: Error: ENOENT: no such file or directory, open 'C:\Users\User\AppData\Roaming\containers\containers.conf'
main ↪️ Activating extension (podman-desktop.podman) ended in 1377 milliseconds
main ↪️ Activating extension (podman-desktop.registries) with max activation time of 20 seconds
main ↪️ Activating extension (podman-desktop.registries) ended in 1 milliseconds
main ↪️ PluginSystem: initialization done.
main ↪️ Autostarting podman-desktop.podman container engine
main ↪️ [podman] Podman extension: Do not start a machine as there is already one starting or started
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
main ↪️ event is [object Object]
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

On Windows and Linux update leaves two files behind in podman-desktop-updater folder. This PR adds removal of that folder in when updater emits 'update-not-available' event which happens during first start after update.

### What issues does this PR fix or reference?

Fix #8488.
There is no need to fix 'Updater does not update' part, because it cannot be replicated anymore.

### How to test this PR?

1. Pull the branch
2. Update podman-desktop version in package.json to the latest release available form github.com
3. Build installer using `pnpm compile:next`
4. Check if you have electron updater cache folder already, for macos - `$HOME/Library/Application Support/Caches/podman-desktop-updater`, for windows - `$LOCALAPPDATA/podman-desktop-updater`
5. If podman-desktop-updater folder does not exists create it manually or install any of the earlier versions of podman-desktop and then install update.
6. Install podman-desktop built on step (3) above from ./dist folder
7. Start it
8. Wait for version to appear in status bar and check if podman-desktop-updater folder from step (4) does not exists.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/updater.ts [hunk 1]
```diff
@@ -350,6 +352,20 @@ export class Updater {
     // Update the 'version' entry in the status bar to show that no update is available
     this.defaultVersionEntry();
     this.apiSender.send('app-update-available', false);
+
+    // Remove the Electron updater cache folder
+    if (isMac() || isWindows()) {
+      const cacheDir: string = isWindows()
+        ? path.join(process.env['LOCALAPPDATA'] ?? '', 'podman-desktop-updater')
+        : path.join(app.getPath('home'), 'Library/Application Support/Caches/podman-desktop-updater');
```
Comment (axel7083) [inline packages/main/src/plugin/updater.ts]: We should probably use [app.getPath("appData")](https://github.com/electron/electron/blob/main/docs/api/app.md#appgetpathname) for both windows and mac, instead of reading of process.env

**Review by axel7083 — COMMENTED** [review]
I am questioning if this should not be an upstream issue.

I was looking at a better way to get the cache folder from their code, and I wonder if we should not make an upstream issue, asking them to expose a `cleanCache`, or something similar, they do not expose a nice way to get the cache directory.

We could still force it using the following import

```ts
import { getAppCacheDir } from 'electron-updater/out/AppAdapter.js';

getAppCacheDir();
```

The code resize is the [AppAdapter](https://github.com/electron-userland/electron-builder/blob/3aa20b3717fae4cd9b67301ce73bddb1f5e9bb73/packages/electron-updater/src/AppAdapter.ts#L34) file.

But, yet, I would rather have an upstream issue, and use this as a temporary solution

File: packages/main/src/plugin/updater.ts (hunk 1 above)
Comment (dgolovin) [reply packages/main/src/plugin/updater.ts]: I checked it and it is pointing to different location on both windows and macOS.
I can use relative path from 'userData' folder.

**Comment by dgolovin** [comment]
PR is updated to use `getAppCacheDir`.

File: packages/main/src/plugin/updater.ts [hunk 2]
```diff
@@ -26,6 +27,7 @@ import {
   type UpdateDownloadedEvent,
   type UpdateInfo,
 } from 'electron-updater';
+import * as appAdapter from 'electron-updater/out/AppAdapter.js';
```
Comment (axel7083) [inline packages/main/src/plugin/updater.ts]: question: why importing the all package?

```suggestion
import { getAppCacheDir } from 'electron-updater/out/AppAdapter.js';
```

importing using `*` prevent tree shaking, moreover only importing why we need improve the clarity, as we better understand what is needed from a specific package/file

**Review by axel7083 — APPROVED** [review]

**Review by cdrage — APPROVED** [review]
After following the steps (on macOS) the updater cache folder was successfully deleted.

Codewise and implementation LGTM!
