### PR TITLE
fix: extensions cannot be installed on symlinked folders

### LINKED ISSUE #7601: Plugins - Podman AI Lab extension, Bootable Container extension - Fail on Fedora Silverblue 40 (homedir is a symlink)
### Bug description

When trying to install and use the plugins,
Bootable Container extension
Podman AI Lab extension

They fail with a stacktrace

### Operating system

Fedora Silverblue 40

### Installation Method

Flathub (Linux)

### Version

1.10.2

### Steps to reproduce

Install podman-desktop as a flatpak on a Fedora Silverblue system
Install Podman AI Lab extension and/or Bootable Container extension

### Relevant log output

```shell
Error: Cannot find extension for /var/home/jwesterl/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionbootc/dist
Stack trace:
Error: Cannot find extension for /var/home/jwesterl/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionbootc/dist
    at _module._load (/app/main/resources/app.asar/packages/main/dist/index.cjs:146:33696)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at Module.<anonymous> (/var/home/jwesterl/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionbootc/dist/extension.js:5:22)
    at Module._compile (node:internal/modules/cjs/loader:1391:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1451:10)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at _module._load (/app/main/resources/app.asar/packages/main/dist/index.cjs:146:33447)
```

### Additional context

On silverblue /home is a symlink to /var/home
It might be relevant

ls -al /home
lrwxrwxrwx. 1 root root 9 Jun 12 11:42 /home -> /var/home

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #7601

### What does this PR do?

Resolves extension folder as node does it and thus loading then failed if the folder is not resolved

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#7601 

### How to test this PR?

Test on a Linux distro that have $HOME as a symlink (Fedora Silverblue or Kinoite)

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/extension-loader.ts [hunk 1]
```diff
@@ -429,6 +429,7 @@ export class ExtensionLoader {
   }
 
   async analyzeExtension(extensionPath: string, removable: boolean): Promise<AnalyzedExtension> {
+    extensionPath = await realpath(extensionPath);
```
Comment (benoitf) [inline packages/main/src/plugin/extension-loader.ts]: I would rename extensionPath of the parameter (to be sure we don't modify the parameter)

**Review by benoitf — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
