### PR TITLE
fix: hide cpu, memory, size sliders on WSL

### LINKED ISSUE #2558: Windows podman machine creation does not respect number of CPUs choosen
### Bug description

On windows, I am creating new podman machine and choose ie. 4 CPUs. When the machine is created there is 8 CPUs.
Same result can be observed when I check the command line `podman mahcine ls`.

When I try to create a machine on cli, the result is the same, so I would sum this up to be upstream issue. I have not found this issue here, so I will fill it in anyway.

 

### Operating system

Windows 10

### Version

1.0.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

It hides the cpu, memory, size sliders on WSL as they are meaningless.

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

it resolves #2558 

### How to test this PR?

1. try to create a new machine on WSL, you should not see the cpu, memory, size sliders

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
Working fine on my computer (windows) LGTM

File: extensions/podman/src/podman-configuration.ts [hunk 1]
```diff
@@ -203,6 +203,16 @@ export class PodmanConfiguration {
     }
   }
 
+  async isValueInContainersConfig(regex: RegExp): Promise<boolean> {
```
Comment (benoitf) [inline extensions/podman/src/podman-configuration.ts]: maybe use `match` like `matchContainersConfig` or `matchRegexpInContainersConfig`

File: extensions/podman/src/podman-configuration.ts [hunk 2]
```diff
@@ -203,6 +203,16 @@ export class PodmanConfiguration {
...
+    try {
+      const containerConf = await this.readContainersConfigFile();
+      return regex.test(containerConf);
+    } catch (e) {
+      console.log(String(e));
```
Comment (benoitf) [inline extensions/podman/src/podman-configuration.ts]: I think it's missing a bit of context in the log message

Comment (benoitf) [reply extensions/podman/src/podman-configuration.ts]: also is it log or debug or warn or error ?

File: extensions/podman/package.json [hunk 3]
```diff
@@ -113,7 +113,8 @@
           "minimum": 1,
           "maximum": "HOST_TOTAL_CPU",
           "scope": "ContainerProviderConnectionFactory",
-          "description": "CPU(s)"
+          "description": "CPU(s)",
+          "when": "!isWindows || !podman.isWSL"
```
Comment (benoitf) [inline extensions/podman/package.json]: do we need to replicate in 3 different places the condition or we introduce direct flags like
```
"when": "podmanMachineCpuSupported"
"when": "podmanMachineDiskSupported"
"when": "podmanMachineMemorySupported"
```

Comment (lstocchi) [reply extensions/podman/package.json]: I don't get what you're saying. It is already replicated in three places. Do you prefer direct flags?

Comment (benoitf) [reply extensions/podman/package.json]: I mean, it was to avoid such complex conditions as we handle both the package.json and the condition in our case.

so I don't know if we need to put all the logic inside the package.json file or just make it working in the code (as it's more tested)

**Review by benoitf — APPROVED** [review]
I think it's a matter of taste if enablement is using 'internal' properties or do the logic.

I would be in favor of a single custom property as we can have unit tests that we don't have well in the package.json enablement but it's not a required for changes

**Comment by lstocchi** [comment]
@benoitf updated with custom properties

**Review by benoitf — APPROVED** [review]
thx
