### PR TITLE
chore: fix svelte checks

### LINKED ISSUE #3665: some typescript errors are not reported in PR checks
### Bug description

There are some .ts files in renderer part that have invalid typescript but no PR check is reporting the error

### Operating system

macOS

### Installation Method

None

### Version

1.3.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Turn on the strict mode in tsconfig.json
650errors were reported, trying to target all of them

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/3665

### How to test this PR?

Test lot of use-cases, pages

### CODE REVIEW

File: packages/renderer/src/lib/dialogs/QuickPickInput.svelte [hunk 1]
```diff
@@ -29,58 +29,71 @@ let quickPickSelectedIndex = 0;
...
+        };
+      }
+    })
+    .filter(item => item !== undefined) as {
+    value: any;
+    description: string;
+    detail: string;
+    checkbox: boolean;
+  }[];
+
```
Comment (dgolovin) [inline packages/renderer/src/lib/dialogs/QuickPickInput.svelte:89]: Filter is not required, because both branches of if return values and using default empty array eliminates `as` statement.
```suggestion
  quickPickItems = (options?.items || <QuickPickItem[] | string[]>[])
    .map(item => {
      if (typeof item === 'string') {
        return { value: item, description: '', detail: '', checkbox: false };
      } else {
        // if type is QuickPickItem use label field for the display
        return {
          value: item.label || '',
          description: item.description || '',
          detail: item.detail || '',
          checkbox: false,
        };
      }
    });

```

File: packages/renderer/src/lib/preferences/PreferencesProviderRendering.svelte [hunk 2]
```diff
@@ -50,14 +50,20 @@ async function stopProvider(): Promise<void> {
   window.dispatchEvent(new CustomEvent('provider-lifecycle-change'));
 }
 
-async function startReceivingLogs(provider: ProviderInfo): Promise<void> {
+async function startReceivingLogs(provider: ProviderInfo | undefined): Promise<void> {
+  if (!provider) {
```
Comment (dgolovin) [inline packages/renderer/src/lib/preferences/PreferencesProviderRendering.svelte:54]: This is highly suspicious code that will cover up programming errors rather than helping to avoid them in a first place.

To avoid this check and similar in stopRecievingLogs method both methods should be called with `providerInfo` which cannot be `undefined` rater than with `showModal`.

File: packages/renderer/src/lib/pod/PodCreateFromContainers.svelte [hunk 3]
```diff
@@ -74,8 +80,9 @@ async function doCreatePodFromContainers() {
       portmapping =>
         portmapping !== undefined &&
         mapPortExposed.has(portmapping.host_port) &&
-        mapPortExposed.get(portmapping.host_port).exposed,
-    );
+        mapPortExposed.get(portmapping.host_port)?.exposed,
+    )
+    .filter(item => item !== undefined) as PodCreatePortOptions[];
```
Comment (dgolovin) [inline packages/renderer/src/lib/pod/PodCreateFromContainers.svelte:85]: map call should be changed to reduce to avoid filtering and type conversion.

**Review by dgolovin — APPROVED** [review]
I noticed couple minor issues, but those are not blocking to merge.

**Comment by benoitf** [comment]
I'll merge and come back with a follow-up PR (much more smaller) as more than 600+ issues are fixed and a lot of files are changed
