### PR TITLE
fix: building image without name should have a correct task title

### LINKED ISSUE #10078: Building undefined
### Bug description

If you go to build an image and select a containerfile, you can click Build without entering a name. This results in a task called 'Building undefined'. We should fix the name, or block building until you enter a name.

### Operating system

macOS 15.1

### Installation Method

None

### Version

1.14.1

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #10078

### What does this PR do?

Ensure the task title is correct if no image name is given

### Screenshot / video of UI

unamed

### How to test this PR?

1. Build an image without the image name
2. Check the task title

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by dgolovin — CHANGES_REQUESTED** [review]
There is another occurrence of 'undefined'. It is in the build log.

image

File: packages/main/src/plugin/index.ts [hunk 1]
```diff
@@ -1289,7 +1289,7 @@ export class PluginSystem {
       ): Promise<unknown> => {
         // create task
         const task = taskManager.createTask({
-          title: `Building ${imageName}`,
+          title: `Building ${imageName ?? 'unnamed image'}`,
```
Comment (dgolovin) [inline packages/main/src/plugin/index.ts]: IMO: `Building image` better that `Building unnamed image`
```suggestion
          title: `Building image ${imageName ?? ''}`,
```

**Review by gastoner — APPROVED** [review]
image
On Windows

**Review by dgolovin — APPROVED** [review]
