### PR TITLE
fix: avoid blinking for modal pages of image lists

### LINKED ISSUE #314: Dialog "Create container from image" blinks when cursor is moving
### Bug description

When trying to run an image and create a container from it the opened dialog doesn't work as expected. It starts blinking when the mouse cursor is moved and it is difficult to select the textbox/button.

### Operating system

fedora 33

### Version

0.0.5

### Steps to reproduce

1. Go to the images list
2. Click on run image 
3. the dialog opens up but it cannot be easily selected as it starts blinking when the mouse cursor is moved

Have a problem with the gif creation tool as it doesn't actually show the mouse cursor but i only move it after clicking on run image. 
podman-blink

### Relevant log output

_No response_

### Additional context

It seems the problem arises if the image is in a top position. If i try to run an image which is at the bottom of the list it works better.

### PR DESCRIPTION
**Pull request by benoitf**
Fixes https://github.com/containers/podman-desktop/issues/314
move modal element from the hover element as when moving
the mouse to another line, it's hiding/showing modal

also move Modal element inside the Modal svelte component rather
than using Modal on the callee/consumer

Change-Id: I38c0a770e665014b4446cd5d104d0a9115246300
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

File: packages/renderer/src/lib/image/PushImageModal.svelte [hunk 1]
```diff
@@ -109,75 +108,81 @@ function callback(name: string, data: string) {
...
+              data-modal-toggle="authentication-modal">
+              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"
+                ><path
+                  fill-rule="evenodd"
+                  d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
+                  clip-rule="evenodd"></path
+                ></svg>
+            </button>
+          </div>
+          <!--<form class="px-6 pb-4 space-y-6 lg:px-8 sm:pb-6 xl:pb-8">-->
```
Comment (vzhukovs) [inline packages/renderer/src/lib/image/PushImageModal.svelte]: I suppose, we can remove this commented code, as far as it redundant now

**Review by vzhukovs — APPROVED** [review]

File: packages/renderer/src/lib/image/PushImageModal.svelte (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/lib/image/PushImageModal.svelte]: yes, I can add code cleanup on that part

Comment (benoitf) [reply packages/renderer/src/lib/image/PushImageModal.svelte]: done
