### PR TITLE
nit: add notification after pushing kind image

### LINKED ISSUE #2166: No feedback from 'Push image to Kind', and fails
### Bug description

Going to an image and selecting `Push image to Kind cluster` provides zero feedback. It should probably use the task manager (which I know is not available to extensions yet).

If I have more than one Kind cluster, it's not clear which it would act on. Probably needs a selection or prompt.

In my case I was able to confirm it was doing _something_ via log events, but it looks like it does a save and then fails on an exec against Kind.

### Operating system

macOS 13.3 M1

### Version

0.14.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
nit: add notification after pushing kind image

### What does this PR do?

* Changes confirmation to show information message, not
  notification.
* Refactors function a bit to give more details when erroring /
  reorganize

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Part of https://github.com/containers/podman-desktop/issues/2231
Closes https://github.com/containers/podman-desktop/issues/2166

Helps create some logging / information to diagnose / make it reproduceable.

### How to test this PR?

Push image to Kind cluster, should function as normal but give dialog
after.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

File: extensions/kind/src/image-handler.ts [hunk 1]
```diff
@@ -43,33 +50,55 @@ export class ImageHandler {
...
-          body: `Image ${image.name} pushed to Kind cluster ${selectedCluster.label}`,
-        });
-      } catch (error) {
-        const errorMessage = error instanceof Error ? error.message : '' + error;
-        throw new Error(
-          `Error while pushing image ${image.name} to Kind cluster ${selectedCluster.label}: ${errorMessage}`,
+
+        // Show a dialog to the user that the image was pushed
+        // TODO: Change this to taskbar notification when implemented
+        await extensionApi.window.showInformationMessage(
```
Comment (jeffmaury) [inline extensions/kind/src/image-handler.ts]: Are all async tasks going to show a message now ? @mairin WDYT ?

**Review by jeffmaury — COMMENTED** [review]
Does it fixes the issue @praveenkumar is having ?

File: extensions/kind/src/image-handler.ts (hunk 1 above)
Comment (mairin) [reply extensions/kind/src/image-handler.ts]: @jeffmaury Ideally it'd be a taskbar notice instead of a dialog (the comment indicates that too). But yeh I think all async tasks should be in the task notification area. Does that make sense?

**Comment by cdrage** [comment]
> Does it fixes the issue @praveenkumar is having ?

It doesnt, but adds more information as I'm unable to reproduce, as well as give a confirmation that it ends.

For @mairin 's question, taskbar isn't available through the podman api yet, so that's why we are using dialog instead.

**Review by jeffmaury — APPROVED** [review]
LGTM
