### PR TITLE
fix: number widget should accept float value for number type

### LINKED ISSUE #8663: number item widget is not allowing float values
### Bug description

when specifying the schema value of a configuration we can choose between integer and number

if integer then it should be 1 or 1.0 (only .0 is allowed) and for number it can be anything

but the widget is not letting us enter the `.` key

### Operating system

macOS

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

try to define a value with number value and try like `1.5`. You won't see the . being displayed and you can either enter 1 or 15 but . is not being accepted

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
The widget Number should handle both integer and number values and validate the values as it's expected from JSON schema

Integer for example 1 and 1.0 are accepted
number: 1, 3.14 etc are valid

Today we can't use `.` character at all

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/8663

### How to test this PR?

set/edit the type of a property to `integer` or `number` and check that you can use the `.` key and only `.0` for integers

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by gastoner — APPROVED** [review]

**Review by gastoner — APPROVED** [review]
Tested on this, but this is probably not related to this PR right? (Windows)
image

**Comment by benoitf** [comment]
@gastoner https://github.com/containers/podman-desktop/issues/8648

File: packages/renderer/src/lib/ui/NumberInput.svelte [hunk 1]
```diff
@@ -30,7 +31,20 @@ function validateNumber() {
 }
 
 function onKeyPress(event: any) {
-  if (isNaN(Number(event.key))) {
+  // if type is integer it means we can only accept nu
```
Comment (feloy) [inline packages/renderer/src/lib/ui/NumberInput.svelte]: >   // if type is integer it means we can only accept nu
Is the sentence complete?

File: packages/renderer/src/lib/ui/NumberInput.svelte [hunk 2]
```diff
@@ -30,7 +31,20 @@ function validateNumber() {
...
+  // see https://json-schema.org/understanding-json-schema/reference/numeric
+  // Numbers with a zero fractional part are considered integers
+
+  // first, add the new character to the extisting value
+  const wantedValue = `${value}${event.key}`;
```
Comment (feloy) [inline packages/renderer/src/lib/ui/NumberInput.svelte]: The problem is that the test is done with the character added at the end, but the user can have placed the cursor anywhere.

For example for an integer input, if the input contains `12` and the cursor is between `1` and `2` and the user types `.`,  the character is accepted (because `12.` is considered as an integer), but the input contains `1.2` which is not an integer.

File: packages/renderer/src/lib/ui/NumberInput.svelte (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/lib/ui/NumberInput.svelte]: fixed

File: packages/renderer/src/lib/ui/NumberInput.svelte (hunk 2 above)
Comment (benoitf) [reply packages/renderer/src/lib/ui/NumberInput.svelte]: fixed

**Comment by benoitf** [comment]
@feloy good catch, should be fixed now (test added also)

File: packages/renderer/src/lib/ui/NumberInput.svelte (hunk 2 above)
Comment (feloy) [reply packages/renderer/src/lib/ui/NumberInput.svelte]: Nice fix . Don't forget to remove the debug logs

**Review by feloy — APPROVED** [review]

File: packages/renderer/src/lib/ui/NumberInput.svelte (hunk 2 above)
Comment (benoitf) [reply packages/renderer/src/lib/ui/NumberInput.svelte]: fixed
