### PR TITLE
fix: remove redundant step completion check when onboarding gets started (#3783)

### LINKED ISSUE #3783: Onboarding bug: Podman onboarding flickers & exits
### Bug description

https://github.com/containers/podman-desktop/assets/6422176/404abf95-8232-4ccb-a092-4f9b8a47a1eb

When pressing the setup button, the "Check for Podman Installation" screen briefly flickers and then onboarding exits.

### Operating system

mac M1

### Installation Method

None

### Version

1.3.1

### Steps to reproduce

1. Have a working podman installation with no errors
2. Click on onboarding button

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR removes a redundant step completion check when the onboarding gets started.

So basically what happens that causes https://github.com/containers/podman-desktop/issues/3783 is:

onboarding gets started -> it loops over all steps to find the one to display -> podman is already installed so the final step with the when clause `podmanIsInstalled` is picked -> another check on the step is executed and bc the step is the last one and completed the user is redirected to the resources page.

There is no need to check if the step is completed for the second time because the check is already performed during the selection of the step to display.

This fixes the behavior to ... you already completed the setup (installed podman, created a machine, started it) and click on the onboarding again? You see the last page with the setup success message or with some other message that we add

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

it fixes #3783 

### How to test this PR?

1. run the onboarding
2. complete it
3. run it again, you should end up to the last page (atm it's the "Podman successfully installed" step)

### CODE REVIEW

**Review by cdrage — APPROVED** [review]
LGTM! Fixes the issue and unblocks onboarding development.


https://github.com/containers/podman-desktop/assets/6422176/8656492b-4946-4f4b-b14a-8e4fb7298bf4

File: packages/renderer/src/lib/onboarding/Onboarding.svelte [hunk 1]
```diff
@@ -51,35 +50,19 @@ onMount(async () => {
...
-      if (isStartedByMe) {
-        firstStart = false;
-        await assertStepCompleted();
-        return;
-      }
-    }
-    if (!firstStart) {
-      await assertStepCompleted();
-    }
+    startOnboarding();
```
Comment (benoitf) [inline packages/renderer/src/lib/onboarding/Onboarding.svelte]: I think we need to catch the error on a promise if we don't await for it.

Comment (benoitf) [reply packages/renderer/src/lib/onboarding/Onboarding.svelte]: the rule is still disabled as for some times linter was not parsing svelte files but as we're getting rid of these exclusions, it should be enabled soon (@typescript-eslint/no-floating-promises)

Comment (lstocchi) [reply packages/renderer/src/lib/onboarding/Onboarding.svelte]: done

**Review by benoitf — APPROVED** [review]
