### PR TITLE
fix: set proxy env variable when launching process

### LINKED ISSUE #3768: Cannot create a Podman machine in a proxy environment
### Bug description

When connected through proxy, the Podman machine cannot be created as the image file cannot be fetched:

image

### Operating system

Win10Pro

### Installation Method

Winget (Windows)

### Version

1.3.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #3768

### What does this PR do?

Set the proxy environment variables when launching process using the extension API

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixes #3768 

### How to test this PR?

1. Create a proxy environment (install proxy, no network access outside proxy)
2. Configure proxy in Podman Desktop
3. Remove cached Podman machine images ($HOME/.local/share/containers/podman/machine/wsl on Windows)
4. Create a Podman machine, make sure image is downloaded through the proxy

### CODE REVIEW

File: packages/main/src/plugin/util/exec.ts [hunk 1]
```diff
@@ -20,16 +20,29 @@ import type { ChildProcessWithoutNullStreams } from 'child_process';
...
+      env.HTTPS_PROXY = 'http://' + proxy.proxy.httpsProxy;
+    }
+    if (proxy.proxy?.httpProxy) {
+      env.HTTP_PROXY = 'http://' + proxy.proxy.httpProxy;
+    }
+    if (proxy.proxy?.noProxy) {
+      env.NO_PROXY = proxy.proxy.noProxy;
+    }
+  }
+
```
Comment (benoitf) [inline packages/main/src/plugin/util/exec.ts]: it means that if extension is setting a proxy data, it'll be replaced all the times by Podman Desktop ?

File: packages/main/src/plugin/util/exec.ts [hunk 2]
```diff
@@ -20,16 +20,29 @@ import type { ChildProcessWithoutNullStreams } from 'child_process';
 import { spawn } from 'child_process';
 import type { RunError, RunOptions, RunResult } from '@podman-desktop/api';
 import { isMac, isWindows } from '../../util.js';
+import type { Proxy } from '../proxy.js';
 
 export const macosExtraPath = '/usr/local/bin:/opt/homebrew/bin:/opt/local/bin:/opt/podman/bin';
 
-export function exec(command: string, args?: string[], options?: RunOptions): Promise<RunResult> {
+export function exec(command: string, proxy: Proxy, args?: string[], options?: RunOptions): Promise<RunResult> {
```
Comment (benoitf) [inline packages/main/src/plugin/util/exec.ts]: When I was wondering if proxy was placed at the right order it let me think that proxy is a global parameter and not a 'per call parameter'

so I think it might be better to replace the utility function exec by a constructor/class/object

like somewhere in plugins:

```
const executor = new Executor(proxy);
```

and when we invoke we just use
```
executor.exec(command, args, options);
```

so we don't need to pass Proxy to contribution manager and extension loader, but we give a reference to the exec handler
Only Exec has a direct dependency to proxy

File: packages/main/src/plugin/util/exec.ts [hunk 3]
```diff
@@ -20,16 +20,29 @@ import type { ChildProcessWithoutNullStreams } from 'child_process';
...
   let env = Object.assign({}, process.env);
 
   if (options?.env) {
     env = Object.assign(env, options.env);
   }
 
+  if (proxy.isEnabled()) {
+    if (proxy.proxy?.httpsProxy) {
+      env.HTTPS_PROXY = 'http://' + proxy.proxy.httpsProxy;
```
Comment (benoitf) [inline packages/main/src/plugin/util/exec.ts]: might use the template literals  like
```suggestion
      env.HTTPS_PROXY = `http://${proxy.proxy.httpsProxy}`;
```

File: packages/main/src/plugin/util/exec.ts (hunk 1 above)
Comment (jeffmaury) [reply packages/main/src/plugin/util/exec.ts]: Yes I don't see the use case

**Review by benoitf — APPROVED** [review]
LGTM code wise

**Review by lstocchi — APPROVED** [review]
LGTM
