### PR TITLE
fix: display an error to the user using uppercase in image name

### LINKED ISSUE #10077: Building image with a capital in the name hangs
### Bug description

I inadvertently called an image 'gpuTest' when building, and it causes the build to hang for 5 minutes before erroring out because capitals are not allowed in repo names. We should validate for this, or fail fast.

### Operating system

macOS 15.1

### Installation Method

None

### Version

1.14.1

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

Displays an error to the user using uppercase in image name

### Screenshot / video of UI

Screenshot 2025-07-08 at 11 17 12

### What issues does this PR fix or reference?

Fixes #10077

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte [hunk 1]
```diff
@@ -374,6 +379,7 @@ let hasInvalidFields = $derived(
           name="containerImageName"
           id="containerImageName"
           placeholder="Image name (e.g. quay.io/namespace/my-custom-image)"
+          error={isImageNameLowercase ? void 0 : 'Image name should be lowercase'}
```
Comment (benoitf) [inline packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]:
```suggestion
          error={isImageNameLowercase ? undefined : 'Image name should be lowercase'}
```

Comment (simonrey1) [reply packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: I can do this change but I was wondering whether the `no-undefined` rule of ESLint would be relevant in this project ([https://eslint.org/docs/latest/rules/no-undefined](https://eslint.org/docs/latest/rules/no-undefined))

Comment (benoitf) [reply packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: we're using undefined everywhere (as default value if not defined)

but this project disable the usage of `null`

File: packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte [hunk 2]
```diff
@@ -323,11 +323,16 @@ $effect(() => {
   }
   buildImageInfo.selectedProvider = selectedProvider;
 });
+
+let isImageNameLowercase = $derived(
+  buildImageInfo.containerImageName === buildImageInfo.containerImageName.toLowerCase(),
+);
```
Comment (axel7083) [inline packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: question (non-blocking): is there other condition to the name of an image ? is it alphanumerical character only? 

My point is, should we make it maybe more generic like, having several checks?

```svelte
let nameInputError: string | undefined = $dervied.by(() => {
 if( /* condition 1 */) return 'error condition 1';
 return undefined;
});
```

**Review by axel7083 — COMMENTED** [review]
See https://github.com/podman-desktop/podman-desktop/pull/13103/files#r2192449345

File: packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: AFAIK also it's not possible to shadow undefined in our project as well due to strict mode

Comment (simonrey1) [reply packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: 6ac74d239abd26c51a2a53ec1c0b525b71a1d2b2

File: packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte (hunk 2 above)
Comment (benoitf) [reply packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: I think we're mostly using this pattern (logic outside of the fields)

so I think it'll more readable yes if we only pass/give the error field and then avoid `? : undefined: 'error message'`

Comment (simonrey1) [reply packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: The validation seems to be done here in podman but it may depends on the provider
https://github.com/containers/podman/blob/aab1029b4fdc022528880a01565960c7400ad439/pkg/api/handlers/utils/images.go#L44

Comment (simonrey1) [reply packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: @benoitf I moved the logic in this commit cdf88d81566c2ae06372f7c387abd5ff3972c485

**Review by benoitf — APPROVED** [review]

File: packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte [hunk 3]
```diff
@@ -323,13 +323,20 @@ $effect(() => {
...
 let hasInvalidFields = $derived(
   !buildImageInfo.containerFilePath ||
     !buildImageInfo.containerBuildContextDirectory ||
     (platforms.length > 1 && !buildImageInfo.containerImageName) ||
     platforms.length === 0 ||
+    !isImageNameLowercase ||
```
Comment (axel7083) [inline packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: suggestion: we can probably remove `isImageNameLowercase` and have only `errorContainerImageName` as error mean invalid


```suggestion
    !errorContainerImageName ||
```

**Review by axel7083 — APPROVED** [review]
LGTM

**Review by axel7083 — APPROVED** [review]

**Comment by vzhukovs** [comment]
@Mergifyio backport 1.20.x
