### PR TITLE
fix: make image build cancellable

### LINKED ISSUE #10080: No way to cancel build, start another one
### Bug description

I started a build using the GPU test here [1] and it appeared to hang - well over four minutes with no feedback in the UI. It was actually caused by #10077, but I didn't know at the time and this issue is for the usability during a hung or extended build, not the specific cause.

- If you leave the page and come back the console output has disappeared.
- No progress, additional console output, or anything to confirm if it's actually still running.
- Cancel button doesn't work.
- Closing and reopening the form brings you back to the same build instead of allowing you to start a new one.

[1] https://podman-desktop.io/docs/podman/gpu#verification

Image

### Operating system

macOS 15.1

### Installation Method

None

### Version

1.14.1

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

0. Supports cancellation and restart the build
1. Preserves build history (form field values and terminal output)
2. Restores build status when called from task manager (form field values and terminal output)
3. Removes stored status for finished builds when task is removed form task manager
4. Supports all kinds of transition to the build image page and restores build state

### Screenshot / video of UI

https://github.com/user-attachments/assets/91bfa398-8ebf-499d-92be-de352f96081f

### What issues does this PR fix or reference?

Fix #10080

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte [hunk 1]
```diff
@@ -30,39 +30,50 @@ import {
...
+$: hasInvalidFields =
+  !buildImageInfo.containerFilePath ||
+  !buildImageInfo.containerBuildContextDirectory ||
+  (platforms.length > 1 && !buildImageInfo.containerImageName) ||
+  platforms.length === 0 ||
+  !buildImageInfo.selectedProvider;
+
+$: if (taskId && taskId !== buildImageInfo.taskId) {
+  if (buildImageInfo?.buildImageKey) {
+    //} && !buildImageInfo.buildFinished) {
```
Comment (feloy) [inline packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte]: you can remove this commented code

**Review by feloy — APPROVED** [review]
tested on mac, can come back to a previous image build screen after a cancel, with correct info in the form

File: packages/renderer/src/App.svelte [hunk 2]
```diff
@@ -178,6 +178,12 @@ window.events?.receive('kubernetes-navigation', (args: unknown) => {
         <Route path="/images/existing-image-create-container" breadcrumb="Select image" >
           <CreateContainerFromExistingImage />
         </Route>
+        <Route path="/images/build" breadcrumb="Build an Image">
+          <BuildImageFromContainerfile />
+        </Route>
+        <Route path="/operations/images/build/:taskId" breadcrumb="Build an Image" let:meta>
+          <BuildImageFromContainerfile taskId={+meta.params.taskId}/>
```
Comment (axel7083) [inline packages/renderer/src/App.svelte]: question: not sure to understand the `+` prefixing the `meta.params.taskId`?

File: packages/renderer/src/App.svelte [hunk 3]
```diff
@@ -178,6 +178,12 @@ window.events?.receive('kubernetes-navigation', (args: unknown) => {
         <Route path="/images/existing-image-create-container" breadcrumb="Select image" >
           <CreateContainerFromExistingImage />
         </Route>
+        <Route path="/images/build" breadcrumb="Build an Image">
+          <BuildImageFromContainerfile />
+        </Route>
+        <Route path="/operations/images/build/:taskId" breadcrumb="Build an Image" let:meta>
```
Comment (axel7083) [inline packages/renderer/src/App.svelte]: remark (blocking): I am not sure to understand why need two routes ? we could use instead a query parameter, so we have a single root, and have the taskId `string | undefined`.

File: packages/renderer/src/stores/build-images.ts [hunk 4]
```diff
@@ -16,13 +16,51 @@
...
+    containerFilePath: '',
+    containerBuildContextDirectory: '',
+    containerBuildPlatform: '',
+    buildArgs: [{ key: '', value: '' }],
+  };
 }
 
-// current build key
-export const buildImagesInfo: Writable<BuildImageInfo> = writable();
+export const buildImagesInfo: Writable<Map<number, BuildImageInfo>> = writable(new Map());
```
Comment (axel7083) [inline packages/renderer/src/stores/build-images.ts:80]: remark: I would rather have the store in a dedicated files like `build-image-info-store` or something with an explicit name, otherwise with the content of the file, and the store being at the bottom of the file, it get lost

File: packages/renderer/src/App.svelte (hunk 2 above)
Comment (dgolovin) [reply packages/renderer/src/App.svelte]: It converts string to number.

https://stackoverflow.com/questions/12862624/whats-the-fastest-way-to-convert-string-to-number-in-javascript

File: packages/renderer/src/App.svelte (hunk 3 above)
Comment (dgolovin) [reply packages/renderer/src/App.svelte]: resolved

File: packages/renderer/src/stores/build-images.ts (hunk 4 above)
Comment (dgolovin) [reply packages/renderer/src/stores/build-images.ts:80]: The file was not introduced by this fix, it should be follow up issue probably.

File: packages/renderer/src/lib/image/ImagesList.svelte [hunk 5]
```diff
@@ -165,7 +165,7 @@ onDestroy(() => {
 });
 
 function gotoBuildImage(): void {
-  router.goto('/images/build');
+  router.goto('/images/build?taskId=');
```
Comment (axel7083) [inline packages/renderer/src/lib/image/ImagesList.svelte]: you should not need to specify the taskId parameter here, not having it makes it undefined

File: packages/renderer/src/stores/build-images.ts (hunk 4 above)
Comment (axel7083) [inline packages/renderer/src/stores/build-images.ts:80]: I don't know how future proof this is, I don't want to block this PR, because this is already how we do things in for the providers form etc.

But this is a memory leak, we never cleanup, we just store the data, if someone never restart podman desktop the build logs are stored forever, this is a problem..

 maybe we need some discussion and maybe think again about https://github.com/podman-desktop/podman-desktop/issues/7397

cc @benoitf, I am interested about your opinion on this matter

Comment (dgolovin) [reply packages/renderer/src/stores/build-images.ts:80]: This should be stored until it is accessible from Task Manager, so if someone decide to check what happened it specific build it would always get build image form restored to the saved state. 

I was going to implement clean up it up when Task removed from Task Manager and therefore the stored data for the build is no longer accessible from Podman Desktop UI.

Comment (axel7083) [reply packages/renderer/src/stores/build-images.ts:80]: > I was going to implement clean up it up when Task removed from Task Manager and therefore the stored data for the build is no longer accessible from Podman Desktop UI.

yeah, but my point would be, maybe this should not be stored in the frontend, but in the backend, I don't know what is the best practice here.

If the data is stored in the backend, we could add a `cleanup / dispose` event to  the tasks, so when the tasks is cleaned / removed, we can removed attached data.

**Review by ScrewTSW — APPROVED** [review]
Tested on Linux, seems to be working fine

**Comment by ScrewTSW** [comment]
tested on Mac M2 Pro and Windows 10 as well, AOK

**Review by axel7083 — APPROVED** [review]
