### PR TITLE
fix(test): flake in telemetry

### LINKED ISSUE #3567: Test flake in TelemetryService.ts
### Bug description

I've seen this flake happen during renderer tests a couple times locally but extremely rare, just saw it during PR automation for the first time.

### Operating system

macOS 13.5

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

```shell
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯
ReferenceError: window is not defined
 ❯ Timeout._onTimeout src/TelemetryService.ts:42:7
     40| 
     41|     this.handlerFlusher = setTimeout(() => {
     42|       if (window.telemetryPage) {
       |       ^
     43|         window.telemetryPage(pagePath).catch((error: unknown) => {
     44|           console.error('Failed to send page event', error);
 ❯ listOnTimeout ../../node:internal/timers:569:17
 ❯ processTimers ../../node:internal/timers:512:7

This error originated in "src/lib/compose/ComposeDetails.spec.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
This error was caught after test environment was torn down. Make sure to cancel any running tasks before test finishes:
- cancel timeouts using clearTimeout and clearInterval
- wait for promises to resolve using the await keyword
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
clear the timeout when the component is destroyed
else we may have code being executed once environment is gone

vitest, when it's tearing down the test, remove all global objects  like window, navigator, etc
we should remove any pending timeout when the component is removed so there is no late execution

(move the code to a separate method that was cleaning the timeout)

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/3567

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

File: packages/renderer/src/TelemetryService.ts [hunk 1]
```diff
@@ -46,4 +43,12 @@ export class TelemetryService {
       }
     }, 200);
   }
+
+  // clear timeout
+  public handlePageClose() {
+    if (this.handlerFlusher !== undefined) {
```
Comment (jeffmaury) [inline packages/renderer/src/TelemetryService.ts]:
```suggestion
    if (this.handlerFlusher) {
```

Comment (benoitf) [reply packages/renderer/src/TelemetryService.ts]: resolved

**Review by deboer-tim — APPROVED** [review]
