### PR TITLE
fix: restart container on terminal page

### LINKED ISSUE #9794: terminal unresponsive when restarting a container
### Bug description

When on a terminal page for a container, if I press the "restart container", the terminal reappears, but is unresponsive.

I need to go to another page and come back to the terminal to make it work again.

https://github.com/user-attachments/assets/6097c86d-78ec-46dd-9ca2-2e4100a77c56

The problem seems very similar to #9771 (except using restart button instead of stop + start), but the root cause seems different, as the PR #9793 does not fix this problem

### Operating system

mac

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

Restart the terminal when the container is in RUNNING state with a previous RESTARTING state (before, only the STARTING state was taken into consideration).

### What issues does this PR fix or reference?

Fixes #9794 

### How to test this PR?

- Start a container and go to its terminal page
- Restart the container (with the "Restart container" button, not stop+start)
- check that the terminal is visible again and that you can type character and get response.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/container/ContainerDetailsTerminal.svelte [hunk 1]
```diff
@@ -31,7 +31,8 @@ let lastState = $state('');
 let containerState = $derived(container.state);
 
 $effect(() => {
-  if (lastState === 'STARTING' && containerState === 'RUNNING') {
+  if ((lastState === 'STARTING' || lastState === 'RESTARTING') && containerState === 'RUNNING') {
+    console.log('==> restart');
```
Comment (benoitf) [inline packages/renderer/src/lib/container/ContainerDetailsTerminal.svelte]: remove

File: packages/renderer/src/lib/container/ContainerDetailsTerminal.svelte [hunk 2]
```diff
@@ -55,6 +56,7 @@ function receiveDataCallback(data: Buffer) {
 function receiveEndCallback() {
   // need to reopen a new terminal if container is running
   if (containerState === 'RUNNING') {
+    console.log('==> shellInContainer 2');
```
Comment (benoitf) [inline packages/renderer/src/lib/container/ContainerDetailsTerminal.svelte]: Remove

File: packages/renderer/src/lib/container/ContainerDetailsTerminal.svelte [hunk 3]
```diff
@@ -76,6 +78,7 @@ async function executeShellIntoContainer() {
   }
 
   // grab logs of the container
+  console.log('==> shellInContainer 1');
```
Comment (benoitf) [inline packages/renderer/src/lib/container/ContainerDetailsTerminal.svelte]: Remove

**Review by benoitf — APPROVED** [review]

**Review by SoniaSandler — APPROVED** [review]

**Comment by benoitf** [comment]
to be backported to 1.14.x as well
