### PR TITLE
fix: ensure system path is created and show notification if not in PATH

### LINKED ISSUE #5776: Podman compose setup fails on Podman Desktop for windows
### Bug description

I tried to execute compose setup on the GUI via Settings/Resources compose. After asking for admin credentials Docker Desktop shows the screen: Failed Installing Compose and a Button Try again.
Any hints for troubleshooting are appreciated.

### Operating system

Windows10

### Installation Method

Installer from website/GitHub releases

### Version

Podman Desktop 1.7.0 / 1.7.1 , Podman 4.8.0/ 4.9.2

### Steps to reproduce

as above

### Relevant log output

```shell
where to find log output ?
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #5776

### What does this PR do?

When installing compose system wide ensure the folder exists and if is not in PATH display a warning message

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#5776

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: extensions/compose/src/cli-run.ts [hunk 1]
```diff
@@ -91,6 +88,12 @@ export async function installBinaryToSystem(binaryPath: string, binaryName: stri
     // Use admin prileges / ask for password for copying to /usr/local/bin
     await extensionApi.process.exec(command, args, { isAdmin: true });
     console.log(`Successfully installed '${binaryName}' binary.`);
+    if (!process.env.PATH?.includes(destinationFolder)) {
+      await extensionApi.window.showWarningMessage(
+        `The compose binary has been installed into ${destinationFolder} but it is not in the system path. You should add it manuaaly if you want to use compose from cli.`,
```
Comment (feloy) [inline extensions/compose/src/cli-run.ts]:
```suggestion
        `The compose binary has been installed into ${destinationFolder} but it is not in the system path. You should add it manually if you want to use compose from cli.`,
```

**Review by feloy — APPROVED** [review]
lgtm
