### PR TITLE
fix: stop autostarted VM when podman extension is deactivated

### LINKED ISSUE #1661: Podman VM not always stops when exiting Podman Desktop
### Bug description

When exiting Podman Desktop, the expected behavior is that the Podman VM is stopped. This seems to only be partially implemented. I have Podman in autostart. It seems to work the first time after a reboot, but on subsequent times I open and exit Podman Desktop, the VM is not stopped. This is unexpected. I'd like the tray status icon to indicate whether Podman is running or not. If the VM is not stopped reliably, then I cannot be sure that it is actually not running. Instead I need to check via the CLI or in the Activity Monitor.

I have included a screen recording to illustrate the problem:
(the part in the middle when I'm not moving the cursor is me waiting for the VM to full start)

https://user-images.githubusercontent.com/340142/224550517-ed51b014-f3ac-4012-b92d-6a0c6ffcb9e6.mp4

### Operating system

macOS Ventura 13.2.1

### Version

0.12.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vyasgun**
### What does this PR do?
Stop an autostarted VM when podman extension is deactivated 
### What issues does this PR fix or reference?

Fixes #1661 
### How to test this PR?
This is the second part for the fix of #1661. Start podman desktop with no machine running. It will autostart a machine. Quitting the app will stop the autostarted machine.

### CODE REVIEW

File: extensions/podman/src/extension.ts [hunk 1]
```diff
@@ -645,9 +650,21 @@ export async function activate(extensionContext: extensionApi.ExtensionContext):
...
+  if (!autoMachineStarted) {
+    return;
+  }
+  await execPromise(getPodmanCli(), ['machine', 'stop', autoMachineName]);
+}
+
 export function deactivate(): void {
   stopLoop = true;
   console.log('stopping podman extension');
+  stopAutoStartedMachine().then(() => {
```
Comment (lstocchi) [inline extensions/podman/src/extension.ts]: Not working for me. I guess PD exits before the execPromise method actually is done.

**Review by jeffmaury — COMMENTED** [review]
What if the auto started machine is stopped by the user ?

File: extensions/podman/src/extension.ts (hunk 1 above)
Comment (vyasgun) [reply extensions/podman/src/extension.ts]: Yes, it quits before completing the execution of the `before-quit` handler sometimes. I'll update this.

File: extensions/podman/src/extension.ts [hunk 2]
```diff
@@ -645,9 +649,41 @@ export async function activate(extensionContext: extensionApi.ExtensionContext):
...
+  const machines = JSON.parse(machineListOutput) as MachineJSON[];
+
+  let currentMachine: MachineJSON | undefined;
+
+  // Find the autostarted machine and check its status
+  for (const machine of machines) {
+    if (machine?.Name == autoMachineName) {
+      currentMachine = machine;
+      break;
+    }
```
Comment (benoitf) [inline extensions/podman/src/extension.ts]:
```suggestion
  // Find the autostarted machine and check its status
currentMachine = machines.find(machine => machine?.Name === autoMachineName);
```

**Review by benoitf — COMMENTED** [review]
it looks odd to me that we need to patch all of the before-quit handler

**Comment by vyasgun** [comment]
@benoitf yes, I think so too - I am trying to think of a cleaner way to ensure the app doesn't quit before the handler completes execution.

File: packages/main/src/index.ts [hunk 3]
```diff
@@ -51,14 +51,17 @@ app.on('window-all-closed', () => {
...
+  event.preventDefault();
+  await extensionLoader
     ?.stopAllExtensions()
     .then(() => {
       console.log('Stopped all extensions');
+      app.quit();
     })
     .catch(error => {
       console.log('Error stopping extensions', error);
+      app.quit();
```
Comment (benoitf) [inline packages/main/src/index.ts]: I'm thinking we should move to app.on('before-quit') and add a flag to tell if we're already stopping the extensions.
because we might still quit the app before performing the stopAll extensions here



You might do a

```
try {

} catch {

} finally {
   app.quit()
}
```

**Comment by lstocchi** [comment]
@vyasgun how did you test it? By running with `yarn watch` and quitting or generating the binary, start it and quitting? It doesn't seem to work on win 11.

**Comment by vyasgun** [comment]
@lstocchi I am looking into this

**Comment by vyasgun** [comment]
@lstocchi We need to add a flag to track the execution of this particular `before-quit` handler. The handler in telemetry calls `app.quit` which causes the app to quit before it runs. I have committed this change now and it is working for me. Please let me know if it works for you.

**Review by lstocchi — APPROVED** [review]
Tested, works fine on Windows!! Thanks @vyasgun 🚀
