### PR TITLE
fix: only restart if a machine is running

### LINKED ISSUE #3321: Switching Docker Compatibility on/off requests for Podman machine restart even when it is stopped or does not exists
### Bug description

When switching Docker compatibility on/off podman desktop asks to restart podman machine when it is stopped or has not even been created yet.

Screenshot 2023-07-24 at 11 01 19 AM

### Operating system

macOS Ventura 13.4 (Apple M1)

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Stop or delete podman machine
2. Enable or disable docker compatibility
3. Watch request being made to restart 'undefined' podman machine
4. Click 'Yes' button and see error reported in console
image

### Relevant log output

```shell
'''
Uncaught (in promise) Error: Error: undefined: VM does not exist

await (async)
click_handler @ StatusBarItem.svelte:36
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
fix: only restart if a machine is running

### What does this PR do?

No matter what, it would try to restart regardless if a machine was
running or not.

This is because the if statement was: `if (isRunning !== '')` which will
always return true even if isRunning was undefined.

The if statement has now been changes to `if (isRunning)` meaning it
will only run if isRunning is defined (not '').

### Screenshot/screencast of this PR

N/A. The prompt will not appear when trying to restart it if there is no
machine running.

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/3321

### How to test this PR?

Click on Docker Compatibility with a Podman Machine stopped. You should
not get the prompt to restart the podman machine.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by deboer-tim** [comment]
findRunningMachine() says it returns a boolean, maybe fix that too?

**Comment by cdrage** [comment]
Ready for review! 💯 had to figure out what was happening inside the tests and then realized it wasn't being mocked correctly (even for an old test too).

Updated and ready 👍

File: extensions/podman/src/compatibility-mode.ts [hunk 1]
```diff
@@ -138,7 +138,7 @@ export class DarwinSocketCompatibility extends SocketCompatibility {
 
     // Prompt the user to restart the podman machine if it's running
     const isRunning = await findRunningMachine();
-    if (isRunning !== '') {
+    if (isRunning) {
```
Comment (dgolovin) [inline extensions/podman/src/compatibility-mode.ts]: This is code duplication.

```
    const isRunning = await findRunningMachine();
    if (isRunning) {
      await this.promptRestart(isRunning);
    }

    return Promise.resolve();
```

Let's move check for machine name inside of promptRestart method.

After that we can rewrite the method as

```
  async enable(): Promise<void> {
    await this.runCommand('install', 'enabled')

    // Prompt the user to restart the podman machine if it's running
    return findRunningMachine().then(machine => this.promptRestart(machine));
  }
```

File: extensions/podman/src/compatibility-mode.ts [hunk 2]
```diff
@@ -150,7 +150,7 @@ export class DarwinSocketCompatibility extends SocketCompatibility {
...
```
Comment (dgolovin) [inline extensions/podman/src/compatibility-mode.ts]: Changes for enable() method can be applied to disable() method too.

**Review by dgolovin — APPROVED** [review]
Verified on mac and it works for me now. No requests to restart machine if it does not exist or is not started.

disable() and enable() functions can be improved (optional).

LGTM

**Comment by cdrage** [comment]
Thank you for the suggestion @dgolovin ! Totally makes the code a lot cleaner. Pushed your suggestion 👍

**Comment by cdrage** [comment]
@dgolovin 

Unfortunately `return findRunningMachine().then(machine => this.promptRestart(machine));` does not work compared to:

```
    const isRunning = await findRunningMachine();
    if (isRunning) {
      await this.promptRestart(isRunning);
    }

    return Promise.resolve();
```

As even when it returns undefined in findRunningMachine, promptRestart is still ran in the function: `return findRunningMachine().then(machine => this.promptRestart(machine));`

If you replace the code, you'll see that the tests now fail.

I've updated the code back to the previous change.

**Review by dgolovin — CHANGES_REQUESTED** [review]
@cdrage I was suggesting to do [this](https://github.com/cdrage/podman-desktop/pull/7/files) as a fix.

Please remove at least

```
return Promise.resolve();
```

it is not needed and result is going to be the same.

**Comment by cdrage** [comment]
> @cdrage I was suggesting to do [this](https://github.com/cdrage/podman-desktop/pull/7/files) as a fix.
> 
> Please remove at least
> 
> ```
> return Promise.resolve();
> ```
> 
> it is not needed and result is going to be the same.

Hi, I commented on the PR. Bit confused on `return Promise.Resolve` suggestion, it's added to the tests in order to mock the functionality.

**Comment by cdrage** [comment]
@dgolovin Ready for another review / I've pushed your changes! :)

**Comment by cdrage** [comment]
Getting some weird errors with smoke testing @odockal @dgolovin any ideas? Rebased + it works fine with `yarn watch`, but unsure why it's causing these tests to fail.

**Comment by cdrage** [comment]
Tests pass now 💯

**Review by dgolovin — APPROVED** [review]
