### PR TITLE
fix(ui): better handle errors on `KubePort` component

### LINKED ISSUE #9686: port forwarding error should be removed when the port forward is deleted
### Bug description

As noted by @feloy in https://github.com/containers/podman-desktop/pull/9682#issuecomment-2447549286 the error is staying even after the user has deleting the port forwarding.

We should remove/reset the error state after the deletion.

### Operating system

Fedora 40

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. forward a port that does not exist
2. assert error visible
3. remove the port forwarding
4. assert error still visible

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Improve the error handling for the port forward actions (display delete errors if any, cleanup previous error when retrying)

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/9686

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/kube/details/KubePort.svelte [hunk 1]
```diff
@@ -59,11 +59,13 @@ async function removePortForward(): Promise<void> {
   if (!mapping) return;
   if (!forwardConfig) return;
   loading = true;
+  error = undefined;
 
   try {
     await window.deleteKubernetesPortForward(forwardConfig);
   } catch (err: unknown) {
     console.error(err);
```
Comment (feloy) [inline packages/renderer/src/lib/kube/details/KubePort.svelte:67]: Do we want to keep to error on the console, as it is now displayed in the UI?

**Review by feloy — APPROVED** [review]
Tested, works as expected.

File: packages/renderer/src/lib/kube/details/KubePort.svelte (hunk 1 above)
Comment (axel7083) [reply packages/renderer/src/lib/kube/details/KubePort.svelte:67]: I would argue yes, because traces, when we display to the UI, we might lose information because of stringify, I am not sure what to follow here, we don't have much guidelines on this point

**Review by benoitf — APPROVED** [review]
