### PR TITLE
fix: check for self signed cert message and use insecure param when editing registry password

### LINKED ISSUE #4522: Adding OpenShift Local docker registry does not trigger insecure registry confirmation request
### Bug description

I have OpenShift Local running and want to add docker registry form it to list of the registries in podman desktop. The registry is using self signed certificate and I always get an error message about 'self signed certificate in certificate chain'. There should be a request if certificate is not trusted and if I still want to use this specific registry, but it never shows up.

https://github.com/containers/podman-desktop/assets/620330/a9d0b09c-1ad8-4857-9e04-b727b960bc28

The same problem is happening if I would try to update password for the registry using self singed certificate.

https://github.com/containers/podman-desktop/assets/620330/bdda7399-9222-434c-bc3f-38535f7d7ba9

### Operating system

macOS Sonoma 14.0

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

When creating new registry:
1. Install OpenShift Local extension
2. Start OpenShift Local cluste
3. Switch to crc-admin kubernetes context
4. Open terminal and run oc whoami --show-token
5. Copy token to clipboard
6. Open Settings/Registries
7. Add new registry  url: default-route-openshift-image-registry.apps-crc.testing, user: kubeadmin, password: paste token

When editing OpenShift Local registry password
1. Select edit 'Edit Password'
2. Change password to incorrect one
3. Press Login
4. Error appears about 'self signed certificate in certificate chain' not 'Incorrect username or password'

### Relevant log output

_No response_

### Additional context

related to testing and looking for solution of #3538.

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Checking for another message related to self signed certificate when adding OpenShift Local image registry to trigger insecure registry confirmation request.

Use insecure parameter to verify new credentials when editing password for insecure registry.

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/620330/a6d13e9f-0048-4c8c-8c9c-223eda46e911

### What issues does this PR fix or reference?

fix #4522.
releated to testing of #3538.

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Add unit test

File: packages/renderer/src/lib/preferences/PreferencesRegistriesEditing.svelte [hunk 1]
```diff
@@ -208,9 +212,9 @@ async function loginToRegistry(registry: containerDesktopAPI.Registry) {
 
   try {
     if (newRegistry) {
-      await window.createImageRegistry(registry.source, registry);
+      await window.createImageRegistry(registry.source, { ...registry });
```
Comment (jeffmaury) [inline packages/renderer/src/lib/preferences/PreferencesRegistriesEditing.svelte:215]: Sounds weird to me

Comment (dgolovin) [reply packages/renderer/src/lib/preferences/PreferencesRegistriesEditing.svelte:215]: It is just pass a shallow copy of the object to function rather than shared object.
Another option is create new shard object when page cleaning new registry form.

Comment (dgolovin) [reply packages/renderer/src/lib/preferences/PreferencesRegistriesEditing.svelte:215]: This is required or the hasBeenCalledWith assertion is going to fail in test. It happens because newRegistryForm is going to be cleaned of entered values right after calling window.createNewRegistry.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by cdrage — APPROVED** [review]
LGTM! Was able to test this locally and I was able to successfully edit the password (and have the prompt come up again fine). Code LGTM too.
