### PR TITLE
fix: context store gets current context on extensions-already-started event

### LINKED ISSUE #4605: Optional options hidden in podman machine creation page on Windows and Mac after force reload
### Bug description

Opening this issue to keep track of a possible bug which does not happen frequently.
When testing the new 1.5.2, I tried to create a new podman machine and all options (rootful, usernetworking) were hidden.
After a restart it started working fine.
The same happen to @odockal once.

I was not able to replicate it again. If someone has more info please post it here. Thanks!!

### Operating system

Windows 10/ 11 and Mac OS 14

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Install Podman (either using onboarding, or dashboard buttons)
2. Go To Settings -> Resources
3. Verify: Open Create new ... (podman machine) form/page got all options available
4. Go back to Resources and call Force Reload (CTRL + R on windows)
5. Verify the Create new page again
6. Assert: All Buttons are present
Actual result: These optional button are not visible.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

The current `context` store is initialized with an empty context and receives updates when the context changes.

But if the user reloads the window, the store is reset, but never receives again the previous values.
 
This PR gets the current values of the context to set the new value of the context store when the event `extensions-already-started` is received, event happening when the window is reloaded.

### What issues does this PR fix or reference?

Fixes #4605 

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by benoitf** [comment]
tested, it works fine, now need tests 🎉

File: packages/renderer/src/stores/context.ts [hunk 1]
```diff
@@ -20,6 +20,13 @@ import type { Writable } from 'svelte/store';
 import { writable } from 'svelte/store';
 import { ContextUI } from '../lib/context/context';
 
+async function getCurrentContext(): Promise<ContextUI> {
+  return Object.entries(await window.contextCollectAllValues()).reduce((result, [key, value]) => {
+    result.setValue(key, value);
+    return result;
+  }, new ContextUI());
+}
+
```
Comment (benoitf) [inline packages/renderer/src/stores/context.ts]: maybe this method content can be moved to the addEventListener method

Also, add a check like we do that only if window.contextCollectAllValues exists

so no need to change all spec.ts files, only the one that would want to override the context

Comment (benoitf) [reply packages/renderer/src/stores/context.ts]: or in Loader.svelte we could also send an event to the backend in case of client refresh, so backend could send again new stuff

in that case, backend will send context-value-updated calls for contexts

**Comment by feloy** [comment]
> tested, it works fine, now need tests 🎉

As the code in `context.ts` is global, I need to create mocks in a `vi.hoisted`, so they are mocked before the import of the `context.ts`, right?

**Comment by benoitf** [comment]
you can also do like for other stores

like a class with a setup method, or just a setup function()
in the store it calls setup function

but then in your test you can do in beforeEach the hooks you want and then you manually call the setup method that will redo the init but using your hooks

File: packages/renderer/src/stores/context.spec.ts [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ ***********************************************************************/
+
+import { beforeAll, beforeEach, expect, test, vi } from 'vitest';
+import { setup } from './context';
+import { ContextUI } from '../lib/context/context';
+import { get } from 'svelte/store';
+
+const contextCollectAllValues = vi.fn();
```
Comment (benoitf) [inline packages/renderer/src/stores/context.spec.ts:24]: not: this one is not suffixed by Mock like the 2 following

**Review by benoitf — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM. Tested on Win11Pro
