### PR TITLE
fix: wait the podman process to end before log the error (#2002)

### LINKED ISSUE #2002: Misbehavior when receiving an error during command execution
### Bug description

On my old laptop if i start a podman machine i see an error during the execution but then the machine gets actually started.
No idea what kind of error this is and why i don't face it on the other computer `your 131072x1 screen size is bogus. expect trouble`

error-start-machine

### Operating system

Windows 10

### Version

next (development version)

### Steps to reproduce

No idea honestly
I just start a podman machine and i face it

### Relevant log output

```shell
your 131072x1 screen size is bogus. expect trouble
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR avoid sending an error to the logger used by the task manager when something is written to stderr. It waits that the process ends with an exit code different than 0.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

it fixes #2002 

### How to test this PR?

1. start/stop a podman machine and check that everything works fine. It would be great if you were able to reproduce the same error i had somehow.
@slemeur i remember you posted a similar issue on slack. If you are able to reproduce the bug consistently can you try this fix?

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
I find it strange that the client side has to be updated to remove logging during execution what if we have another process that is doing the same ? Isn't the problem on the implementation side (the task manager UI ?)

**Comment by lstocchi** [comment]
> I find it strange that the client side has to be updated to remove logging during execution what if we have another process that is doing the same ? Isn't the problem on the implementation side (the task manager UI ?)

I didn't get it. 
There are 3 different events that the logger can log (`log`, `warn` and `error`). The task manager marks the task as failed when the error event is received. 
Until now the stderr was redirected to the error channel, but if a process writes to stderr it doesn't mean that it failed.
Maybe i should redirect stdErr to `warn`

How should the task manager UI handles it? it cannot know if the error was fatal or not.

**Comment by jeffmaury** [comment]
So maybe we should map stdErr to warn and raise an error is exitCode is different from 0 ?

**Comment by lstocchi** [comment]
> So maybe we should map stdErr to warn and raise an error is exitCode is different from 0 ?

the error is already raised if the exitcode is different from 0 -> https://github.com/containers/podman-desktop/pull/2132/files#diff-1d16ac2f384c4c96f7a97d54054e227b1a53aed035e9bd5f005b68d60525bc39R118

I'll add the warn

File: extensions/podman/src/podman-cli.ts [hunk 1]
```diff
@@ -111,20 +111,13 @@ export function execPromise(
...
-      if (stdOut && stdOut !== '') {
-        content += stdOut + '\n';
-      }
-      if (stdErr && stdErr !== '') {
-        content += stdErr + '\n';
-      }
-
       if (exitCode !== 0) {
-        reject(new Error(content));
+        options?.logger?.error(stdErr);
```
Comment (jeffmaury) [inline extensions/podman/src/podman-cli.ts:119]: Same data will be logged twice. Is it a requirement ?

Comment (lstocchi) [reply extensions/podman/src/podman-cli.ts:119]: WDYM logged twice? the logger.error and the reject message? or the warn and the error?
if it is about the first, then the reject will be handled by a catch in further steps so it's the ui which will decide if to show it twice somewhere or not. In the current implementation it happens as you can read the error in the terminal and in the error component that pop up below the terminal.

if it's about the second, the task manager uses the error content as the text to show if an error occurs. But it seems correct for me. Let's say i only write to the warn channel, the task manager should have the logic to store the content and then show it in the task manager UI if the process fails. 

image

By maintaining this separation the UI can prints the warn in the terminal and the error (if the process eventually fails) in the task manager.

Comment (jeffmaury) [reply extensions/podman/src/podman-cli.ts:119]: I mean the content of stdErr will be logged twice at the warn and error level, don't know if it's an issue ?

Comment (lstocchi) [reply extensions/podman/src/podman-cli.ts:119]: forgot to reply. The problem is that you don't know in advance if the content returned by stderr is just a warning or a fatal error that will stop the process. Only when the process fails you can tell, ok the stderr returned was a fatal error. I don't see many other alternatives how to handle it tbh.
The decision is just if we want to redirect stderr to logger.log or logger.warn.
If you have any preferences, just let me know so i can update it.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by cdrage — APPROVED** [review]
This works and LGTM. I feel as though @benoitf should have a quick look before we merge.

**Review by benoitf — APPROVED** [review]
