### PR TITLE
fix: set rootful connection when starting rootful machine (#2582)

### LINKED ISSUE #2582: Podman machine created with root privileges is not respected when there are more than one machine
### Bug description

I am assuming that creation of a podman machine with root-privileges on will choose root system connection as a default, so once started, root connection is used. 

this is true when there is no machine on the system and we are creating a new one. When there is a machine (with system connections) already, root system connection of the newly created machine is not set.

rootfulmachine

### Operating system

Windows 10

### Version

1.0.x

### Steps to reproduce

1. Start podman desktop on the windows. 
2. Install, initialize and start podman machine on it (rootless by default)
3. Create new machine, where we want root privileges to be applied.
4. Start the new machine and check whether is has root privileges
5. Ie. One can create new kind cluster connection
Actually, kind cluster creation says I have to use rootful connection or setup rootless (workaround)
Cli shows that root system connection of the new machine was not set as default and thus new machine is using old (rootless) connection of the old machine. 

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR set the default connection to the rootful one if the machine has been originally created rootful

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

it resolves #2582 

### How to test this PR?

1. create a rootful machine
2. start it when the default is a different machine
3. it should ask if you want to switch default -> yes
4. verify that the rootful connection has been selected

### CODE REVIEW

File: extensions/podman/src/util.ts [hunk 1]
```diff
@@ -108,3 +109,15 @@ export function runCliCommand(command: string, args: string[], options?: RunOpti
...
+  return new Promise((resolve, reject) => {
+    fs.readFile(path, 'utf8', (err, data) => {
+      if (err) {
+        reject(err);
+      } else {
+        resolve(data);
+      }
+    });
+  });
+}
```
Comment (benoitf) [inline extensions/podman/src/util.ts]: not sure why we would need that method ?

Comment (benoitf) [reply extensions/podman/src/util.ts]: I mean, to be more clear, we do have `{ readFile } from 'node:fs/promises'`

File: extensions/podman/src/extension.ts [hunk 2]
```diff
@@ -208,22 +216,50 @@ export async function checkDefaultMachine(machines: MachineJSON[]): Promise<void
...
     if (result === 'Yes') {
       try {
+        // make it the default to run the info command
         await execPromise(getPodmanCli(), ['system', 'connection', 'default', runningMachine.Name]);
+
+        // check if it's rootful
+        const machineInfoJson = await execPromise(getPodmanCli(), ['machine', 'info', '--format', 'json']);
+        const machineInfo = JSON.parse(machineInfoJson);
+        const filepath = path.join(machineInfo.Host.MachineConfigDir, `${runningMachine.Name}.json`);
+        const machineConfigJson = await readFile(filepath);
```
Comment (benoitf) [inline extensions/podman/src/extension.ts]: should we check if file exists or that we have an entry ?

File: extensions/podman/src/util.ts (hunk 1 above)
Comment (lstocchi) [reply extensions/podman/src/util.ts]: ah cool. I saw that almost the same code was used in other parts, so the plan was to use this function to replace duplicate code. This way it's even easier. Going to use `fs/promises`

**Review by benoitf — COMMENTED** [review]
it's missing probably unit tests ? to handle this usecase / rootful mode

File: extensions/podman/src/extension.ts (hunk 2 above)
Comment (lstocchi) [reply extensions/podman/src/extension.ts]: added a path/content check + moved to its own try/catch in case of other failures

**Comment by lstocchi** [comment]
> it's missing probably unit tests ? to handle this usecase / rootful mode

tests added 👍

**Review by benoitf — APPROVED** [review]
tested and works as expected

before
![image](https://github.com/containers/podman-desktop/assets/436777/8fe4b459-7298-4743-8df6-42d26006e53c)



```
podman system connection list                                                                                                                                                                                                                                                                                                                                                                Name                         URI                                                         Identity                                    Default
foo                          ssh://core@127.0.0.1:49159/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/foo                     false
foo-root                     ssh://root@127.0.0.1:49159/run/podman/podman.sock           /Users/benoitf/.ssh/foo                     false
foobar                       ssh://core@127.0.0.1:64889/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/foobar                  false
foobar-root                  ssh://root@127.0.0.1:64889/run/podman/podman.sock           /Users/benoitf/.ssh/foobar                  false
foorootful                   ssh://core@127.0.0.1:58802/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/foorootful              false
foorootful-root              ssh://root@127.0.0.1:58802/run/podman/podman.sock           /Users/benoitf/.ssh/foorootful              false
lima-podman                  unix:///Users/benoitf/.lima/podman/sock/podman.sock                                                     false
maxmem                       ssh://core@127.0.0.1:60082/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/maxmem                  false
maxmem-root                  ssh://root@127.0.0.1:60082/run/podman/podman.sock           /Users/benoitf/.ssh/maxmem                  false
my-machine                   ssh://core@127.0.0.1:55508/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/my-machine              false
my-machine-root              ssh://root@127.0.0.1:55508/run/podman/podman.sock           /Users/benoitf/.ssh/my-machine              false
new                          ssh://core@127.0.0.1:59318/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/new                     false
new-root                     ssh://root@127.0.0.1:59318/run/podman/podman.sock           /Users/benoitf/.ssh/new                     false
podman-machine-default       ssh://core@localhost:59356/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/podman-machine-default  false
podman-machine-default-root  ssh://root@localhost:59356/run/podman/podman.sock           /Users/benoitf/.ssh/podman-machine-default  false
test                         ssh://core@127.0.0.1:60639/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/test                    true
test-root                    ssh://root@127.0.0.1:60639/run/podman/podman.sock           /Users/benoitf/.ssh/test                    false
tmp                          ssh://core@127.0.0.1:57641/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/tmp                     false
tmp-root                     ssh://root@127.0.0.1:57641/run/podman/podman.sock           /Users/benoitf/.ssh/tmp                     false
```


then
![image](https://github.com/containers/podman-desktop/assets/436777/56de995c-e81b-4666-87c7-b47c67e14c2b)

```
 podman system connection list                                                                                                                                                                                                                                                                                                                                                                    
Name                         URI                                                         Identity                                    Default
foo                          ssh://core@127.0.0.1:49159/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/foo                     false
foo-root                     ssh://root@127.0.0.1:49159/run/podman/podman.sock           /Users/benoitf/.ssh/foo                     false
foobar                       ssh://core@127.0.0.1:64889/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/foobar                  false
foobar-root                  ssh://root@127.0.0.1:64889/run/podman/podman.sock           /Users/benoitf/.ssh/foobar                  false
foorootful                   ssh://core@127.0.0.1:58802/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/foorootful              false
foorootful-root              ssh://root@127.0.0.1:58802/run/podman/podman.sock           /Users/benoitf/.ssh/foorootful              true
lima-podman                  unix:///Users/benoitf/.lima/podman/sock/podman.sock                                                     false
maxmem                       ssh://core@127.0.0.1:60082/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/maxmem                  false
maxmem-root                  ssh://root@127.0.0.1:60082/run/podman/podman.sock           /Users/benoitf/.ssh/maxmem                  false
my-machine                   ssh://core@127.0.0.1:55508/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/my-machine              false
my-machine-root              ssh://root@127.0.0.1:55508/run/podman/podman.sock           /Users/benoitf/.ssh/my-machine              false
new                          ssh://core@127.0.0.1:59318/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/new                     false
new-root                     ssh://root@127.0.0.1:59318/run/podman/podman.sock           /Users/benoitf/.ssh/new                     false
podman-machine-default       ssh://core@localhost:59356/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/podman-machine-default  false
podman-machine-default-root  ssh://root@localhost:59356/run/podman/podman.sock           /Users/benoitf/.ssh/podman-machine-default  false
test                         ssh://core@127.0.0.1:60639/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/test                    false
test-root                    ssh://root@127.0.0.1:60639/run/podman/podman.sock           /Users/benoitf/.ssh/test                    false
tmp                          ssh://core@127.0.0.1:57641/run/user/501/podman/podman.sock  /Users/benoitf/.ssh/tmp                     false
tmp-root                     ssh://root@127.0.0.1:57641/run/podman/podman.sock           /Users/benoitf/.ssh/tmp                     false
```

system connection is now correctly set to the rootful socket

File: extensions/podman/src/extension.ts [hunk 3]
```diff
@@ -208,26 +216,60 @@ export async function checkDefaultMachine(machines: MachineJSON[]): Promise<void
   // As a last check, let's see if the machine that is running is set by default or not on the CLI.
   // if it isn't, we should prompt the user to set it as default, or else podman CLI commands will not work
   const runningMachine = machines.find(machine => machine.Running);
-  const defaultMachine = machines.find(machine => machine.Default);
+  let defaultMachine = machines.find(machine => machine.Default);
+  if (!defaultMachine) {
+    const defaultConnection = await getDefaultConnection();
+    let defaultConnectionName = defaultConnection?.Name;
+    if (defaultConnectionName.endsWith('-root')) {
```
Comment (cdrage) [inline extensions/podman/src/extension.ts]: `-root` is used multiple times in the code, should it be a const variable in case we want to change it?

File: extensions/podman/src/extension.ts [hunk 4]
```diff
@@ -208,26 +216,60 @@ export async function checkDefaultMachine(machines: MachineJSON[]): Promise<void
...
+        // check if it's rootful
+        const machineInfoJson = await execPromise(getPodmanCli(), ['machine', 'info', '--format', 'json']);
+        const machineInfo = JSON.parse(machineInfoJson);
+        const filepath = path.join(machineInfo.Host.MachineConfigDir, `${runningMachine.Name}.json`);
+        if (fs.existsSync(filepath)) {
+          const machineConfigJson = await fs.promises.readFile(filepath, 'utf8');
+          if (machineConfigJson && machineConfigJson.length > 0) {
+            const machineConfig = JSON.parse(machineConfigJson);
+            if (machineConfig.Rootful) {
+              //if it's rootful let's update the connection
```
Comment (cdrage) [inline extensions/podman/src/extension.ts]:
```suggestion
              // if it's rootful let's update the connection
```

File: extensions/podman/src/extension.ts (hunk 3 above)
Comment (cdrage) [reply extensions/podman/src/extension.ts]: We should add a comment that the reason that it's `-root` is because we're updating it to be that way?

**Review by cdrage — CHANGES_REQUESTED** [review]
Tests are amazing! Crazy how there's more code in tests than the actual code. That's awesome.

Only a few little comments but otherwise this LGTM. Feel free to dismiss my review / mark as merge after reviewing.

File: extensions/podman/src/extension.ts (hunk 3 above)
Comment (lstocchi) [reply extensions/podman/src/extension.ts]: Done 👍

**Review by cdrage — APPROVED** [review]
