### PR TITLE
fix: copying docker-compose to fails on windows

### LINKED ISSUE #6543: Install docker-compose binary got error message
### Bug description

When I use Podman Desktop to follow docker-compose, I encounter an error message related to user permissions, do I need to do any privilege escalation operations on Windows 11? Also, I installed with admin privileges and had the same problem.

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

### Steps to reproduce

_No response_

### Relevant log output

```shell
VM5:2 main ↪️ [compose] Failed to install 'docker-compose' binary: Error: Failed to execute command: User did not grant permission.
console.<computed>	@	VM5:2
(anonymous)	@	VM5:2
emit	@	VM4 sandbox_bundle:2
onMessage	@	VM4 sandbox_bundle:2
VM5:2 main ↪️ [compose] Error: Failed to execute command: User did not grant permission.
    at C:\Users\*****\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:304:11148
    at C:\Users\*****\AppData\Local\Programs\podman-desktop\resources\app.asar\packages\main\dist\index.cjs:301:1476
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
console.<computed>	@	VM5:2
(anonymous)	@	VM5:2
emit	@	VM4 sandbox_bundle:2
onMessage	@	VM4 sandbox_bundle:2
```

### Additional context

podman-compose-failed

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

PR changes how docker-compose.exe copied to destination folder on windows. No user privilege lifting is required for destination folder.

### What issues does this PR fix or reference?

Fix #6543.

### How to test this PR?

Install docker-compose on windows using CLI Tools page and no privilege lifting requests should be shown

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Can we prevent using the sync call ?

**Comment by dgolovin** [comment]
> Can we prevent using the sync call ?

Updated to use fs.promises.

File: extensions/compose/src/cli-run.ts [hunk 1]
```diff
@@ -57,8 +57,8 @@ export async function installBinaryToSystem(binaryPath: string, binaryName: stri
   let args: string[] = [];
   let command: string | undefined;
   if (system === 'win32') {
-    command = 'copy';
-    args = [`"${binaryPath}"`, `"${destinationPath}"`];
+    // admin privileges are are not needed on Windows
+    return fs.promises.copyFile(binaryPath, destinationPath).then(() => destinationPath);
```
Comment (feloy) [inline extensions/compose/src/cli-run.ts]: The code is in an async function, I think you can use 
```
await fs.promises.copyFile(binaryPath, destinationPath);
return destinationPath;
```

**Review by jeffmaury — APPROVED** [review]
LGTM

File: extensions/compose/src/cli-run.spec.ts [hunk 2]
```diff
@@ -164,3 +168,16 @@ test('success: installBinaryToSystem to show warning if binary path not in PATH'
   );
   expect(extensionApi.window.showWarningMessage).toBeCalled();
 });
+
+test('installBinaryToSystem copy binary on windows using fs.copyFileSync', async () => {
```
Comment (axel7083) [inline extensions/compose/src/cli-run.spec.ts]: title is wrong? you are using `fs.promises.copyFile` not copyFileSync?

Comment (dgolovin) [inline extensions/compose/src/cli-run.spec.ts]:
```suggestion
test('installBinaryToSystem copy binary on windows using fs.copyFile', async () => {
```

File: extensions/compose/src/cli-run.ts (hunk 1 above)
Comment (dgolovin) [inline extensions/compose/src/cli-run.ts]:
```suggestion
    await fs.promises.copyFile(binaryPath, destinationPath)
    return destinationPath;
```

**Review by feloy — APPROVED** [review]
