### PR TITLE
fix: make min-height=0px for tabs on container details page

### LINKED ISSUE #3992: Resizing the window makes container's terminal last lines invisible
### Bug description

If I increase the height of the window to increase the number of lines in container's terminal and then reduce the height then I no longer see the lines of my terminal.

### Operating system

macOS Ventura 13.4 (Apple M1)

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

https://github.com/containers/podman-desktop/assets/620330/57125ce8-3cfd-4802-8fb3-c29fd052aaa6

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dgolovin**
### What does this PR do?

Fix #3992.

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/620330/22ac6eb0-eb4d-4daf-bfcc-0473cad40577

### What issues does this PR fix or reference?

Fix #3992.

### How to test this PR?

See #3992 screen recording to replicate.

### CODE REVIEW

File: packages/renderer/src/lib/ui/DetailsPage.svelte [hunk 1]
```diff
@@ -50,7 +50,7 @@ export function close(): void {
     <div class="flex flex-row px-2 border-b border-charcoal-400">
       <slot name="tabs" />
     </div>
-    <div class="h-full bg-charcoal-900">
+    <div class="h-full bg-charcoal-900" style="min-height:0px">
```
Comment (benoitf) [inline packages/renderer/src/lib/ui/DetailsPage.svelte]: Use the tailwind option there ?

```suggestion
    <div class="h-full bg-charcoal-900 min-h-0">
```

**Review by benoitf — APPROVED** [review]
Nice, I confirm the patch works

commented that you should probably use tailwind directive rather than custom style

would be interesting to know if we can have tests on the terminal working smoothly when we resize

**Review by deboer-tim — APPROVED** [review]
Tested. +1 conditional on making the change @benoitf suggested.

To be consistent with other pages like FormPage we should add "flex w-full overflow-auto" too and make sure all the *Details pages are consistent, but that actually causes more problems with the terminal so I'm not suggesting it for now. Seems like there is some odd behaviour with the terminal, but maybe I just need #3955 too.
