### PR TITLE
fix(core): update installed extensions actions to svelte 5

### LINKED ISSUE #13365: Migrate installed extensions actions to svelte 5
### Bug description

Migrate installed extensions actions to svelte 5

`packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte`

### Operating system

all

### Installation Method

None

### Version

1.19.2

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by simonrey1**
### What does this PR do?

This PR migrates the update installed extensions component to svelte 5

### What issues does this PR fix or reference?

Fixes https://github.com/podman-desktop/podman-desktop/issues/13365

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte [hunk 1]
```diff
@@ -4,10 +4,15 @@ import type { CombinedExtensionInfoUI } from '/@/stores/all-installed-extensions
 import InstalledExtensionCardLeftLifecycle from './InstalledExtensionCardLeftLifecycle.svelte';
 import InstalledExtensionCardLeftOnboardingAndProperties from './InstalledExtensionCardLeftOnboardingAndProperties.svelte';
 
-export let extension: CombinedExtensionInfoUI;
+interface Props {
+  extension: CombinedExtensionInfoUI;
+  className: string;
```
Comment (gastoner) [inline packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte]: I think you should be able to do a similar thing, and thanks to this change, you should be able to have changes only in this file? 

https://github.com/podman-desktop/podman-desktop/blob/5ac757f2c70127da7e242536f08429337dc854f7/packages/ui/src/lib/screen/EmptyScreen.svelte#L32

**Review by gastoner — CHANGES_REQUESTED** [review]

File: packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte (hunk 1 above)
Comment (simonrey1) [reply packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte]: You are right, by using `class: className` we can make it work by only changing this file.
However this is confusing in my opinion because class is reserved. 
So I prefer to use a unique className attribute rather than renaming the attribute when entering the component.

Comment (gastoner) [reply packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte]: Sure, but AFAIK we are doing this in all other files so I would stick with the convention

Comment (simonrey1) [reply packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte]: e350ae634419dd044b8b737899b8450d39cc9d72

**Review by gastoner — APPROVED** [review]

**Review by MarsKubeX — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

File: packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte [hunk 2]
```diff
@@ -4,10 +4,15 @@ import type { CombinedExtensionInfoUI } from '/@/stores/all-installed-extensions
 import InstalledExtensionCardLeftLifecycle from './InstalledExtensionCardLeftLifecycle.svelte';
 import InstalledExtensionCardLeftOnboardingAndProperties from './InstalledExtensionCardLeftOnboardingAndProperties.svelte';
 
-export let extension: CombinedExtensionInfoUI;
+interface Props {
+  extension: CombinedExtensionInfoUI;
+  class: string;
```
Comment (axel7083) [inline packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte]: generally class attribute is optional, even if for our usage we always have one, we may still have it optional to match HTML component synthax

Comment (simonrey1) [reply packages/renderer/src/lib/extensions/InstalledExtensionActions.svelte]: e179a73fc57b81325eccfbf1951f03b95e31e98a
