### PR TITLE
fix: proper validation of input fields

### LINKED ISSUE #11296: Edit image dialog is broken
### Bug description

The moment you type anything in the image name or tag you get an error: "Please enter a value". Can't find any way to clear the error.

### Operating system

macOS 15.3

### Installation Method

None

### Version

1.16.0

### Steps to reproduce

_No response_

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?

Current changes proposal provides the better way to validate input fields during image rename operation.

### Screenshot / video of UI

Снимок экрана 2025-02-25 в 18 10 48
Снимок экрана 2025-02-25 в 18 10 55
Снимок экрана 2025-02-25 в 18 11 03
Снимок экрана 2025-02-25 в 18 11 14
Снимок экрана 2025-02-25 в 18 11 45

### What issues does this PR fix or reference?

#11296 

### How to test this PR?

Open "Edit Image" modal dialog and try to enter different names into provided input fields.

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Comment by deboer-tim** [comment]
I would prefer not to fix it this way - it still depends on the type of HTML element firing the event and being able to get its value, which Input could change.

You could use an event that fires after the change and just use the value of imageName / imageTag directly, or something like:
`$: {imageTagErrorMessage = imageTag === '' ? 'Please enter a value' : ''; }`
(Svelte 5 `$derived()` would be even better)

Also, needs a test.

File: packages/renderer/src/lib/image/RenameImageModal.svelte [hunk 1]
```diff
@@ -28,22 +28,14 @@ function disableSave(name: string, tag: string): boolean {
 
 let imageNameErrorMessage = '';
 function validateImageName(event: Event): void {
-  let inputName = event.target instanceof Input ? event.target.value : undefined;
-  if (inputName === undefined || inputName.trim() === '') {
-    imageNameErrorMessage = 'Please enter a value';
-  } else {
-    imageNameErrorMessage = '';
-  }
+  const target = event.currentTarget as HTMLInputElement;
```
Comment (benoitf) [inline packages/renderer/src/lib/image/RenameImageModal.svelte]: issue: we can't assume this direct cast

File: packages/renderer/src/lib/image/RenameImageModal.svelte [hunk 2]
```diff
@@ -28,22 +28,14 @@ function disableSave(name: string, tag: string): boolean {
...
 
 let imageTagErrorMessage = '';
 function validateImageTag(event: Event): void {
-  let inputName = event.target instanceof Input ? event.target.value : undefined;
-  if (inputName === undefined || inputName.trim() === '') {
-    imageTagErrorMessage = 'Please enter a value';
-  } else {
-    imageTagErrorMessage = '';
-  }
+  const target = event.currentTarget as HTMLInputElement;
```
Comment (benoitf) [inline packages/renderer/src/lib/image/RenameImageModal.svelte]: issue: same here

File: packages/renderer/src/lib/image/RenameImageModal.svelte (hunk 1 above)
Comment (vzhukovs) [reply packages/renderer/src/lib/image/RenameImageModal.svelte]: fixed

File: packages/renderer/src/lib/image/RenameImageModal.svelte (hunk 2 above)
Comment (vzhukovs) [reply packages/renderer/src/lib/image/RenameImageModal.svelte]: fixed

**Comment by vzhukovs** [comment]
@deboer-tim @benoitf I've updated the PR with new changes, removed dynamic casting

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by benoitf** [comment]
@Mergifyio backport 1.17.x
