### PR TITLE
fix: remove incorrect 'apply' namespace from applyResourcesFromYAML

### LINKED ISSUE #7594: Unable to edit any Kubernetes YAML without having to delete resourceVersion
### Bug description

Took me **hours** to try and figure out why this wasn't working...

But whenever we apply a Kubenetes YAML, despite all the YAML being valid as well as double-checking everything `kubectl` vs our UI I couldn't figure out why this error kept popping up:

Screenshot 2024-06-11 at 11 10 47 PM

The files are the exact same, there has been no changes.. yet it still complained.

That is until I found this code:

```ts
  async applyResourcesFromYAML(context: string, yaml: string): Promise<KubernetesObject[]> {
    const manifests = await this.loadManifestsFromYAML(yaml);
    return this.applyResources(context, manifests, 'apply');
  }
```

Which calls:

```ts
  async applyResources(
    context: string,
    manifests: KubernetesObject[],
    namespace?: string,
  ): Promise<KubernetesObject[]> {
    return this.syncResources(context, manifests, 'apply', namespace);
  }
```

We are passing in `apply` as the namespace!

After removing the 'apply' statement, you can edit it and it now works as usual.
 

### Operating system

mac m1

### Installation Method

None

### Version

1.10.2

### Steps to reproduce

1. Edit any Kubernetes YAML
2. See you get a resourceVersion error..

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
fix: remove incorrect 'apply' namespace from applyResourcesFromYAML

### What does this PR do?

Removes the 'apply' namespace from applyResourcesFromYAML which was
causing problems.

### Screenshot / video of UI

https://github.com/containers/podman-desktop/assets/6422176/24fc3f03-4872-4756-abc6-124ac8035047

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/7594

### How to test this PR?

- [X] Tests are covering the bug fix or the new feature

You can now edit any k8s YAML without having to remove resourceVersion.

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
@deboer-tim @feloy if you are able to have a quick look :)

File: packages/main/src/plugin/kubernetes-client.ts [hunk 1]
```diff
@@ -1116,7 +1116,7 @@ export class KubernetesClient {
    */
   async applyResourcesFromYAML(context: string, yaml: string): Promise<KubernetesObject[]> {
     const manifests = await this.loadManifestsFromYAML(yaml);
-    return this.applyResources(context, manifests, 'apply');
+    return this.applyResources(context, manifests);
```
Comment (feloy) [inline packages/main/src/plugin/kubernetes-client.ts:1119]: It seems by reading the code that if you don't pass the `namespace` value, the action will be done in the `default` namespace. Have you tested in a non-`default` namespace?

Comment (cdrage) [reply packages/main/src/plugin/kubernetes-client.ts:1119]: Yup, it will work for a non-default namespace as the apply resources will prioritize the `namespace:` declaration in the file over whatever has been passed in to the function.


https://github.com/containers/podman-desktop/assets/6422176/c0039780-3635-460e-a710-a462b2cbf7f7

**Review by feloy — APPROVED** [review]

File: packages/main/src/plugin/kubernetes-client.ts (hunk 1 above)
Comment (cdrage) [reply packages/main/src/plugin/kubernetes-client.ts:1119]: https://github.com/containers/podman-desktop/assets/6422176/5f3255de-6f03-4499-8abd-fdea16019e33

I realized I uploaded the wrong file, but the same still applies (editing yaml)
