### PR TITLE
fix: wsl2 detection

### LINKED ISSUE #857: [0.9.1] Windows 10 WSL2 installation not detected
### Bug description

Can't install Podman through the Podman Desktop Dashboard because it is not recognizing my WSL2 installation.

### Operating system

Windows 10 Pro

### Version

0.9.1

### Steps to reproduce

This version of windows requires a manual installation of the wsl2 kernel: [https://learn.microsoft.com/en-us/windows/wsl/install-manual](https://learn.microsoft.com/en-us/windows/wsl/install-manual)

---

I've already own an OpenSuse Tumbleweed configured with version 2 before:
wsl2-2

---

Install the Podman Desktop application then, on the Dashboard, try to install Podman:
podman-install

### Relevant log output

_No response_

### Additional context

This version of wsl2 does not support newer commands as `wsl --status`:
wsl2-3

---
`wsl --install` is not a valid command either:
wsl2-4

---
My spec:
Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
16,0 GB RAM
Windows 10 Pro 20H2 build 19042.985

Ps.: not on Windows Insiders Program

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
It change the way of WSL2, as suggested in https://github.com/containers/podman-desktop/issues/857#issuecomment-1323549582 I try to use `wsl --set-default-version 2` as command which ensures that user has wsl2 installed and it has permission to use it.

### Screenshot/screencast of this PR
n/a

### What issues does this PR fix or reference?
resolve https://github.com/containers/podman-desktop/issues/857

### CODE REVIEW

File: extensions/podman/src/podman-install.ts [hunk 1]
```diff
@@ -439,14 +439,27 @@ class WSL2Check extends BaseCheck {
...
+      if (!isWSL) {
+        if (isAdmin) {
+          return this.createFailureResult(
+            'WSL2 is not installed. Call "wsl --install" in terminal.',
+            'Install WSL',
+            'https://docs.microsoft.com/en-us/windows/wsl/install-manual',
+          );
+        } else {
+          return this.createFailureResult(
+            'WSL2 is not installed or you does not have permissions to run WSL2. Contact your Administrator to setup WSL2.',
```
Comment (benoitf) [inline extensions/podman/src/podman-install.ts]:
```suggestion
            'WSL2 is not installed or you do not have permissions to run WSL2. Contact your Administrator to setup WSL2.',
```

**Comment by benoitf** [comment]
it's not an issue to set WSL to 2 as a check if the user is using WSL1 (and do not want to set WSL2) or it'll just call a prompt ?

**Comment by evidolob** [comment]
Hmm, that is good point.
In other hand, podman CLI check wsl installation with `wsl --status` https://github.com/containers/podman/blob/main/pkg/machine/wsl/machine.go#L1147 
and also validates WSL feature with switching to wsl2: https://github.com/containers/podman/blob/main/pkg/machine/wsl/machine.go#L1173-L1175

So even if we don’t use switching to wsl2, podman CLI will do.

**Comment by benoitf** [comment]
image

**Review by benoitf — APPROVED** [review]
tested, worked on Windows 11 (French)
