### PR TITLE
fix: wrong margin in the update available modal

### LINKED ISSUE #9896: "Update now" button in "Update Available Now" modal is too close to window border
### UX Description

As can be seen from the screenshot below, the "Update now" button is touching the border of the modal window, maybe it should be a bit to the left?

Image

### Request type

UX analysis/suggestions for improvement

### Primary Contact

_No response_

### Deadline for request

_No response_

### PR DESCRIPTION
**Pull request by MarsKubeX**
### What does this PR do?

Remove unused div causing incorrect margin in 'Update Available' modal action buttons.

### Screenshot / video of UI

Captura de pantalla 2025-06-03 a las 15 01 08

### What issues does this PR fix or reference?

Fixes #9896 

### How to test this PR?

- [ ] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/dialogs/Dialog.svelte [hunk 1]
```diff
@@ -24,9 +24,11 @@ export let onclose: () => void = () => {
   </div>
 
   <div class="px-5 py-5 mt-2 flex flex-row w-full space-x-5">
+    {#if $$slots.validation}
```
Comment (axel7083) [inline packages/renderer/src/lib/dialogs/Dialog.svelte:27]: question: who is providing the validation slot?

**Review by axel7083 — APPROVED** [review]
LGTM, might be nice to show `before / after` screenshots in the PR, so we better understand the change.

Testing such thing is kinda tricky, so on my side I am fine with skipping it, since this is pretty trivial.

File: packages/renderer/src/lib/dialogs/Dialog.svelte (hunk 1 above)
Comment (benoitf) [inline packages/renderer/src/lib/dialogs/Dialog.svelte:27]: I think there is a formatting issue (div/slot) should be shifted for the lines below)

I have the feeling that the proposal is a workaround. I mean, what happens if there is validation slot, the issue will still be there no ?

so should it reduce the text of some buttons, handle the fix when there is validation turned on, make the default width longer ?

Comment (MarsKubeX) [reply packages/renderer/src/lib/dialogs/Dialog.svelte:27]: Fixed the wrong formatting. 
The parent component (Dialog) caused the layout issue. The content is displayed via the MessageBox component (which isn't modified here) and it simply shows messages, so it doesn't use the validation slot. If MessageBox ever needs validation support, I can add width then, but this fix aligns with its current use case.

**Review by cdrage — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
