### PR TITLE
fix: bulk delete on pods should call the pod deletion

### LINKED ISSUE #2954: Not possible to completely delete pods from the containers list
### Bug description

When deleting pods (selecting the "pod grouping item" from the containers list, all containers of the pod are not properly deleted and it remains "infra" container `podman-pause`. It even raises an error.

Capture d’écran 2023-06-22 à 09 53 27

The other containers are eventually deleted, but then the pods are still remaining:
Capture d’écran 2023-06-22 à 10 06 55

### Operating system

macOS Ventura 13.4

### Installation Method

Installer from website/GitHub releases

### Version

1.1.0

### Steps to reproduce

- Run the preload.sh script from https://github.com/redhat-developer/podman-desktop-demo/tree/main/primary-podify-demo 
- Stop the pods
- Try to delete them

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Allow to delete pod when selecting the pod in the list of containers

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/2954

### How to test this PR?

Select with bulk mode in containers list some pods
Click on delete. It should work (containers of the pod (all the pod) is deleted)

unit test provided

### CODE REVIEW

File: packages/renderer/src/lib/ContainerList.svelte [hunk 1]
```diff
@@ -340,6 +355,7 @@ function errorCallback(container: ContainerInfoUI, errorMessage: string): void {
       <button
         class="pf-c-button pf-m-primary"
         on:click="{() => deleteSelectedContainers()}"
+        aria-label="Delete selected containers"
```
Comment (deboer-tim) [inline packages/renderer/src/lib/ContainerList.svelte]: Nit: should probably say 'Delete selected containers and pods' or be generic, since it calls the function that correctly deletes pods (and containers) now.

**Review by deboer-tim — APPROVED** [review]

File: packages/renderer/src/lib/ContainerList.svelte (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/lib/ContainerList.svelte]: fixed
