### PR TITLE
fix: load compose logs async not await

### LINKED ISSUE #3349: no logs for compose group
### Bug description

From https://github.com/containers/podman-desktop/pull/3253#issuecomment-1651160907

I have compose project but going to the logs tab, everything is empty

It should display logs of all containers of the compose application

### Operating system

macOS Ventura

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

I used
https://gist.githubusercontent.com/benoitf/a94cff3545cb0992007dd1fc58287816/raw/d0b33311834d84ec1d6830b32a167af80c84926e/docker-compose-example.yaml

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
fix: load compose logs async not await

### What does this PR do?

* Loads all the compose containers asynchronously rather than using await.
* Adds simple tests for No logs, however, will have to add integration
  test for loading logs correcctly

### Screenshot/screencast of this PR

https://github.com/containers/podman-desktop/assets/6422176/3fb4556f-9746-45d3-91a7-23877f7c1ced

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/3349

### How to test this PR?

1. Test using Docker Compose example: https://gist.githubusercontent.com/benoitf/a94cff3545cb0992007dd1fc58287816/raw/d0b33311834d84ec1d6830b32a167af80c84926e/docker-compose-example.yaml
2. Compose logs will appear asynchronously now / while podman desktop
   retrieves the logs, rather than await for each container

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

File: packages/renderer/src/lib/compose/ComposeDetailsLogs.svelte [hunk 1]
```diff
@@ -82,8 +82,9 @@ async function fetchComposeLogs() {
       callback(name, `${colouredName} ${padding} | ${content}`);
     };
 
-    // Get the logs for the container
-    await window.logsContainer(container.engineId, container.id, logsCallback);
+    // Get the logs for the container asynchronously / all at the same time
+    // this will update the terminal as the logs come in.
+    window.logsContainer(container.engineId, container.id, logsCallback);
```
Comment (benoitf) [inline packages/renderer/src/lib/compose/ComposeDetailsLogs.svelte]: I think there is a missing catch here
( I think an eslint rule is still not applied but it would fail)

**Review by benoitf — CHANGES_REQUESTED** [review]
it requires promise.catch(your code) not try { }  catch

**Review by benoitf — APPROVED** [review]
image
