### PR TITLE
fix: handle compose format json that is no longer a JSON array object

### LINKED ISSUE #4357: Microcks Extension fails to initialize
### Bug description

When installing the Microcks Docker Desktop Extension on Podman Desktop there is an error that stops the containers to start.

### Operating system

macOS Ventura 13.6

### Installation Method

Brew (macOS)

### Version

1.4.0

### Steps to reproduce

Install podman desktop

Try to install the microcks extension:

hguerrero/microcks-docker-desktop-extension:0.2.2

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
handle new JSON output of docker-compose v2.21.+ which is in fact no longer JSON compliant
it's a set of JSON objects separated by newlines
related entry: https://github.com/docker/compose/pull/10918

### What issues does this PR fix or reference?

fixes https://github.com/containers/podman-desktop/issues/4357

### How to test this PR?

unit test

### CODE REVIEW

File: packages/main/src/plugin/contribution-manager.ts [hunk 1]
```diff
@@ -272,7 +272,18 @@ export class ContributionManager {
     try {
       jsonResultPs = JSON.parse(result.stdout);
     } catch (error) {
-      throw new Error(`unable to parse the result of the ps command ${result.stdout}`);
+      if (error instanceof SyntaxError) {
```
Comment (dgolovin) [inline packages/main/src/plugin/contribution-manager.ts:275]: @benoitf  Would simpler change, if code would check for '[' in the beginning of result.stdout and if it is missing fix stdout with
```
`[${result.stdout.replaceAll('\n', ',;')}]`
```
before parsing?

**Review by lstocchi — APPROVED** [review]
LGTM

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by cdrage — APPROVED** [review]
