### PR TITLE
fix: custom extension install modal buttons

### LINKED ISSUE #6999: Installation collection of extensions through the `Install Custom Extension` has inconsistent button
### Bug description

When installating a collection of extensions we have some weird `Done -> Install -> Done -> Install` with the models action buttons.

https://github.com/containers/podman-desktop/assets/42176370/f7550f3e-bc93-469d-b9de-02a056bf5b0a

### Operating system

Windows 11

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

Install a collection of extension

### Relevant log output

_No response_

### Additional context

```
Downloading sha256:[...].tar - [0 -> 100%]% - ([min]/[max])
Filtering image content...
Analyzing image [other extension]...
Downloading and extract layers...
Downloading sha256:[...].tar - [0 -> 100%]% - ([min]/[max])

etc.
```

We have a repetition of downloading images, filtering content and downloading images

https://github.com/containers/podman-desktop/blob/b6ffdbfe0ab31924356e07bf9c67d40b5059bf68/packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte#L148

And we are basing the state of the button on this percentage, which is a problem, as we can have several time the `100%` we should instead wait for the following line to be awaited

https://github.com/containers/podman-desktop/blob/b6ffdbfe0ab31924356e07bf9c67d40b5059bf68/packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte#L53

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

The `install` button of the custom extension installation modal was having a problem were it was changing from `install -> Done -> install` for each extension install when loading an extension pack.

This PR fixes that behavior by considering it is terminated when the `window.extensionInstallFromImage` is resolved (meaning all extensions has been installed).

### Screenshot / video of UI

Before https://github.com/containers/podman-desktop/issues/6999

After

https://github.com/containers/podman-desktop/assets/42176370/82ce9213-0e44-46e0-96ed-b0451a3575b2

### What issues does this PR fix or reference?

Fixes https://github.com/containers/podman-desktop/issues/6999

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte [hunk 1]
```diff
@@ -138,14 +138,14 @@ function handleKeydown(e: KeyboardEvent) {
...
-          {#if progressPercent !== 100}
+          {#if installInProgress || progressPercent !== 100}
             <Button
               icon="{faCloudDownload}"
               disabled="{inputfieldError !== undefined}"
               on:click="{() => installExtension()}"
               inProgress="{installInProgress}">Install</Button>
           {/if}
-          {#if progressPercent === 100}
+          {#if progressPercent === 100 && !installInProgress}
```
Comment (deboer-tim) [inline packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte]: Would be nice to switch the order of this to match the others.

**Review by deboer-tim — APPROVED** [review]
IMHO we should also fix the progress monitor to be the overall progress at some point, but this issue is definitely the worse problem.

File: packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte (hunk 1 above)
Comment (axel7083) [inline packages/renderer/src/lib/extensions/InstallManuallyExtensionModal.svelte]:
```suggestion
          {#if !installInProgress && progressPercent === 100}
```
