### PR TITLE
fix: dispose existing port forwards on delete

### LINKED ISSUE #9561: `KubernetesClient#deletePortForward` do not dispose the server
### Bug description

I was working on https://github.com/containers/podman-desktop/issues/9273 and https://github.com/containers/podman-desktop/issues/9275 and I found a problem with the way we _delete_ port foward added in https://github.com/containers/podman-desktop/pull/7379

When we delete a port forward we get the `KubernetesPortForwardService`

https://github.com/containers/podman-desktop/blob/2600ef0449b96d916cf282437d1320fbb5e1bbf1/packages/main/src/plugin/kubernetes/kubernetes-client.ts#L1772-L1774

The service itself ask the configuration to delete it

https://github.com/containers/podman-desktop/blob/2600ef0449b96d916cf282437d1320fbb5e1bbf1/packages/main/src/plugin/kubernetes/kubernetes-port-forward-service.ts#L105-L108

And the configuration remove it from its configuration: **but do not dispose the server!!**

https://github.com/containers/podman-desktop/blob/2600ef0449b96d916cf282437d1320fbb5e1bbf1/packages/main/src/plugin/kubernetes/kubernetes-port-forward-storage.ts#L324-L332

## Why ?

When we start the port forward, we do not store the disposable, meaning, we are never able to remove it.

https://github.com/containers/podman-desktop/blob/2600ef0449b96d916cf282437d1320fbb5e1bbf1/packages/main/src/plugin/kubernetes/kubernetes-client.ts#L1768

The only places where the disposables are stored are in the `KubernetesPortForwardService`, but they are an unusable Array<IDisposable>

https://github.com/containers/podman-desktop/blob/ec3ee08dbe4ff0343f5cb12f70756d286c4f1e8a/packages/main/src/plugin/kubernetes/kubernetes-port-forward-service.ts#L68

### Operating system

Fedora 40

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. start a port foward using code from https://github.com/containers/podman-desktop/pull/7379
2. call delete
3. assert server still running

### Relevant log output

_No response_

### Additional context

We would need to have somewhere, probably the `KubernetesPortForwardService` a Map linking a resources to the disposable, or something similar

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #9561

### What does this PR do?

Dispose an existing port forwarding on delete

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#9561 

### How to test this PR?

Run `pnpm test:main`

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/kubernetes/kubernetes-port-forward-service.ts [hunk 1]
```diff
@@ -79,6 +79,10 @@ export class KubernetesPortForwardService implements IDisposable {
     this.#disposables.forEach(disposable => disposable.dispose());
```
Comment (axel7083) [inline packages/main/src/plugin/kubernetes/kubernetes-port-forward-service.ts:79]: not sure this works anymore, as the `disposables` is now a Map instead of an array, maybe we need something like `Array.from(this.#disposables.values()).forEach(disposable => disposable.dispose());`

**Review by axel7083 — APPROVED** [review]
LGTM

**Review by gastoner — APPROVED** [review]
