### PR TITLE
fix: Improve task names

### LINKED ISSUE #2605: Inconsistent task names
### Bug description

Try a variety of tasks. Most use a different naming pattern (e.g. "Create X" vs "Creating X" vs "X") that's inconsistent, some are wrong (e.g. "Creating a Kind provider") and in some cases so long it's not readable in the task manager:
Screenshot 2023-05-22 at 9 42 00 AM

### Operating system

macOS 13.3 M1

### Version

1.0.x

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

Task names were inconsistent:
- Most described the task ('Create X') others what it was doing ('Creating X'), made this consistent using the task.
- Actions on providers were including the provider name, which made it too long to fit in the task manager, removed this.
- Creation tasks called everything a provider (e.g. 'Creating a Kind provider'), switched to use the same display name as the UI (e.g. 'Create Kind cluster').
- Build task just used the image name, added 'Build' for consistency.

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

Fixed #2605.

### How to test this PR?

Create a couple providers, start/stop instances, and attempt to build a container file.

### CODE REVIEW

File: packages/renderer/src/lib/image/build-image-task.ts [hunk 1]
```diff
@@ -64,7 +64,7 @@ export function startBuild(imageName: string, buildImageCallback: BuildImageCall
   buildCallbacks.set(key, buildImageCallback);
 
   // start a task
-  const task = createTask(imageName);
+  const task = createTask('Build ' + imageName);
```
Comment (benoitf) [inline packages/renderer/src/lib/image/build-image-task.ts]:
```suggestion
  const task = createTask(`Build ${imageName}`);
```

File: packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte [hunk 2]
```diff
@@ -56,7 +56,7 @@ async function restartConnectionProvider(
   if (providerConnectionInfo.status === 'started') {
     updateConnectionStatus(provider, providerConnectionInfo, 'restart');
     const loggerHandlerKey = startTask(
-      `Restart ${provider.name} ${providerConnectionInfo.name}`,
+      `Restart ${providerConnectionInfo.name}`,
```
Comment (benoitf) [inline packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte:59]: If you remove the provider name it means you may see inaccurate data ?

File: packages/renderer/src/lib/image/build-image-task.ts (hunk 1 above)
Comment (deboer-tim) [reply packages/renderer/src/lib/image/build-image-task.ts]: Fixed.

File: packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte (hunk 2 above)
Comment (deboer-tim) [reply packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte:59]: Not sure I follow? It used to say `Restart Podman Podman Machine my-machine`, now it says `Restart Podman Machine my-machine`. Even the shorter cases like `Delete MicroShift` or if I can fully control the instance name I find it obvious enough and more natural.

Comment (benoitf) [reply packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte:59]: I mean, if a user has two instances of Podman it will say Restart Podman Machine my-machine while before you have a way to know it was for 'Podman' Provider or for 'Lima' for example (if machine have the same name)

maybe we need an extra field on task to add this kind of secondary information

Comment (benoitf) [reply packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte:59]: like the source of the message (in that case it'll be `Podman`)

Comment (deboer-tim) [reply packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte:59]: Ah. I have things uniquely named so length (and not getting the name I picked cut off) has been a bigger issue. How about `Restart ${providerConnectionInfo.name} (${provider.name})`?

Comment (benoitf) [reply packages/renderer/src/lib/preferences/PreferencesConnectionActions.svelte:59]: I think for now nobody has multiple vendors with the same name so let's get rid of it but probably we need the source field to better understand who is adding what in the task manager

**Review by benoitf — APPROVED** [review]
