### PR TITLE
fix: menus are not unregistered upon extension deactivation

### LINKED ISSUE #2069: Mutliple same options (Push image to kind cluster) in kebab menu over image item - caused by Kind extenions activation/deactivation process
### Bug description

Screenshot_20230413_152444

### Operating system

Fedora 37

### Version

next (development version)

### Steps to reproduce

One needs to probably have kind installed on PD. Then when Kind extension is activated/deactivated in Settings -> Extensions, another context menu item (Push image to Kind) is added. Extensions Activation/Deactivation call is not cleaning up properly.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2069

### What does this PR do?

Unregister contributed menus when extension is stopped

### What issues does this PR fix or reference?

Fixes #2069

### How to test this PR?

Stop and start Kind extension and make sure the Push to cluster menu appears only once on the Images tab

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM 

my only concern is that we should add some rule to avoid duplicate commands. I think it's possible that two extensions contribute to the same menu with two command having the same name. In that case one will overwrite the other.
BTW this fixes our current issue, this is why i gave my LGTM, not sure if you want to fix this other thing in another PR.

**Review by cdrage — COMMENTED** [review]
LGTM. I have the same concern as @lstocchi regarding adding logic regarding adding multiple same-named menus.

**Review by cdrage — APPROVED** [review]

File: packages/main/src/plugin/extension-loader.ts [hunk 1]
```diff
@@ -797,6 +797,18 @@ export class ExtensionLoader {
...
+    if (analyzedExtension) {
+      const extensionConfiguration = analyzedExtension.manifest?.contributes?.configuration;
+      if (extensionConfiguration) {
+        this.configurationRegistry.deregisterConfigurations([extensionConfiguration]);
+      }
+      const menus = analyzedExtension.manifest?.contributes?.menus;
+      if (menus) {
+        this.menuRegistry.unregisterMenus(menus);
+      }
+    }
```
Comment (benoitf) [inline packages/main/src/plugin/extension-loader.ts]: probably need to move this upper before we delete it from activated extensions ?

**Review by benoitf — APPROVED** [review]
