### PR TITLE
fix: error during extension install overlaps with other components

### LINKED ISSUE #10898: Fix Error layout from the extension installation in the extension's catalog
### Bug description

If there is an error during extension installation, its not properly aligned/framed. please see pics:

Image

Image

### Operating system

Windows 10

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Install multiple extension at once in a fast manner.
2. Minikube, AI Lab, bootc, RH Extensions Pack (this one is important), Image Layers, etc.
3. This is not expected workflow but it should show the errors.

I would expect error, that is especially long, to be better shown withing the extension catalog card and in the details.

### Relevant log output

```shell

```

### Additional context

We might consider better handling of parallel installation of the extension, but it is still not a standard process of installing extensions, imho.

### PR DESCRIPTION
**Pull request by jiridostal**
### What does this PR do?

When an error occurs during the installation of an extension, the error message is currently misaligned and can overlap with other UI components, especially when the message is lengthy. 

### Screenshot / video of UI

Before:
image
After:
image

### What issues does this PR fix or reference?

Fixes #10898

### How to test this PR?
Install multiple extension at once in a fast manner.

1. Minikube, AI Lab, bootc, RH Extensions Pack (this one is important), Image Layers, etc.
2. Should show the errors.

The error display has been moved outside of the <Button\> component. This ensures that the tooltip's hover behavior is independent of the button

### CODE REVIEW

File: packages/renderer/src/lib/featured/FeaturedExtensionDownload.svelte [hunk 1]
```diff
@@ -71,6 +71,7 @@ async function installExtension(): Promise<void> {
 }
 </script>
 
+<ErrorMessage icon wrapMessage class="-top-[15px] -right-0 absolute" error={errorInstall}/>
```
Comment (axel7083) [inline packages/renderer/src/lib/featured/FeaturedExtensionDownload.svelte]: question (non-blocking): the classes seems a bit odd to me? compare to the one bellow you added a `-` before `right-0`, is there any reason?

**Review by axel7083 — APPROVED** [review]
Tested and LGTM, (easier way is just to unplug internet) before clicking on download to test

> I test would be appreciated, but this is kinda tricky to test :/ we could check that the ErrorMessage component is called with the `icon` prop, but this is kinda implementation specific

File: packages/renderer/src/lib/featured/FeaturedExtensionDownload.svelte (hunk 1 above)
Comment (jiridostal) [reply packages/renderer/src/lib/featured/FeaturedExtensionDownload.svelte]: That must be a left-over from alignment experiments. Fixing the negative-zero value to a positive-zero :-)

**Review by MarsKubeX — APPROVED** [review]
LGTM, just take a look to the pending check
