### PR TITLE
fix: address unhandled race condition for logs to console after windo…

### LINKED ISSUE #13630: Javascript exception encountered after closing PD after starting or stopping podman machine
### Bug description

Currently it seems that there is a javascript exception being thrown if the user closes the Podman Desktop app right after starting or stopping the podman machine from PD.

https://github.com/user-attachments/assets/02bbdc51-b166-4d67-8d5f-1ca6964230c6

### Operating system

macOS

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

1. Either stop a running podman machine or start a stopped podman machine from PD Resources page.
2. After clicking the START or STOP buttons close PD (ensure that the Exit on Close option is enabled beforehand)
3. Notice that an exception popup is shown.

### Relevant log output

```shell
Uncaught Exception:
Error: Unable to find the main window
at PluginSystem.getWebContentsSender (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:610:2842)
at Object.log (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:612:40646)
at /Applications/Podman Desktop.app/Contents/Resources/app.asar/extensions/podman/packages/extension/builtin/podman.cdix/dist/extension.cjs:1:10483
at Array.forEach (<anonymous>)
at Xe.log (/Applications/Podman Desktop.app/Contents/Resources/app.asar/extensions/podman/packages/extension/builtin/podman.cdix/dist/extension.cjs:1:10470)
at Socket.<anonymous> (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:388:12630)
at Socket.emit (node:events:518:28)
at addChunk (node:internal/streams/readable:561:12)
at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
at Readable.push (node:internal/streams/readable:392:5)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bmahabirbu**
…w is destroyed

more specifically this race condition happened under a very narrow window. If the user quits the app while podman vm is stopping the code would try to log to the console during quiting and there was no safetly measure during the small window to prevent those logs from happening after the window shutdown.

### What does this PR do?

Fixes: https://github.com/podman-desktop/podman-desktop/issues/13630

### How to test this PR?

You're in for a rough time if you want to test this since the window is so narrow for the error to show up
dont checkout this pr 
Follow the instructions here with a small catch
https://github.com/podman-desktop/podman-desktop/issues/13630
when exiting podman desktop wait a moment to see maybe 2 logs before quitting
if your luckly you should spot the os crash dialog for the uncaught exception
this pr aims to catch this error and avoid the dialog crash

- [ x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/index.ts [hunk 1]
```diff
@@ -3164,19 +3164,22 @@ export class PluginSystem {
   }
 
   getLogHandler(channel: string, loggerId: string): LoggerWithEnd {
+    // Helper function to safely send to renderer, handling shutdown race condition
+    const safeSend = (messageType: string, data?: unknown): void => {
+      if (!this.isQuitting) {
+        try {
+          this.getWebContentsSender().send(channel, loggerId, messageType, data);
+        } catch (err) {
```
Comment (simonrey1) [inline packages/main/src/plugin/index.ts]: I am afraid that this would silence other errors, it the check for isQuitting not enough that we have to add the try catch?

**Review by MarsKubeX — APPROVED** [review]
LGTM

**Review by simonrey1 — APPROVED** [review]
LGTM, seems safe to catch and log error using the console instead.

+ the isQuitting avoid continuing to send logs after

**Comment by bmahabirbu** [comment]
removed unnecessary isquitting we should log errors to console during isquitting but just make sure to handle the no window error
