### PR TITLE
fix: display context name for Kubernetes pods

### LINKED ISSUE #2154: Differentiate the provider on where the Pods are running
In the list of containers, it is possible to differentiate in which provider the container is running.

On the list of pods, I should be able to know where the pod is running:
- Locally with Podman
- On my Kubernetes context

We should be able to provide a pretty name for:
- Kind running locally
- OpenShift Local
- Devsanbox

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2154

### What does this PR do?

Display the Kubernetes context name for Kubernetes pods. As the context can be long (Sandbox), it is shortened to 16 characters and tooltip shows the whole context name

### Screenshot/screencast of this PR

context

### What issues does this PR fix or reference?

Fixes #2154

### How to test this PR?

1. Have one pods running on Kubernetes
2. Go to the Pods list tab

### CODE REVIEW

File: packages/main/src/plugin/kubernetes-client.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ function toContainerStatus(state: V1ContainerState | undefined): string {
   return 'Unknown';
 }
 
-function toPodInfo(pod: V1Pod): PodInfo {
+function toPodInfo(pod: V1Pod, contextName: string | undefined): PodInfo {
```
Comment (benoitf) [inline packages/main/src/plugin/kubernetes-client.ts]:
```suggestion
function toPodInfo(pod: V1Pod, contextName?: string): PodInfo {
```

File: packages/main/src/plugin/kubernetes-client.ts [hunk 2]
```diff
@@ -88,7 +88,7 @@ function toPodInfo(pod: V1Pod): PodInfo {
     Namespace: pod.metadata?.namespace || '',
     Networks: [],
     Status: pod.status?.phase || '',
-    engineId: 'kubernetes',
+    engineId: contextName || 'kubernetes',
```
Comment (benoitf) [inline packages/main/src/plugin/kubernetes-client.ts]:
```suggestion
    engineId: contextName ?? 'kubernetes',
```

just a suggestion, I saw that we should use nullish coalescing runtime operatorbut you can keep || a linter rule will come soon

File: packages/main/src/plugin/kubernetes-client.ts (hunk 1 above)
Comment (benoitf) [reply packages/main/src/plugin/kubernetes-client.ts]: optional parameter will fit better

**Review by benoitf — APPROVED** [review]

**Comment by deboer-tim** [comment]
'Kubernetes' is pretty long, do you think we need it in the name or is the context enough? Removing or shortening would allow a few more characters for the context, or we could do something like 'deboer/.../namespace' (omitting the middle bits since the ends are usually the most useful).

I'm ok merging, we can always try this and change the label later.

**Comment by benoitf** [comment]
replace `Kubernetes` by `k8s` ?

**Comment by deboer-tim** [comment]
Or a single-color Kubernetes wheel at the start? I think I like that best, but we could do later.
