### PR TITLE
fix: start extensions once UI and System are ready

### LINKED ISSUE #1760: Podman desktop hung on "Initializing..." screen
### Bug description

When extension try to use `showInputBox` API function in it's `activate` function, podman desktop is not able to finish load, and hung on `Initializing...` loader screen:

Screenshot 2023-03-21 at 16 19 12

There are no error logs/messages, app just hung on that screen.

### Operating system

 macOS 13.2.1 Intel

### Version

0.12.0

### Steps to reproduce

Create an extension with this code:
```typescript
export async function activate(extensionContext: extensionApi.ExtensionContext): Promise<void> {
  const result = await extensionApi.window.showInputBox({
    prompt: 'Provide something',
  });
  await extensionApi.window.showInformationMessage(result, 'OK');
}
```

And try to start podman desktop with that extension.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Ensure extensions are started once UI and Plugin System is initialized
before we were waiting the end of the extensions to hide the 'initialize' method
but if an extension was prompting for input it was not displayed.

Now, it correctly waits the prompt.

I've done some chore using extra commits to make it more readable.

### Screenshot/screencast of this PR

we have the prompt when starting Podman Desktop 
image

### What issues does this PR fix or reference?

Fixes #1760 

### How to test this PR?

Unit tests
You can also use the test case of the referenced issue.

### CODE REVIEW

File: packages/renderer/src/Loader.svelte [hunk 1]
```diff
@@ -12,7 +12,7 @@ let loadingSequence;
 onMount(async () => {
   loadingSequence = setInterval(() => {
     toggle = !toggle;
-  }, 2000);
+  }, 100);
```
Comment (cdrage) [inline packages/renderer/src/Loader.svelte:15]: Is this intentional? Checking every 100 milliseconds, just checking.

**Review by cdrage — CHANGES_REQUESTED** [review]
One small comment, otherwise LGTM.

Went ahead and was able to start it up / no issues with either running `yarn watch` or `yarn compile` and running the binary. It's able to start up correctly / start the extensions once the UI was initialized.

File: packages/renderer/src/Loader.svelte (hunk 1 above)
Comment (benoitf) [reply packages/renderer/src/Loader.svelte:15]: yes it was intentional, just to do not wait extra time

**Review by cdrage — APPROVED** [review]
LGTM
