### PR TITLE
fix: fix sidebar and page size

### LINKED ISSUE #2320: Left sidebar does not resize properly while in settings
### Bug description

The left sidebar does not resize properly while in settings.

Capture d’écran 2023-05-03 à 10 27 36

### Operating system

Ventura 13.3.1

### Version

next (development version)

### Steps to reproduce

- Display the settings of Podman Desktop
- Create a new machine
--> At this stage the left sidebar is properly displayed.
- Hit the button "create"
--> If you scroll a little bit, you'll see the leftsidebar with an empty area.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR fixes a problem with the sidebar not having the right height when going on a page with a long list and also the size of the internal page (the background wasn't taking the full height and the full width resulting in having a part black and one gray)

### Screenshot/screencast of this PR

fix-ui

### What issues does this PR fix or reference?

it fixes #2320 and maybe #2322

### How to test this PR?

1. start PD and check that the sidebar and background on pages that are larger than the window works correctly

### CODE REVIEW

File: packages/renderer/src/AppNavigation.svelte [hunk 1]
```diff
@@ -89,7 +89,8 @@ export let meta;
 
 <svelte:window />
 <nav
-  class="pf-c-nav z-0 group w-[54px] min-w-[54px] flex flex-col justify-between overflow-hidden hover:overflow-y-auto"
+  class="pf-c-nav z-0 group w-[54px] min-w-[54px] flex flex-col justify-between overflow-hidden hover:overflow-y-auto top-0"
+  style="position: sticky"
   aria-label="Global">
```
Comment (benoitf) [inline packages/renderer/src/AppNavigation.svelte:94]: 'sticky' does not work ?

Comment (lstocchi) [reply packages/renderer/src/AppNavigation.svelte:94]: `pf-c-nav` class override it with `relative`

**Review by benoitf — APPROVED** [review]
https://user-images.githubusercontent.com/436777/235917597-ee707875-9fc7-4fd5-a602-6f43832142a8.mp4

**Review by cdrage — APPROVED** [review]
LGTM. It fixed the side bar and no more sizing issues.
