### PR TITLE
fix: autostarted connection fires onDidUpdateContainerConnection

### LINKED ISSUE #9929: After restarting Kind Cluster disappears from Podman-Desktop Resources
### Bug description

I have created one Kind Cluster and after restart MacOSX no more found the cluster created and for that not possible start the cluster.
If I install the kind command and create new cluster via command line the cluster before created on appear and is possible start and delete the new cluster created via command line. This is my workatound to work for while not corrected that issue.Image

### Operating system

masOS Sonoma

### Installation Method

Brew (macOS)

### Version

next (development version)

### Steps to reproduce

Create kind cluster on podman-desktop => Restart macosx Sonoma 15.1 => Open Podman-Desktop/Resources => No more Kind Cluster.

To appear kind cluster:
Install kind cli => Execute kind create cluster => Return to Podman-Desktop/Resources => The kind cluster created on Podman-Desktop appear newly.

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by feloy**
Signed-off-by: Philippe Martin <phmartin@redhat.com>

### What does this PR do?

- When a provider's connection is auto-started, wait for api to be attached before to send onDidUpdateProvider event

- On Kind extension, search kind clusters when onDidUpdateProvider event is received

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

Fixes #9929 

### How to test this PR?

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/provider-registry.ts [hunk 1]
```diff
@@ -399,8 +399,22 @@ export class ProviderRegistry {
     // grab the provider
     const provider = this.getMatchingProvider(internalId);
 
-    await autoStart.start(new LoggerImpl());
-
+    let updateContainerConnectionCalled: boolean = false;
+    const context = {
+      updateContainerConnection: (containerProviderConnection: ContainerProviderConnection): void => {
+        updateContainerConnectionCalled = true;
+        const providerConnectionInfo = this.getProviderConnectionInfo(containerProviderConnection);
```
Comment (benoitf) [inline packages/main/src/plugin/provider-registry.ts:411]: question: should we check that this object is matching one being registered by this provider id ? before handling it

to be sure the extension is not giving us another object from other extension/whatever ?

File: packages/main/src/plugin/provider-registry.ts [hunk 2]
```diff
@@ -399,8 +399,22 @@ export class ProviderRegistry {
     // grab the provider
     const provider = this.getMatchingProvider(internalId);
 
-    await autoStart.start(new LoggerImpl());
-
+    let updateContainerConnectionCalled: boolean = false;
+    const context = {
```
Comment (benoitf) [inline packages/main/src/plugin/provider-registry.ts]: question Use Object.freeze or readonly to ensure we can't modify the value of the context object

File: packages/extension-api/src/extension-api.d.ts [hunk 3]
```diff
@@ -607,13 +607,17 @@ declare module '@podman-desktop/api' {
...
+  }
+
   /**
    * By providing this interface, when Podman Desktop is starting
    * It'll start the provider through this interface.
    * It can be turned off/on by the user.
    */
   export interface ProviderAutostart {
-    start(logger: Logger): Promise<void>;
+    start(logger: Logger, context?: AutostartContext): Promise<void>;
```
Comment (jeffmaury) [inline packages/extension-api/src/extension-api.d.ts:625]: Maybe explain why the context should be used

File: packages/main/src/plugin/provider-registry.ts (hunk 1 above)
Comment (jeffmaury) [reply packages/main/src/plugin/provider-registry.ts:411]: Is that being handled ?

**Review by jeffmaury — COMMENTED** [review]
See https://github.com/podman-desktop/podman-desktop/pull/10970/files#r1950486331

File: packages/main/src/plugin/provider-registry.ts (hunk 1 above)
Comment (feloy) [reply packages/main/src/plugin/provider-registry.ts:411]: Yes, I added this code to handle it (line 405):

```
if (!this.isContainerProviderConnectionRegistered(provider, containerProviderConnection)) {
  throw new Error(
    `container connection ${containerProviderConnection.name} is not registered by provider ${provider.name}`,
  );
} 
```

**Review by benoitf — APPROVED** [review]

**Comment by feloy** [comment]
@jeffmaury as discussed this morning, I can correctly restart a kind cluster after stopping/starting the podman machine on which it runs


https://github.com/user-attachments/assets/55a204d1-2842-49ae-84a8-e9a012279157

File: packages/main/src/plugin/provider-registry.spec.ts [hunk 4]
```diff
@@ -444,6 +449,172 @@ describe('should send events when starting a container connection', async () =>
...
+        socketPath: '/endpoint1.sock',
+      },
+      status: 'started',
+      vmType: {
+        id: 'libkrun',
+        name: 'libkrun',
+      },
+    };
+
+    containerProviderConnection = {
```
Comment (axel7083) [inline packages/main/src/plugin/provider-registry.spec.ts]: If connection and containerProviderConnection are never updated, they should not be part of the beforeEach, they should be defined outside as they are constants

File: packages/main/src/plugin/provider-registry.spec.ts [hunk 5]
```diff
@@ -444,6 +449,172 @@ describe('should send events when starting a container connection', async () =>
...
+    test('should send events when api is directly attached', async () => {
+      vi.mocked(containerRegistry.isApiAttached).mockReturnValue(true);
+
+      let onBeforeDidUpdateContainerConnectionCalled = 0;
+      providerRegistry.onBeforeDidUpdateContainerConnection(event => {
+        expect(event.connection.name).toBe(connection.name);
+        expect(event.connection.type).toBe(connection.type);
+        expect(event.status).toBe(onBeforeDidUpdateContainerConnectionCalled ? 'started' : 'starting');
+        onBeforeDidUpdateContainerConnectionCalled++;
+      });
```
Comment (axel7083) [inline packages/main/src/plugin/provider-registry.spec.ts]: I feel like this should more "vitest / jest" synthax like, instead of counting manually the calls

```ts
const onBeforeDidUpdateContainerConnectionListenerMock = vi.fn();
providerRegistry.onBeforeDidUpdateContainerConnection(onBeforeDidUpdateContainerConnectionListenerMock);
...
expect(onBeforeDidUpdateContainerConnectionListenerMock).toHaveBeenCalledTimes(2);
expect(onBeforeDidUpdateContainerConnectionListenerMock).toHaveBeenNthCalledWith(1, expect.objectContaining({
  connection: expect.objectContaining({
    name: connection.name,
    type: connection.type,
  }),
  status: 'starting'
}));
expect(onBeforeDidUpdateContainerConnectionListenerMock).toHaveBeenNthCalledWith(2, expect.objectContaining({
  connection: expect.objectContaining({
    name: connection.name,
    type: connection.type,
  }),
  status: 'started'
}));
```

**Review by axel7083 — COMMENTED** [review]
Left some comments on the tests

**Review by jeffmaury — APPROVED** [review]
LGTM

File: packages/main/src/plugin/provider-registry.spec.ts (hunk 5 above)
Comment (feloy) [reply packages/main/src/plugin/provider-registry.spec.ts]: Yes you are right, I'll change. Thanks

**Review by axel7083 — APPROVED** [review]
LGTM
