### PR TITLE
fix(windows): fixed minimizing the app during startup

### LINKED ISSUE #13737: Start on minimize not honored
### Bug description

After latest update  start on minimize option doesn't work anymore; application starts normally and not in tray area

### Operating system

Win 11 enterprise 10.0.22631

### Installation Method

Other

### Version

1.21.0

### Steps to reproduce

Program has been automatically updated using auto update feature from 1.19.2 to 1.21.0.
I have unchecked and then rechecked option, but still won't work

### Relevant log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gastoner**
### What does this PR do?
Fixes windows minimizing during startup
Removes *.vbs script that causes not expected behaviour during startup, this file was a leftover after refactoring after https://github.com/podman-desktop/podman-desktop/pull/13056

### What issues does this PR fix or reference?
Closes #13737 

### How to test this PR?
Install older version of PD e.g. 1.18 check that in startup application there is an podman-desktop.vbs script
Install & run version from this PR 
Go to settings enable 'minimize on startup'. Restart system, the app should be started in tray 

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Not sure to understand the issue because 1.21 works fine on my laptop ?

**Comment by odockal** [comment]
> Not sure to understand the issue because 1.21 works fine on my laptop ?

At some point back in time I recall reproducing the problem. But today I cannot. I was testing this on my laptop I have at home, this time all seems working on the machine in the lab. I am not sure how is it possible.

**Comment by jeffmaury** [comment]
> > Not sure to understand the issue because 1.21 works fine on my laptop ?
> 
> At some point back in time I recall reproducing the problem. But today I cannot. I was testing this on my laptop I have at home, this time all seems working on the machine in the lab. I am not sure how is it possible.

Running `podman-desktop --minimized` or `podman-desktop --minimize` is the same on my machine

**Comment by gastoner** [comment]
@jeffmaury asking the user how is he starting the app (I have my suspicions that he is starting the app manually which should open it, and not start it just inthe  tray)

**Review by MarsKubeX — APPROVED** [review]
LGTM codewise. Not tested

**Review by dgolovin — APPROVED** [review]
I have it built locally and installed with after 1.19 left that vbs file behind.
The entry disappears from startup for me after first start.
LGTM.

**Review by odockal — APPROVED** [review]
LGTM.
* vbs script only for podman-desktop is removed from previous installation
* pd starts up maximized when user logs in (minimize disabled)
* pd starts up minimized when user logs in (minimize enabled)
* preferences option is respected and preserved between application restarts
* startup entry is added (non-vbs)

Tested on win 10.

File: packages/main/src/system/windows-startup.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@
  * SPDX-License-Identifier: Apache-2.0
  ***********************************************************************/
 
-import { existsSync } from 'node:fs';
+import { existsSync, unlink } from 'node:fs';
```
Comment (axel7083) [inline packages/main/src/system/windows-startup.ts:20]: can we use the promise version?

File: packages/main/src/system/windows-startup.ts [hunk 2]
```diff
@@ -55,6 +55,16 @@ export class WindowsStartup {
     const preferencesConfig = this.configurationRegistry.getConfiguration('preferences');
     const minimize = preferencesConfig.get<boolean>('login.minimize');
 
+    // after https://github.com/podman-desktop/podman-desktop/pull/13056 there is a leftover startup file that we need to remove
+    const windowsStartupFoler = path.resolve(app.getPath('appData'), 'Microsoft/Windows/Start Menu/Programs/Startup');
```
Comment (axel7083) [inline packages/main/src/system/windows-startup.ts:59]:
```suggestion
    const windowsStartupFoler = path.resolve(app.getPath('appData'), 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
```

I think this might be better than using manual delimiter

Comment (gastoner) [reply packages/main/src/system/windows-startup.ts:59]: Here I've just reverted previously removed lines
