### PR TITLE
fix: container start error is not reported

### LINKED ISSUE #6981: Switch to a Containers page after creating a container without entrypoint or command
### Bug description

When I have an image that I want to run, and there is no name picked up, nor entry point or command, the outcome of pressing the Start the container button visually does nothing. Since the page is not switched, I have no idea that I am actually creating containers (without them being actually started). I should be led to the Container's details page so I know that I am actually doing something.

creatingContainerPageSwitch

### Operating system

Windows 10

### Installation Method

None

### Version

1.10.0

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #6981

### What does this PR do?

Report error if container start errored

### Screenshot / video of UI

start-container-error

### What issues does this PR fix or reference?

#6981 

### How to test this PR?

1. Create a dummy image (FROM scratch)
2. Start this image

- [x] Tests are covering the bug fix or the new feature

### CODE REVIEW

File: packages/main/src/plugin/container-registry.ts [hunk 1]
```diff
@@ -1878,11 +1878,9 @@ export class ContainerProviderRegistry {
       }
 
       const engine = this.internalProviders.get(engineId);
-      if (engine) {
+      if (engine && (options.start === true || options.start === undefined)) {
+        await container.start();
```
Comment (benoitf) [inline packages/main/src/plugin/container-registry.ts:1882]: AFAIK we need to attach before starting a container

Comment (benoitf) [reply packages/main/src/plugin/container-registry.ts:1882]: else you may not receive the output

Comment (jeffmaury) [reply packages/main/src/plugin/container-registry.ts:1882]: The reason for the switch is the following:

- [Docker documentation](https://docs.docker.com/reference/cli/docker/container/attach/) mentions attach is for running containers
- podman attach (CLI) rejects if container is not running
- current behavoir in Podman Desktop is attach API call never returns

Comment (benoitf) [reply packages/main/src/plugin/container-registry.ts:1882]: you're correct, I checked the cli and order is the following

1.POST /v1.41/containers/create HTTP/1.1\r
2. POST /v1.41/containers/1784f98a7d5f2fa80950cc55a7ab066a6acf841066403ed61b3b04cf3b47a262/attach?stderr=1&stdin=1&stdout=1&stream=1 HTTP/1.1\r

**Review by benoitf — APPROVED** [review]
