### PR TITLE
bug: fix name display issues with compose files

### LINKED ISSUE #5028: An extra "-1" is added to container naming when deploying a compose file.
### Bug description

For some reason, Podman Desktop is adding an extra dash and number to container naming when deploying a Compose file:

```yaml
services:

  hello:
    container_name: hello
    image: cdrage/helloworld

  hello-1:
    container_name: hello-1
    image: cdrage/helloworld
```

See below:

Screenshot 2023-11-28 at 10 35 26 AM

Despite the fact that in `podman ps` the naming is fine:

```sh
▶ podman ps
CONTAINER ID  IMAGE                               COMMAND     CREATED             STATUS             PORTS       NAMES
43fad3c6735d  docker.io/cdrage/helloworld:latest              About a minute ago  Up About a minute              hello-1
b9b582c47e64  docker.io/cdrage/helloworld:latest              About a minute ago  Up About a minute              hello
```

### Operating system

mac m1

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Deploy:

```yaml
services:

  hello:
    container_name: hello
    image: cdrage/helloworld

  hello-1:
    container_name: hello-1
    image: cdrage/helloworld
```

Check PD UI and see that an extra `-1` has been added to the name.

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cdrage**
bug: fix name display issues with compose files

### What does this PR do?

We should be using Names from Podman container inspect to safely
determine the name. Relying on labels unfortunatly causes issues. After
much investigation, it's determined that the difference between a normal
compose file and one that uses `container_name` for services, is ONLY
the `Names` array returned in podman inspect. Labels do not change.

This PR adds the following:
* Uses Names rather than docker.compose.service labels in order to
  safely and more accurately determine a compose services name. This
  works by determining what the project name is and taking it away from
  Names array. Accurately does this even if container_name is supplied in
  compose.yaml

### Screenshot / video of UI

Screenshot 2024-07-10 at 12 00 28 PM

### What issues does this PR fix or reference?

Closes https://github.com/containers/podman-desktop/issues/5028

### How to test this PR?

- [X] Tests are covering the bug fix or the new feature

1. Test with a "normal" file and see that `-1` is added to compose
   names.

```yaml
services:

  redis-leader:
    image: redis:latest

  redis-replica:
    image: redis:latest
    command: redis-server --replicaof redis-leader 6379

  web:
    image: quay.io/kompose/web
```

2. Test with a compose file that uses `container_name`, and see that the
   container name is propagated:

```yaml
services:

  redis-leader:
    container_name: redis-leader
    image: redis:latest
    ports:
      - "6379"

  redis-replica:
    container_name: redis-replica
    image: redis:latest
    ports:
      - "6379"
    command: redis-server --replicaof redis-leader 6379

  web:
    container_name: web
    image: quay.io/kompose/web
    ports:
      - "8080:8080"
```

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

File: packages/renderer/src/lib/container/container-utils.ts [hunk 1]
```diff
@@ -32,17 +32,29 @@ import { ContainerGroupInfoTypeUI } from './ContainerInfoUI';
...
-        return `${composeService}-${composeContainerNumber}`;
-      }
-    }
+    // If the container has no name, return an empty string.
     if (containerInfo.Names.length === 0) {
       return '';
     }
+
+    // Safely determine if this is a compose project or not by checking the "service" or project label.
+    if (containerInfo.Labels?.['com.docker.compose.service'] || containerInfo.Labels?.['com.docker.compose.project']) {
```
Comment (lstocchi) [inline packages/renderer/src/lib/container/container-utils.ts]: Looks to me that checking `containerInfo.Labels?.['com.docker.compose.service']` is not necessary. 
If `containerInfo.Labels?.['com.docker.compose.service']` is defined and `containerInfo.Labels?.['com.docker.compose.project']` is undefined we get inside the if, but then the second if is skipped.

Comment (cdrage) [reply packages/renderer/src/lib/container/container-utils.ts]: Yeah you are right. We could just do `containerInfo.Labels?.['com.docker.compose.project']`

**Review by lstocchi — APPROVED** [review]
LGTM
