### PR TITLE
fix: Clear message box detail

### LINKED ISSUE #2541: Changing the OpenShift local preset in preferences shows a warning dialog with last opened URL via link in PD
### Bug description

I was deploying an app to the dev sandbox, then I started to play with openshift local.
When I am changing openshift preset in preferences I got a warning dialog "to apply changes you need to create new instance" and under that there is an sandbox route I used before:

sandboxroute-openshiftpresetchange

### Operating system

Fedora 37

### Version

1.0.0

### Steps to reproduce

1. Install OpenShift local
2. go to preferences OpenShift local ext.
3. Click on a link under pull secret file section - download from the ...
4. Try to change preset
5. ASSERT: Message contains correct text only
Actual result: correct text + last url visited in podman desktop

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by deboer-tim**
### What does this PR do?

The message box detail wasn't being cleared, so if you open one dialog that had a detailed message (e.g. External website) and then open another that doesn't, you still see the original dialog's detailed message.

### Screenshot/screencast of this PR

N/A. You should see the same as issue #2541 but without the odd detailed message (url in this case).

### What issues does this PR fix or reference?

Fixes #2541.

### How to test this PR?

Open an external link, then open another dialog and confirm the url is not there.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

File: packages/renderer/src/lib/dialogs/MessageBox.svelte [hunk 1]
```diff
@@ -25,6 +25,8 @@ const showMessageBoxCallback = async (options?: MessageBoxOptions) => {
   message = options.message;
   if (options.detail) {
     detail = options.detail;
+  } else {
+    detail = null;
```
Comment (benoitf) [inline packages/renderer/src/lib/dialogs/MessageBox.svelte]: I guess you mean undefined and not null ?

Comment (deboer-tim) [reply packages/renderer/src/lib/dialogs/MessageBox.svelte]: Yes, old Java habits die hard 😉. Fixed.
